### ISSUE TITLE
WES output changes with number of shards

### ISSUE THREAD

**Issue by chris-sf** [google/deepvariant#112]
I was running the whole exome example from here:
https://cloud.google.com/genomics/docs/tutorials/deepvariant#calling_exome_regions_configuration

```#!/bin/bash
set -euo pipefail
# Set common settings.
PROJECT_ID=PROJECT_ID
OUTPUT_BUCKET=gs://OUTPUT_BUCKET
STAGING_FOLDER_NAME=wes_staging
OUTPUT_FILE_NAME=wes_output.vcf
# Model for calling exome sequencing data.
MODEL=gs://deepvariant/models/DeepVariant/0.7.0/DeepVariant-inception_v3-0.7.0+data-wes_standard
IMAGE_VERSION=0.7.0
DOCKER_IMAGE=gcr.io/deepvariant-docker/deepvariant:"${IMAGE_VERSION}"
#
# Changing the number of chards changes the output for some reason
COMMAND="/opt/deepvariant_runner/bin/gcp_deepvariant_runner \
  --project ${PROJECT_ID} \
  --zones us-west1-* \
  --docker_image ${DOCKER_IMAGE} \
  --outfile ${OUTPUT_BUCKET}/${OUTPUT_FILE_NAME} \
  --staging ${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME} \
  --model ${MODEL} \
  --bam gs://deepvariant/exome-case-study-testdata/151002_7001448_0359_AC7F6GANXX_Sample_HG002-EEogPU_v02-KIT-Av5_AGATGTAC_L008.posiSrt.markDup.bam \
  --bai gs://deepvariant/exome-case-study-testdata/151002_7001448_0359_AC7F6GANXX_Sample_HG002-EEogPU_v02-KIT-Av5_AGATGTAC_L008.posiSrt.markDup.bai \
  --ref gs://deepvariant/exome-case-study-testdata/hs37d5.fa.gz \
  --regions gs://deepvariant/exome-case-study-testdata/refseq.coding_exons.b37.extended50.bed \
  --shards 64 \
  --make_examples_workers 8 \
  --make_examples_cores_per_worker 32 \
  --make_examples_ram_per_worker_gb 60 \
  --make_examples_disk_per_worker_gb 100 \
  --call_variants_workers 1 \
  --call_variants_cores_per_worker 32 \
  --call_variants_ram_per_worker_gb 60 \
  --call_variants_disk_per_worker_gb 50 \
  --max_preemptible_tries 5 \
  --gcsfuse"
# Run the pipeline.
gcloud alpha genomics pipelines run \
    --project "${PROJECT_ID}" \
    --service-account-scopes="https://www.googleapis.com/auth/cloud-platform" \
    --logging "${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME}/runner_logs_$(date +%Y%m%d_%H%M%S).log" \
    --regions us-west1 \
    --docker-image gcr.io/deepvariant-docker/deepvariant_runner:"${IMAGE_VERSION}" \
    --command-line "${COMMAND}"
```

Changing `--shards` to `128` changes the output in the VCF file. Running a diff between the two outputs shows that they are not the same. Why would that happen?

**Comment by pichuan** [comment]
Hi @chris-sf 
thanks for reporting the issue. We really don't expect the variant calling results to differ when we change the number of shards, but it seems like we can also see this issue when we try running WES case study with different number of shards. We'll investigate further to find out the root cause. But I can confirm I don't think this should be the behavior.

**Comment by pichuan** [comment]
From our experiments so far, it seems like the number of tensorflow.Examples coming out at the end of the `make_examples` stage already differ.
So that means even before the data touches the CNN classifier in TensorFlow, there are already some differences. This is still not quite I'd expect, but I could see maybe some differences happen when we partition things in different number of tasks. I'll take a closer look on `make_examples`.

For now, if you need to ensure reproducible and deterministic results, please also make sure to use the same number of shards.

**Comment by pgrosu** [comment]
Yeah, but @pichuan folks will then ask the obvious question of what would be the right number of shards to get the correct variant calls.  Probably some validation tests might be required with comparative benchmarks that show consistent predictability.  I'm sure you guys have done some of this already, which would be nice if it could be shared for optimally configuration of the settings.  Ideally it's something that users can then replicate themselves, in order to run verification tests at different granular stages of the DeepVariant workflow - and would be compared to validated metrics for proper evaluation - just to convince the users all is working properly.

**Comment by pichuan** [comment]
This was really puzzling me, so I started with a smallest possible reproducible setting and started debugging. 

Now I understand why the results are different. 

This update will be about the technical explanation of why different number of shards result in different result:

This is because when we're processing reads in a region, we (by default) first do a sampling of the reads down to `max_reads_per_partition` (default=1500) reads. Here is the code snippets that does that:

https://github.com/google/deepvariant/blob/r0.7/deepvariant/make_examples.py#L842-L844

```
    if self.options.max_reads_per_partition > 0:
      reads = utils.reservoir_sample(
          reads, self.options.max_reads_per_partition, self.random)
```

This was originally an optimization for speed. A while ago we noticed that some regions in the genome took really long time to create examples. And this is because some regions have a lot of reads piled up.
Because of the way that germline DeepVariant is set up, the final pileup image has only a image height of 100 anyway, so we don't really need to process all the reads. But at this stage we still need to go through the realigner step later, so we decided to sample enough reads here so that the following steps can still use more information, but we cut off at the number of `max_reads_per_partition` (default=1500) reads.

The randomization here is done with `self.random`, which is initialize with the same seed at the beginning. Because the seed is the same at the beginning, we're able to generate deterministic and reproducible results if you fix the number of tasks.

However, when you run make_examples with different number of tasks, that means each task has its own `self.random`. Even though each of them started with the same seed, when you have different number of tasks(shards), these RandomState ends up progressing differently. This means when you look at a same region in two different runs (for example, I was looking at `20:3208913-3209912` in the exome), they might be going through a different place of the random number.

That is the reason why if you run with different number of shards, the results are different.

@pgrosu , based on the reason above, you can understand that the number of tasks/shards won't actually correlate or explain which variant calling results will be better.

Currently our goal was to make sure every run with the same parameters has deterministic and reproducible results. I think we're still achieving that.
I need to adjust my previous belief that "our results coming out from `make_examples would be the same" is incorrect. The reason is explained above.

With the current code, if you want all runs (even with different number of shards) to be the same, you can set `--max_reads_per_partition 0`. This might cause the run to be much slower though. But after that, the results should be the same. If after adding that flag, results are still different, please let me know.

**Comment by pgrosu** [comment]
@pichuan I was assuming shards are the partitioning, but notice that via partitioning you might still be an issue even if you don't hit a depth of a 100.  You might be losing precision in your call by limiting the sample size to 1500.  Basically your call probability would basically be more precise with more reads.

**Comment by pichuan** [comment]
Hi @chris-sf 
Thanks again for reporting this issue. We made an internal change to address this issue, which should come out in the next release.
