### ISSUE TITLE
Using DeepVariant on Large Sample Size (WES or WGS)

### ISSUE THREAD

**Issue by shalabhsuman** [google/deepvariant#142]
- Can you suggest what would be the best strategy to optimize deepvariant variant calling on large sample sizes (>500 WES/ WGS samples)?
- Is Deepvariant optimized for N+1 Strategy or joint calling (I read there is an option for gVCF output) and if so, what would be the best way or recommended tool to convert multiple deepvariant's gVCFs (500 gVCFs) to one VCF??

**Comment by AndrewCarroll** [comment]
Hello @shalabhsuman,

We are currently working on recommendations for best practices to jointly call and merge cohorts of this size. We have a few similar size projects that we are conducting ourselves to be able to assess accuracy and scalability.

We have done some preliminary work in joint calling and merging cohorts (this was a component of a recent blog from our group https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/)

Our early investigations have used GLnexus (https://www.biorxiv.org/content/10.1101/343970v1) to combine gVCFs. Because the final recommendations will use gVCFs, if you generate the gVCF files now you should be able to merge these with the final recommended approach.

If you would be interested, we would be interested to collaborate you in the joint calling of these samples. This will help you get the best calls sooner, and will also help us evaluate and improve the merging methods we are developing.

**Comment by shalabhsuman** [comment]
Hi, thanks for responding. This is very helpful. Definitely will be interested in collaborating on this. I will get back to you with more information on that.
Also, apart from GLnexus, have you performed any testing using GATK4 to merge gVCFs (from Deepvariant) into final VCF? 

Shalabh

**Comment by AndrewCarroll** [comment]
Hi Shalabh,

We have performed internal benchmarks on merging of gVCFs with GATK and do not recommend this approach. I think it will be better to wait for recommendations on merging with GLnexus, or to collaborate directly.

**Comment by shalabhsuman** [comment]
Thank you. Do you have a timeline on when the benchmarks on GLnexus to combine gVCFs would be completed ?

**Comment by andrewrech** [comment]
Hello all,

My institution is conducting a cancer immunotherapy study involving >1000 WES and we are **highly** interested in evaluating deepvariant. I would like to be included in feasibility discussions, if you are willing, and we could potentially contribute resources to this effort.

Sincerely,

Andrew

@gunjanbaid @AndrewCarroll @shalabhsuman

**Comment by AndrewCarroll** [comment]
Hello @andrewrech,

Thank you for you interest. We are quite interested in collaborating on this effort, and the timeframe of Q2-Q4 is a good fit for our efforts. For these WES samples, will these be germline sequencing or somatic sequencing? 

I do not know the institutional requirements for access, but if you are able to add other investigators, our team may be interested to work closely with you on generating the individual calls, merging them, and evaluating the results.

**Comment by andrewrech** [comment]
Get's - let's follow up offline.

**Comment by mlin** [comment]
Hi I'm the GLnexus maintainer. From that side we're currently lacking a motivating, medium/large scale study with DeepVariant gVCF files which would provide the context to chase down the gnarly corner cases that arise in gVCF merging / joint genotyping, completing the current "experimental" integrated configuration. There are a few candidates in the pipeline but more would be really welcome. Ping me if I can help!

**Comment by gunjanbaid** [comment]
I'll close this issue for now but feel free to reopen if anyone has additional questions.

**Comment by AndrewCarroll** [comment]
Hi @andrewrech and @shalabhsuman

I wanted to update this issue with recent developments for cohort merging. With the DeepVariant v0.9 release, we recommend [Best practices for multi-sample variant calling with DeepVariant](https://github.com/google/deepvariant/blob/r0.9/docs/trio-merge-case-study.md)

Although this case study is a trio, we have optimized parameters for cohorts scaling into the 1000's, so we feel this will work well for your use cases.

Thank you.

**Comment by andrewrech** [comment]
Thank you Andrew, I'm looking forward to reading
