### ISSUE TITLE
bam index location issue for make_examples

### ISSUE THREAD

**Issue by ekofman** [google/deepvariant#149]
Hi (accidentally closed old issue prematurely)

Is there an argument to specify a bam index file's location in the make_examples step if it is different from the bam file? I am making symlinks for both, then running make_examples like so:

```
echo "Start running make_examples...Log will be in the terminal and also to make_examples.log."
    ( time seq 0 $((${numShards}-1)) | \
      parallel -k --line-buffer \
          /opt/deepvariant/bin/make_examples \
          --mode calling \
          --ref ${Fasta} \
          --reads bamlink \
          --examples "${sample_id}.examples.tfrecord@${numShards}.gz" \
          --gvcf "${sample_id}.gvcf.tfrecord@${numShards}.gz" \
          --task {} \
    ) 2>&1 | tee "make_examples.log"
```
And getting this error:

`ValueError: Not found: No index found for bamlink`

A little strange, because the bam index in question is indeed in the same location as the bam file-- these are the linking commands:

```
+ ln -s /cromwell_root/fc-.../dir_name/RP-1735/WGS/JN_G2701-1/v2/JN_G2701-1.bam bamlink
+ ln -s /cromwell_root/fc-.../dir_name/RP-1735/WGS/JN_G2701-1/v2/JN_G2701-1.bai bailink

```

So two questions:
1) Why doesn't this work?
2) Is there a way to specify the index file location separately, or am I going to have to simply copy the two files into a local folder together at the working directory level. This would be somewhat of a pain because the bam is hundreds of GB. Thanks!

Seems like there might be based on [this link] (https://cloud.google.com/genomics/docs/tutorials/deepvariant#additional_configuration_options)
But I can't find the equivalent just for the make_examples section

**Comment by gunjanbaid** [comment]
1. I believe this does not work because `make_examples` expects the following naming: 

* `<NAME>.bam` for the BAM file
* `<NAME>.bam.bai` for the index

2. There is no way to specify a separate name for the index file. However, you could try to name your symlinks as `data.bam` and `data.bam.bai`, shown below. I did not get a chance to test this out myself, but let me know if this does not work, and I can look into other possible solutions.

```
+ ln -s /cromwell_root/fc-.../dir_name/RP-1735/WGS/JN_G2701-1/v2/JN_G2701-1.bam data.bam
+ ln -s /cromwell_root/fc-.../dir_name/RP-1735/WGS/JN_G2701-1/v2/JN_G2701-1.bai data.bam.bai
```

Regarding the link you shared, the configuration options pertain to the `gcp_deepvariant_runner` which is part of a pipeline that can be used to run DeepVariant on Google Cloud. Based on your command above, it does not seem like you are using this pipeline, but correct me if I'm wrong.

**Comment by ekofman** [comment]
@gunjanbaid I think you're right about it being a configuration for a different pipeline. Thanks, I'll try using bam.bai instead of simply .bai and see if that works.

**Comment by gunjanbaid** [comment]
@ekofman were you able to resolve this issue?

**Comment by ekofman** [comment]
I think it actually does work with simply reads.bam and reads.bai. Yep!

**Comment by gunjanbaid** [comment]
@ekofman You are correct, thanks for pointing that out! I will modify my earlier response. Index files named as `<NAME>.bam.bai` **AND** `<NAME>.bai` are accepted.
