### ISSUE TITLE
Evaluation regions for HG002

### ISSUE THREAD

**Issue by AndrewCarroll** [google/deepvariant#15]
I notice that the numbers for exome precision and recall are given based on Refseq. There isn't anything wrong with this approach.

If it is of use, (https://www.nature.com/articles/sdata201625) indicates that the HG002 exome was generated with Agilent SureSelect. We've taken the SureSelect v5 BED (agilent_sureselect_human_all_exon_v5_b37_targets.bed) and intersected it with the GIAB confident regions for our exome evaluations. 

https://dl.dnanex.us/F/D/z8j2G3jYxjJfQ333z742KP2KkJb0Q32XJx34Xzyj/hg002_giab_intersect_agilent_sureselect.bed

**Comment by depristo** [comment]
Thank you! We weren't 100% certain the ideal dataset to evaluate the callset on. Personally I like to use two evaluation intervals: RefSeq alone and the capture intervals. RefSeq is nice because it is entirely orthogonal to the capture approach, which I feel is fair since the capture intervals are often only those where the capture proves to be effective, not actually where one wants to analyze their exome data (closer to RefSeq IMO). But I like replacing our refseq + 50 bp intervals with the capture intervals. 

Out of curiosity, why intersect the capture intervals upfront with the confident regions? Happy and VCFEval both will internally do that intersection if you call on the capture intervals and provide the confident regions for evaluation?

**Comment by AndrewCarroll** [comment]
That's a good question. We use this BED file to provide to the calling programs where possible so that we don't use compute performing calling in regions we won't be evaluating on. You are correct, doing the intersection in hap.py will work just fine in terms of the final results.

Here is the non-intersected BED file: 

https://dl.dnanex.us/F/D/y61fXf4qz5G8F4QvXz14bkYQ5Q9Yy5q5JPf1K3kg/agilent_sureselect_human_all_exon_v5_b37_targets.bed

**Comment by depristo** [comment]
Thanks Andrew! We've put this on our internal buganizer component for DeepVariant and we'll update the case study to use this.
