### ISSUE TITLE
Strange make_examples lag when trying to use 64 cores and shards for WGS

### ISSUE THREAD

**Issue by ekofman** [google/deepvariant#150]
Hi, with WGS (mm10, but the documentation says WGS human model should work for this), I got make_examples running fine with 4 cores and shards, but as soon as I go above 4 I get a strange lag. I'm running this recommended command:

```
echo "Start running make_examples...Log will be in the terminal and also to make_examples.log."
    ( time seq 0 $((${numShards}-1)) | \
      parallel -k --line-buffer \
          /opt/deepvariant/bin/make_examples \
          --mode calling \
          --ref ${Fasta} \
          --reads bamlink \
          --examples "${sample_id}.examples.tfrecord@${numShards}.gz" \
          --gvcf "${sample_id}.gvcf.tfrecord@${numShards}.gz" \
          --task {} \
    ) 2>&1 | tee "make_examples.log"
    echo "Done."
    echo

```
With 4, I get a nice stdout update per shard, first a description of the contigs:

`I0201 17:01:29.167016 140183113676544 make_examples.py:946] Common contigs are [u'chr1', u'chr10', u'chr11', u'chr12', u'chr13', u'chr14', u'chr15', u'chr16', u'chr17', u'chr18', u'chr19', u'chr1_GL456210_random', u'chr1_GL456211_random', u'chr1_GL456212_random', u'chr1_GL456213_random', u'chr1_GL456221_random', u'chr2', u'chr3', u'chr4', u'chr4_GL456216_random', u'chr4_JH584292_random', u'chr4_GL456350_random', u'chr4_JH584293_random', u'chr4_JH584294_random', u'chr4_JH584295_random', u'chr5', u'chr5_JH584296_random', u'chr5_JH584297_random', u'chr5_JH584298_random', u'chr5_GL456354_random', u'chr5_JH584299_random', u'chr6', u'chr7', u'chr7_GL456219_random', u'chr8', u'chr9', u'chrX', u'chrX_GL456233_random', u'chrY', u'chrY_JH584300_random', u'chrY_JH584301_random', u'chrY_JH584302_random', u'chrY_JH584303_random', u'chrUn_GL456239', u'chrUn_GL456367', u'chrUn_GL456378', u'chrUn_GL456381', u'chrUn_GL456382', u'chrUn_GL456383', u'chrUn_GL456385', u'chrUn_GL456390', u'chrUn_GL456392', u'chrUn_GL456393', u'chrUn_GL456394', u'chrUn_GL456359', u'chrUn_GL456360', u'chrUn_GL456396', u'chrUn_GL456372', u'chrUn_GL456387', u'chrUn_GL456389', u'chrUn_GL456370', u'chrUn_GL456379', u'chrUn_GL456366', u'chrUn_GL456368', u'chrUn_JH584304']`

then:

```
I0201 17:01:44.899904 140183113676544 make_examples.py:1030] Writing examples to RP-1735_JN_G2701-1_v2_WGS_OnPrem.examples.tfrecord-00002-of-00004.gz
I0201 17:01:44.900499 140183113676544 make_examples.py:1034] Writing gvcf records to RP-1735_JN_G2701-1_v2_WGS_OnPrem.gvcf.tfrecord-00002-of-00004.gz
2019-02-01 17:01:44.902018: I third_party/nucleus/io/sam_reader.cc:565] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0201 17:01:45.086961 140555261302528 make_examples.py:1030] Writing examples to RP-1735_JN_G2701-1_v2_WGS_OnPrem.examples.tfrecord-00001-of-00004.gz
I0201 17:01:45.087383 140555261302528 make_examples.py:1034] Writing gvcf records to RP-1735_JN_G2701-1_v2_WGS_OnPrem.gvcf.tfrecord-00001-of-00004.gz
2019-02-01 17:01:45.088430: I third_party/nucleus/io/sam_reader.cc:565] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0201 17:01:44.582973 140046530758400 make_examples.py:1030] Writing examples to RP-1735_JN_G2701-1_v2_WGS_OnPrem.examples.tfrecord-00003-of-00004.gz
I0201 17:01:44.583492 140046530758400 make_examples.py:1034] Writing gvcf records to RP-1735_JN_G2701-1_v2_WGS_OnPrem.gvcf.tfrecord-00003-of-00004.gz
2019-02-01 17:01:44.584969: I third_party/nucleus/io/sam_reader.cc:565] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0201 17:01:44.952101 140546703472384 make_examples.py:1030] Writing examples to RP-1735_JN_G2701-1_v2_WGS_OnPrem.examples.tfrecord-00000-of-00004.gz
I0201 17:01:44.952527 140546703472384 make_examples.py:1034] Writing gvcf records to RP-1735_JN_G2701-1_v2_WGS_OnPrem.gvcf.tfrecord-00000-of-00004.gz
2019-02-01 17:01:44.953547: I third_party/nucleus/io/sam_reader.cc:565] Setting HTS_OPT_BLOCK_SIZE to 134217728
```

It then starts outputting per site info:

`I0201 17:01:49.720201 140183113676544 make_examples.py:782] Found 0 candidates in chr1:2001-3000 [4.82s elapsed]
I0201 17:01:49.732466 140183113676544 make_examples.py:782] Found 0 candidates in chr1:6001-7000 [0.01s elapsed]
I0201 17:01:49.744833 140183113676544 make_examples.py:782] Found 0 candidates in chr1:10001-11000 [0.01s elapsed]
I0201 17:01:49.757262 140183113676544 make_examples.py:782] Found 0 candidates in chr1:14001-15000 [0.01s elapsed]
I0201 17:01:49.769794 140183113676544 make_examples.py:782] Found 0 candidates in chr1:18001-19000 [0.01s elapsed]`

However, when I go up in number of shards and cores, even to just 8, let alone the recommended 64, I don't get past this point:

 `Common contigs are [u'chr1', u'chr10', u'chr11', u'chr12', u'chr13', u'chr14', u'chr15', u'chr16', u'chr17', u'chr18', u'chr19', u'chr1_GL456210_random', u'chr1_GL456211_random', u'chr1_GL456212_random', u'chr1_GL456213_random', u'chr1_GL456221_random', u'chr2', u'chr3', u'chr4', u'chr4_GL456216_random', u'chr4_JH584292_random', u'chr4_GL456350_random', u'chr4_JH584293_random', u'chr4_JH584294_random', u'chr4_JH584295_random', u'chr5', u'chr5_JH584296_random', u'chr5_JH584297_random', u'chr5_JH584298_random', u'chr5_GL456354_random', u'chr5_JH584299_random', u'chr6', u'chr7', u'chr7_GL456219_random', u'chr8', u'chr9', u'chrX', u'chrX_GL456233_random', u'chrY', u'chrY_JH584300_random', u'chrY_JH584301_random', u'chrY_JH584302_random', u'chrY_JH584303_random', u'chrUn_GL456239', u'chrUn_GL456367', u'chrUn_GL456378', u'chrUn_GL456381', u'chrUn_GL456382', u'chrUn_GL456383', u'chrUn_GL456385', u'chrUn_GL456390', u'chrUn_GL456392', u'chrUn_GL456393', u'chrUn_GL456394', u'chrUn_GL456359', u'chrUn_GL456360', u'chrUn_GL456396', u'chrUn_GL456372', u'chrUn_GL456387', u'chrUn_GL456389', u'chrUn_GL456370', u'chrUn_GL456379', u'chrUn_GL456366', u'chrUn_GL456368', u'chrUn_JH584304']`

Then it just seems to lag, for up to 24 hours before I aborted the job because of cost concerns.

Any ideas of what might be happening under the hood such that 4 cores and shards seems to run immediately with no problem, but things just freeze and don't advance with more? 4 would be far too slow and expensive unfortunately for WGS, but I'm not sure how to get past this. Thanks in advance for any help.

**Comment by pgrosu** [comment]
Are you following the configurations as recommended on the following page, and specifying the number of workers as well?

https://cloud.google.com/genomics/docs/tutorials/deepvariant#pipeline_configurations

If so, then it will the Pipelines API is triggered, which basically makes custom machines of this form:

```
  machine_type = 'custom-{0}-{1}'.format(
      pipeline_args.make_examples_cores_per_worker,
      pipeline_args.make_examples_ram_per_worker_gb * 1024)
```

Ref: https://github.com/google/deepvariant/blob/r0.7/deepvariant/docker/gcp_deepvariant_runner.py#L305-L307

Also I believe that `make_examples` is restricted to one core based on this:

```
    if options.n_cores != 1:
      errors.log_and_raise(
          'Currently only supports n_cores == 1 but got {}.'.format(
options.n_cores), errors.CommandLineError)
```

Ref: https://github.com/google/deepvariant/blob/r0.7/deepvariant/make_examples.py#L1167-L1170

In any case, it will some time to explain the complete control flow, and if you look at the following two files I think you'll discover why based on the design of DeepVariant:

https://github.com/google/deepvariant/blob/r0.7/deepvariant/make_examples.py

https://github.com/google/deepvariant/blob/r0.7/deepvariant/docker/gcp_deepvariant_runner.py

Hope it helps,
~p

**Comment by pichuan** [comment]
Hi @ekofman , 
thanks for reporting this!

It seems like you're using the example from the WGS case study. From my experience, suppose you on a 4-core machine, if you specify a $numShards bigger than 4 (say, 64), `parallel` will actually still just run 4 at a time. Therefore, it might run 0-3 first. And when they finished, `parallel` will proceed with the range of 4-7, etc.

Because of that, if you run 64 shards on 4-core machine, you won't see all 64 jobs started at the same time. Can you first confirm whether that's the case for you? 
In your case, if somehow all 64 `make_examples` started on the same machine that 4 cores, it is possible that the machine starts becoming resource constrained and swapping a lot, therefore nothing will finish. But the first thing will be to check whether `parallel` handles this for you (which is my experience in the past).
@ekofman , please let me know what you observe. And, it'll also be useful to know how many cores are on your machine, and how much RAM. If you can check your system resources while you're running to see what resource might be exhausted, that will also be useful to know. If your BAM file is sharable / public, I'm also happy to run a few test runs myself. I expect changing $numShards should work, so I'd really like to know what went wrong here and fix it. Thanks!


The GCP runner code that @pgrosu mentioned is actually a separate example. The GCP runner config is evolving over time as well, so it's by no means the best (or only) config that we recommend. But it's a useful example to see how to orchestrate these jobs on multiple machines on Google Cloud. For example, the amount of RAM it requests for its workers can be a good example of how much you might need.
I'm adding @nmousavi, our collaborator on the Cloud team, as a FYI since Paul's comment mentioned the GCP runner.

**Comment by ekofman** [comment]
@pichuan Thanks for the feedback -- I have altered my WDL (I'm building this as a method on FireCloud) to include the lscpu command, and have run with 1, 4 and 64 cores/shards so hopefully I will get a better sense of what's going on and report back here.

**Comment by ekofman** [comment]
I'm currently testing on a low-pass WGS bam (~2GB, from blood biopsy) for quicker debugging turnaround time, and am successfully getting 16 shards and cores to run when GCP has the appropriate machine type available, here is output of lscpu:

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:              0
CPU MHz:               2300.000
BogoMIPS:              4600.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-15
```

I then get 16 messages like this:
`
Common contigs are [u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'X', u'Y']`

Then the candidate site lines begin printing out. 

How much memory per shard/core/worker (assuming one worker per shard and core if I'm not mistaken) is recommended?

**Comment by ekofman** [comment]
Aha. I think it was a RAM issue. Once I upped the RAM to 60 GB it works and starts outputing stdouts per each shard. Wasn't working with 16GB or below. Good to know -- play with RAM if you encounter the same issue.

**Comment by pichuan** [comment]
Thanks @ekofman for the update. Good to know that it was resolved.

In terms of whether bigger BAM files affect the run time -- overall it would increase the run time, since we'll be dealing with more reads per region on average, which will be more expensive to realign, build pileup image, etc.
But in make_examples, we sample subset of reads before performing these expensive operations. (We try to minimize the effect on accuracy if any). So it shouldn't be too bad.
Empirically, we do still sometimes see more expensive regions. It'll be great to identify a few regions like this on any public BAM we can get, so we can understand it better and improve.
