### ISSUE TITLE
How to run/call call_variants when make_examples produces sharded outputs

### ISSUE THREAD

**Issue by ekofman** [google/deepvariant#151]
Hi, I've gotten a test run successfully through the make_example step with 64 shards, and have produced 64 examples and gvcf files like so:
```
-rw-r--r-- 1 root root   14394035 Feb  6 18:18 test.examples.tfrecord-00000-of-00064.gz
-rw-r--r-- 1 root root   16089657 Feb  6 18:18 test.examples.tfrecord-00001-of-00064.gz
-rw-r--r-- 1 root root   14238866 Feb  6 18:18 test.examples.tfrecord-00002-of-00064.gz
-rw-r--r-- 1 root root   14484530 Feb  6 18:19 test.examples.tfrecord-00003-of-00064.gz
...
-rw-r--r-- 1 root root   15225527 Feb  6 18:18 test.examples.tfrecord-00056-of-00064.gz
-rw-r--r-- 1 root root   14663343 Feb  6 18:19 test.examples.tfrecord-00057-of-00064.gz
-rw-r--r-- 1 root root   14571664 Feb  6 18:19 test.examples.tfrecord-00058-of-00064.gz
-rw-r--r-- 1 root root   13704439 Feb  6 18:19 test.examples.tfrecord-00059-of-00064.gz
-rw-r--r-- 1 root root   14383355 Feb  6 18:18 test.examples.tfrecord-00060-of-00064.gz
-rw-r--r-- 1 root root   13559255 Feb  6 18:19 test.examples.tfrecord-00061-of-00064.gz
-rw-r--r-- 1 root root   16376740 Feb  6 18:19 test.examples.tfrecord-00062-of-00064.gz
-rw-r--r-- 1 root root   15276769 Feb  6 18:18 test.examples.tfrecord-00063-of-00064.gz
-rw-r--r-- 1 root root    5842718 Feb  6 18:18 test.gvcf.tfrecord-00000-of-00064.gz
-rw-r--r-- 1 root root    5860574 Feb  6 18:18 test.gvcf.tfrecord-00001-of-00064.gz
-rw-r--r-- 1 root root    5852289 Feb  6 18:18 test.gvcf.tfrecord-00002-of-00064.gz
-rw-r--r-- 1 root root    5845856 Feb  6 18:19 test.gvcf.tfrecord-00003-of-00064.gz
-rw-r--r-- 1 root root    5834861 Feb  6 18:18 test.gvcf.tfrecord-00004-of-00064.gz
-rw-r--r-- 1 root root    5812744 Feb  6 18:18 test.gvcf.tfrecord-00005-of-00064.gz
-rw-r--r-- 1 root root    5856643 Feb  6 18:19 test.gvcf.tfrecord-00006-of-00064.gz
...
-rw-r--r-- 1 root root    5893279 Feb  6 18:19 test.gvcf.tfrecord-00054-of-00064.gz
-rw-r--r-- 1 root root    5850799 Feb  6 18:19 test.gvcf.tfrecord-00055-of-00064.gz
-rw-r--r-- 1 root root    5844041 Feb  6 18:18 test.gvcf.tfrecord-00056-of-00064.gz
-rw-r--r-- 1 root root    5816735 Feb  6 18:19 test.gvcf.tfrecord-00057-of-00064.gz
-rw-r--r-- 1 root root    5852875 Feb  6 18:19 test.gvcf.tfrecord-00058-of-00064.gz
-rw-r--r-- 1 root root    5820441 Feb  6 18:19 test.gvcf.tfrecord-00059-of-00064.gz
-rw-r--r-- 1 root root    5797526 Feb  6 18:18 test.gvcf.tfrecord-00060-of-00064.gz
-rw-r--r-- 1 root root    5893496 Feb  6 18:19 test.gvcf.tfrecord-00061-of-00064.gz
-rw-r--r-- 1 root root    5818504 Feb  6 18:19 test.gvcf.tfrecord-00062-of-00064.gz
-rw-r--r-- 1 root root    5831798 Feb  6 18:18 test.gvcf.tfrecord-00063-of-00064.gz

```

Surprisingly, this was generated using the following command:

```
 ## Run `make_examples`
    echo "Start running make_examples...Log will be in the terminal and also to make_examples.log."
    ( time seq 0 $((${numShards}-1)) | \
      parallel -k --line-buffer \
          /opt/deepvariant/bin/make_examples \
          --mode calling \
          --ref ${Fasta} \
          --reads reads.bam \
          --examples "${sample_id}.examples.tfrecord@${numShards}.gz" \
          --gvcf "${sample_id}.gvcf.tfrecord@${numShards}.gz" \
          --task {} \
    ) 2>&1 | tee "make_examples.log"
    echo "Done."
    echo
```

Which was based on this example: https://github.com/google/deepvariant/blob/r0.7/scripts/run_wgs_case_study_docker.sh

I would have expected the naming scheme to match the pattern I specified instead of the 000*-of-00064... strange.

Now I am trying to move on to the next step, but again having trouble figuring out how to deal with these multiple example files /sharding when passing them as inputs to the call_variants step. 

In the example, it recommends:

```
## Run `call_variants`
echo "Start running call_variants...Log will be in the terminal and also to ${LOG_DIR}/call_variants.log."
( time sudo docker run \
    -v "${BASE}":"${BASE}" \
    gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
    /opt/deepvariant/bin/call_variants \
    --outfile "${CALL_VARIANTS_OUTPUT}" \
    --examples "${EXAMPLES}" \
    --checkpoint "${MODEL}"
) 2>&1 | tee "${LOG_DIR}/call_variants.log"
echo "Done."
echo
```

Is there some magic pattern recognition that knows to look for files of the format 000*-of-00064? Confused as to how I should do this; should I run call_variants on 64 separate machines, with each machine running a job on one of the sharded make_examples outputs? When I try incorporating the code recommended in the example workflow, I get the following error:

`ValueError: Cannot find matching files with the pattern "test.examples.tfrecord@64.gz"`

So obviously not working out of the box as specified. But I'm not sure whether call_variants is intelligent to handle sharded examples or if I should be explicitly only running it once on each shard and then somehow merging all the vcfs after or something. And where in this shading would post processing of variants fit in to generate the VCF -- can that be part of a reduce step pulling all sharded call_variants outputs together one one machine? Any recommendations @pichuan @akolesnikov ?

**Comment by ekofman** [comment]
I feel like I'm so close... going ahead with the option of running one call_variants per machine per shard and then trying to gather all results before postprocessing. Not sure if that is correct, however, assuming that it is, I'm still now running into this:

I0206 23:26:03.790093 139996085663488 call_variants.py:328] Initializing model from DeepVariant-inception_v3-0.6.0+cl-191676894.data-wgs_standard/model.ckpt.data-00000-of-00001
2019-02-06 23:26:03.791839: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open DeepVariant-inception_v3-0.6.0+cl-191676894.data-wgs_standard/model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

I'm using the wgs model found at deepvariant/models/DeepVariant/0.6.0/DeepVariant-inception_v3-0.6.0+cl-191676894.data-wgs_standard/, called model.ckpt.data-00000-of-00001 .... should I be referencing the full name or just moel.ckpt.data as suggested here https://github.com/tensorflow/models/issues/2676 ?

**Comment by pgrosu** [comment]
Sort of close...why are you using a 0.6.0 model with a 0.7.2 codebase?  It's better to be consistent.  Here's the location of the 0.7.2 wgs models:

```Bash
$ gsutil ls -l gs://deepvariant/models/DeepVariant/0.7.2/DeepVariant-inception_v3-0.7.2+data-wgs_standard/
 348681272  2018-12-11T23:39:18Z  gs://deepvariant/models/DeepVariant/0.7.2/DeepVariant-inception_v3-0.7.2+data-wgs_standard/model.ckpt.data-00000-of-00001
     18496  2018-12-11T23:39:42Z  gs://deepvariant/models/DeepVariant/0.7.2/DeepVariant-inception_v3-0.7.2+data-wgs_standard/model.ckpt.index
  31106596  2018-12-11T23:39:45Z  gs://deepvariant/models/DeepVariant/0.7.2/DeepVariant-inception_v3-0.7.2+data-wgs_standard/model.ckpt.meta
TOTAL: 3 objects, 379806364 bytes (362.21 MiB)
$
```
~p

**Comment by nmousavi** [comment]
Can you verify TF examples (test.gvcf.tfrecord-*) are in ${BASE} path?

If you use DeepVariant's cloud runner, you won't need to do all these steps manually. It takes care of everything and runs the pipeline on GCP. See instruction here:

https://cloud.google.com/genomics/docs/tutorials/deepvariant

Is there any reason why you don't use cloud runner?

**Comment by ekofman** [comment]
Thanks for the help. So call variants only needs to be called once on all the shards at once, running on one GPU? Not individually once per shard? And under the hood it’s designed to recognize the tfrecord naming and numbering scheme as is described in the example wgs sh script? Given that the format is 000*-of-00064 do I have to specify this or does call variants assume that format and know how to find the 64 shards if they’re in the working directory? There’s a lot of regex going on I’d love to see documented (I guess maybe it’s in the codebase but if it could be explicitly written on the documentation that’d be awesome)  — I understand that there is this cloud runner but considering these other components are exposed I feel like I don’t have a good sense of the way they should be appropriately called individually. 

I’m hoping to set up a version of this in FireCloud using WDL as all of our workflows are currently set up in this way. It seems like I’m almost there — if I can’t figure it out then yes I will perhaps have to use the cloud runner.

**Comment by ekofman** [comment]
Oh I thought I was using a consistent model and codebase — thanks for the links.

**Comment by pichuan** [comment]
Hi @ekofman ,

a few things:

(1) The `@64` format correspond to `000??-of-00064`. So, in  your case, it is expected that `--examples "${sample_id}.examples.tfrecord@${numShards}.gz"` in the `make_examples` step generated 
`test.examples.tfrecord-000??-of-00064.gz` (shards from 00 to 63).

(2) From the command you pasted, it seems like you're directly running inside docker.
If that is the case, you don't need the [-v flags](https://docs.docker.com/storage/volumes/), but you still need to make sure that the files are actually visible when/where you run call_variants.
If you're still running call_variants inside docker (like you did for your make_examples step), please make sure when you can see `test.examples.tfrecord-000??-of-00064.gz` from where you run the command. So, `ls test.examples.tfrecord-000??-of-00064.gz` should see the files.

The command you pasted from our run_wgs_case_study_docker.sh example is actually different from the make_examples command you posted first. If you're using that, you need to make sure you're using the [-v flags](https://docs.docker.com/storage/volumes/) correctly and make sure the files are visible to it.

(3) I tested with `sudo docker run -it gcr.io/deepvariant-docker/deepvariant:0.7.2` first and directly running the commands inside. I modified from the WES example because it's faster, but WGS should be the same. I can confirm that I was able to run the following steps without any issues:

1. Start interactive mode so I can use command similar to yours. I'm not considering how I'm getting the data out.
```
sudo docker run -it gcr.io/deepvariant-docker/deepvariant:0.7.2
```

2. Inside the interactive mode, run the following:
```
MODEL_HTTP_DIR="https://storage.googleapis.com/deepvariant/models/DeepVariant/0.7.2/DeepVariant-inception_v3-0.7.2+data-wes_standard"
DATA_HTTP_DIR=https://storage.googleapis.com/deepvariant/exome-case-study-testdata
N_SHARDS="64"

## Download extra packages
sudo apt-get -y update
sudo apt-get -y install parallel
sudo apt-get -y install aria2
## Download models, and test data
# Copy the model files to your local disk.
aria2c -c -x10 -s10 "${MODEL_HTTP_DIR}"/model.ckpt.data-00000-of-00001
aria2c -c -x10 -s10 "${MODEL_HTTP_DIR}"/model.ckpt.index
aria2c -c -x10 -s10 "${MODEL_HTTP_DIR}"/model.ckpt.meta

# Copy the data
aria2c -c -x10 -s10 ${DATA_HTTP_DIR}/151002_7001448_0359_AC7F6GANXX_Sample_HG002-EEogPU_v02-KIT-Av5_AGATGTAC_L008.posiSrt.markDup.bai
aria2c -c -x10 -s10 ${DATA_HTTP_DIR}/151002_7001448_0359_AC7F6GANXX_Sample_HG002-EEogPU_v02-KIT-Av5_AGATGTAC_L008.posiSrt.markDup.bam
aria2c -c -x10 -s10 ${DATA_HTTP_DIR}/agilent_sureselect_human_all_exon_v5_b37_targets.bed
aria2c -c -x10 -s10  ${DATA_HTTP_DIR}/hs37d5.fa.gz
aria2c -c -x10 -s10 ${DATA_HTTP_DIR}/hs37d5.fa.gz.fai
aria2c -c -x10 -s10 ${DATA_HTTP_DIR}/hs37d5.fa.gz.gzi
aria2c -c -x10 -s10 ${DATA_HTTP_DIR}/hs37d5.fa.gzi
```

Then, I ran `make_examples` similar to the way you did in your original post:
```
## Run `make_examples`
( time seq 0 $((N_SHARDS-1)) | \
  parallel -k --line-buffer \
      /opt/deepvariant/bin/make_examples \
      --mode calling \
      --ref "hs37d5.fa.gz" \
      --reads "151002_7001448_0359_AC7F6GANXX_Sample_HG002-EEogPU_v02-KIT-Av5_AGATGTAC_L008.posiSrt.markDup.bam" \
      --examples "HG002.examples.tfrecord@${N_SHARDS}.gz" \
      --regions "agilent_sureselect_human_all_exon_v5_b37_targets.bed" \
      --gvcf "HG002.gvcf.tfrecord@${N_SHARDS}.gz" \
      --task {} \
) 2>&1 | tee "make_examples.log"
```
This took on 13m33.192s a 64-core, 128GB RAM machine.

Before I proceeded with call_variants, I first checked that the output files from make_examples exist:
```
ls HG002.examples.tfrecord*.gz | wc -l
```
I see 64 of them here.
A common issue is that if the make_examples step failed but you didn't notice, then the next step will fail.
Common failure modes I've seen before:
 - if you were running make_examples, but abort in the middle by ctrl-c. Sometimes not all the make_examples in the background were killed. If you just re-run make_examples without killing all background make_examples first, the output might be corrupted.
 - if make_examples failed completely without outputting HG002.examples.tfrecord*.gz at all, it'll also cause a failure. Our hope is that you'll notice this in the errors that make_examples displayed. If you're creating some kind of workflow yourself, you will need to make sure you check the error code of the runs. If make_examples died, you shouldn't proceed with call_variants.

After my make_examples run and confirming that I have the output files, I ran call_variants:
```
## Run `call_variants`
( time \
    /opt/deepvariant/bin/call_variants \
    --outfile "HG002.cvo.tfrecord.gz" \
    --examples "HG002.examples.tfrecord@${N_SHARDS}.gz" \
    --checkpoint "model.ckpt" \
) 2>&1 | tee "call_variants.log" &
```
When I run this on the same 64-core, 128GB RAM machine, it usually only uses about 500% CPU (instead of all of the 64 cores). This step took about 2m.

I can confirm that I successfully run this step without the errors you saw.

However, if I remove the files first by `rm -f HG002.examples.tfrecord*.gz` and then repeat the call_variants command above, I can see the errors you reported above:
```
ValueError: Cannot find matching files with the pattern "HG002.examples.tfrecord@64.gz"
```

So, please make sure you that your make_examples step completed successfully before you proceed.

(4) As you noticed so far, creating a workflow can be complicated (and mostly has nothing to do with variant caller itself). If you end up trying out the Cloud runner and has more questions, please feel free to get in touch with @nmousavi and the Cloud team. I'm sure the team will love to get your feedback if you decide to try it out. Thank you!

**Comment by ekofman** [comment]
@pichuan Thank for such a thorough description, really appreciate it. Super helpful to understand the different expectations and possible failure modes of each step. I will go back and make sure all of the preconditions you mentioned are met. One last comment though -- you didn't run call_variants on a GPU though it seems that is recommended; just makes it faster or is there any other reason to?

**Comment by pichuan** [comment]
@ekofman Currently, the case studies (and corresponding scripts) are used to show an example of how to run DeepVariant. We showed an example of how to run it on a single machine, and didn't focus on many other aspects such as how to pull multiple workers to orchestrate a distributed workflow, or how to run with GPU (which involves installing GPU driver, using the binaries that are built for GPU, etc).
If you want to run on GPU, and if you have everything set up already (such as installing GPU driver correctly), you should be able to do it pretty much the same way. But instead of `sudo docker pull gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}"`, you'll pull from gcr.io/deepvariant-docker/**deepvariant_gpu** which is built for GPU.
We have also documented it here:
https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-details.md#call_variants in case you need to build the binaries yourself.

Note that even though using GPUs is faster, the overall cost might not be better depending on many other factors. Again, you can look at the [GCP Cloud runner](https://cloud.google.com/genomics/docs/tutorials/deepvariant) as an example of how they configure their run.
If you end up doing more experiments to compare different configurations in your workflow, we would love to learn more about it as well. In addition to the [GCP Cloud runner](https://cloud.google.com/genomics/docs/tutorials/deepvariant) that @nmousavi 's team maintains, we also have seen other examples such as https://github.com/atgenomix/deepvariant-on-spark (and their [WGS case study](https://github.com/atgenomix/deepvariant-on-spark/blob/master/docs/wgs-case-study.md) reports run time as well).

In terms of how much details we include on the DeepVariant GitHub page --
Even though I'm personally very interested in the performance and cost of these implementations, I also need to consider the trade-off of the amount of details we include, because too much information can also end up being confusing. If you have more suggestions on how to organize the documentation better in the future, please let me know. Even now it's already a bit messy and I would like to simplify it further. Thanks!
