### ISSUE TITLE
Nvidia RTX 2070 with Tensor cores

### ISSUE THREAD

**Issue by kokyriakidis** [google/deepvariant#157]
Hello, I am a pharmacy student and I am trying to use your tool. 
I have in my possession a pc with i7-6700, 32GB RAM and a RTX 2070 with CUDA cores and Tensor Cores.
1) Can I somehow use the Tensor cores of my GPU and how?
2) Is 32 GB enough? If I upgrade to 64gb will be better?

**Comment by pgrosu** [comment]
It all depends on how big your data is.

**Comment by kokyriakidis** [comment]
Lets say I want to do an analysis on a 9gb WES bam file. Will 32gb be enough?

**Comment by pgrosu** [comment]
Yes, but take a look at this:

https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-details.md

It just depends on how many coffee breaks you want to have :)

~p

**Comment by kokyriakidis** [comment]
So the question is, is it worth to buy another 32gb ram (64 total)? Will I see much improvement?

**Comment by pgrosu** [comment]
I would begin by performing an empirical serial study first with your current configuration, starting with the bare minimum amount of memory, and increasing it with some consistency.  Then based on that, project out what would be satisfactory - if the current setup is not sufficient.

**Comment by kokyriakidis** [comment]
Currently, I have a mini motherboard with two RAM slots (32gb), so I cannot upgrade it. I am looking to buy maybe a quad channel motherboard. I was looking at AMDs Threadrippers due to their cores. Will I have a usage penalty using AMD instead of INTEL based cpus due to the MLK library?

**Comment by pichuan** [comment]
Hi @kokyriakidis 
MKL is an important part of the speed improvement for the `call_variants` step in the v0.7 release.
We don't currently have tried on AMD, so I can't say what the performance will be like. I'd like to learn more if you try it and have some numbers to share. 

In general it's pretty difficult for the DeepVariant team to give advice on hardware or fine-tuning for a specific configuration. I usually think of that as an open-ended research problem itself, because many factors could come into play. I think @pgrosu 's advice above is the best. Start documenting numbers with your current configuration, continue with various hypotheses ("can I use less RAM?", "am I building with the optimized flags for my setting?", etc) and trying them out. Continue to document the numbers and see if your hypotheses got proved or disproved. If you have any observations that are different from the statement we made in our GitHub documentations, we'd really appreciate you let us know.

Your original question (in the title) is interesting - I only recently heard about Tensor Cores. We've mostly rely on TensorFlow (which DeepVariant used in the `call_variants` step) to interface with various hardware (CPU/GPU/TPU) below. But as you noticed that there are still things users/developers need to know at the level of DeepVariant, such as making sure we use MKL-enabled TensorFlow version, etc. Regarding Tensor Cores, I don't know enough to answer your question yet. But I'll ask around and reply back when I hear more.

For now, I'll close this issue because I think @pgrosu and I have provided enough meta-information as we can. Feel free to open another issue if you have more questions.
