### ISSUE TITLE
Failed to open BAM file in deepvariant-tpu-training-case-study

### ISSUE THREAD

**Issue by YAaNnGg** [google/deepvariant#184]
Hi, I got an error when running 
`( time seq 0 $((N_SHARDS-1)) | \
  parallel --halt 2 --joblog "${LOG_DIR}/log" --res "${LOG_DIR}" \
    sudo docker run \
      -v /home/${USER}:/home/${USER} \
      gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
      /opt/deepvariant/bin/make_examples \
      --mode training \
      --ref "${REF}" \
      --reads "${BAM}" \
      --examples "${OUTPUT_DIR}/validation_set.with_label.tfrecord@${N_SHARDS}.gz" \
      --truth_variants "${TRUTH_VCF}" \
      --confident_regions "${TRUTH_BED}" \
      --task {} \
      --regions "'chr21 chr22'" \
) >"${LOG_DIR}/validation_set.with_label.make_examples.log" 2>&1`

the log message in validation_set.with_label.make_examples.log is as below:

`[E::hts_open_format] Failed to open file /home/chenyangwang600/training-case-study/input/data/BGISEQ_PE100_NA12878.sorted.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_rBHpvo/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1235, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_rBHpvo/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1186, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_rBHpvo/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 315, in default_options
    with sam.SamReader(flags_obj.reads) as sam_reader:
  File "/tmp/Bazel.runfiles_rBHpvo/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 216, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_rBHpvo/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_rBHpvo/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /home/chenyangwang600/training-case-study/input/data/BGISEQ_PE100_NA12878.sorted.bam
parallel: This job failed:
sudo docker run -v /home/root:/home/root gcr.io/deepvariant-docker/deepvariant:0.8.0 /opt/deepvariant/bin/make_examples --mode training --ref /home/chenyangwang600/training-case-study/input/data/ucsc_hg19.fa --reads /home/chenyangwang600/training-case-study/input/data/BGISEQ_PE100_NA12878.sorted.bam --examples /home/chenyangwang600/training-case-study/output/validation_set.with_label.tfrecord@8.gz --truth_variants /home/chenyangwang600/training-case-study/input/data/HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer_chrs_FIXED.vcf.gz --confident_regions /home/chenyangwang600/training-case-study/input/data/HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_chr.bed --task 1 --regions 'chr21 chr22'

real    0m4.444s
user    0m0.318s
sys     0m0.216s`

I thought I followed the instructions in the guide(Advanced Case Study: Train a customized SNP and small indel variant caller for BGISEQ-500 data) except that I used a 8vCPUs with 
`gcloud beta compute instances create "cpu-eight"  \
  --scopes "compute-rw,storage-full,cloud-platform" \
  --image-family "ubuntu-1604-lts" \
  --image-project "ubuntu-os-cloud" \
  --machine-type "n1-standard-8" \
  --boot-disk-size "300" \
  --zone "us-west1-b" \
  --min-cpu-platform "Intel Skylake"`

and set variables
N_SHARDS="8"

I tried to use another VM but also failed. How can I solve this issue?

Thanks,
Yang

**Comment by YAaNnGg** [comment]
I think I know what's happening. The `${USER}` was `/root` when running docker. It was maybe caused by a `sudo bash`? When I changed it, everything seems OK. Similar Error #141 .

**Comment by pgrosu** [comment]
Hi @charlesfeigin,

The issue was that he was running as `root` and mapping `/home/${USER}`, which does not exist as `root` has a home directory of `/root` usually (not `/home/root`).  Also Docker containers launch as `root`, meaning they have their own `/root`.  It's best not to run as root.  If you have to, just make sure your files are located other than under `/root`, and you map them from that other directory instead.  Where were your files located before?

Thanks,
~p

**Comment by charlesfeigin** [comment]
Thank you so much for your assistance Paul. Answered slightly out of order:

2. The location from which the commands were run is /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/. Inside this directory are two subdirectories: inputs (in which the assembly and bam files are) and outputs (in which the results go).

1. The commands run were:

BIN_VERSION="1.5.0"
docker pull google/deepvariant:"${BIN_VERSION}"

INPUT_DIR="${PWD}/inputs"
OUTPUT_DIR="${PWD}/outputs"

docker run -v "${INPUT_DIR}":"/input" -v "${OUTPUT_DIR}":"/output" google/deepvariant:"${BIN_VERSION}" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/input/GCF_902635505.1_mSarHar1.11_genomic_baicompat.fa --reads=/input/NC_045426.1_A_filt_fixed_markdup_csort.bam --output_vcf=/output/NC_045426.1_A.vcf.gz --output_gvcf=/output/NC_045426.1_A.g.vcf.gz --intermediate_results_dir /output/NC_045426.1_A_intermediate_results_dir --num_shards=1 &

3. The complete output of errors is:

2023-08-30 21:45:18.422516: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0830 21:45:20.409601 140002879141696 run_deepvariant.py:364] Re-using the directory for intermediate results in /output/NC_045426.1_A_intermediate_results_dir

***** Intermediate results will be written to /output/NC_045426.1_A_intermediate_results_dir in docker. ****


***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/GCF_902635505.1_mSarHar1.11_genomic_baicompat.fa" --reads "/input/NC_045426.1_A_filt_fixed_markdup_csort.bam" --examples "/output/NC_045426.1_A_intermediate_results_dir/make_examples.tfrecord@1.gz" --channels "insert_size" --gvcf "/output/NC_045426.1_A_intermediate_results_dir/gvcf.tfrecord@1.gz" --task {}

2023-08-30 21:45:21.348267: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[E::hts_open_format] Failed to open file "/input/NC_045426.1_A_filt_fixed_markdup_csort.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 196, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 182, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 133, in default_options
    samples_in_order, sample_role_to_train = one_sample_from_flags(
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 88, in one_sample_from_flags
    sample_name = make_examples_core.assign_sample_name(
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 147, in assign_sample_name
    with sam.SamReader(reads_filenames.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 260, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_34o2lccw/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 227, in __init__
    self._reader = sam_reader.SamReader.from_file(
ValueError: NOT_FOUND: Could not open /input/NC_045426.1_A_filt_fixed_markdup_csort.bam
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/GCF_902635505.1_mSarHar1.11_genomic_baicompat.fa --reads /input/NC_045426.1_A_filt_fixed_markdup_csort.bam --examples /output/NC_045426.1_A_intermediate_results_dir/make_examples.tfrecord@1.gz --channels insert_size --gvcf /output/NC_045426.1_A_intermediate_results_dir/gvcf.tfrecord@1.gz --task 0

real    0m3.279s
user    0m3.908s
sys     0m6.234s

**Comment by pgrosu** [comment]
Hi Charles,

Great!  So if you run the following steps, what do you see (I know some are obvious, but it's just a sanity check):

$`1)`$ The following will test that your file is at the correct location:

```
ls -l /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs 

ls -l /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs | grep NC_045426.1_A_filt_fixed_markdup_csort.bam
```

$`2)`$ The following will test that your `INPUT_DIR` environment variable works properly:

``` 
INPUT_DIR="${PWD}/inputs" 

echo ${PWD}

ls -l ${INPUT_DIR}

ls -l ${INPUT_DIR} | grep NC_045426.1_A_filt_fixed_markdup_csort.bam
```

$`3)`$ The following will test that your `INPUT_DIR` environment variable works properly inside Docker:

```
INPUT_DIR="${PWD}/inputs" 
BIN_VERSION="1.5.0"

echo ${PWD}

sudo docker run -v "${INPUT_DIR}":"/input" google/deepvariant:"${BIN_VERSION}" ls -l /input

sudo docker run -v "${INPUT_DIR}":"/input" google/deepvariant:"${BIN_VERSION}" ls -l /input | grep NC_045426.1_A_filt_fixed_markdup_csort.bam
```

You should see the file `NC_045426.1_A_filt_fixed_markdup_csort.bam` for all 3 steps.  Please list for which step you don't see that file, and what you actually see for that step (in terms of the complete output of the step).

Of course the other way to explicitly name the input and output variables, by changing them to the following (and not relying on `${PWD}` - the present working directory - which could change):

```
INPUT_DIR="/tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs"

OUTPUT_DIR="/tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/outputs"

```
Thanks,
Paul

**Comment by charlesfeigin** [comment]
Thanks again Paul:

1)

ls -l /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs 
-rw-rw-r-- 1 ajp1 ajp1 3138120789 Aug 31 12:12 GCF_902635505.1_mSarHar1.11_genomic_baicompat.fa
-rw-rw-r-- 1 ajp1 ajp1 3133881452 Aug 31 12:12 NC_045426.1_A_filt_fixed_markdup_csort.bam

ls -l /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs | grep NC_045426.1_A_filt_fixed_markdup_csort.bam
-rw-rw-r-- 1 ajp1 ajp1 3133881452 Aug 31 12:12 NC_045426.1_A_filt_fixed_markdup_csort.bam

2) 

INPUT_DIR="${PWD}/inputs" 
echo ${PWD}
/tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling


ls -l ${INPUT_DIR}
total 6125004
-rw-rw-r-- 1 ajp1 ajp1 3138120789 Aug 31 12:12 GCF_902635505.1_mSarHar1.11_genomic_baicompat.fa
-rw-rw-r-- 1 ajp1 ajp1 3133881452 Aug 31 12:12 NC_045426.1_A_filt_fixed_markdup_csort.bam

ls -l ${INPUT_DIR} | grep NC_045426.1_A_filt_fixed_markdup_csort.bam
-rw-rw-r-- 1 ajp1 ajp1 3133881452 Aug 31 12:12 NC_045426.1_A_filt_fixed_markdup_csort.bam


3) 

INPUT_DIR="${PWD}/inputs" 
BIN_VERSION="1.5.0"
echo ${PWD}
/tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs

Note: ajp1 is in the docker user group, but does not have sudo permissions. they did not need sudo to run deepvariant on their earlier runs though and it worked just fine...

Nonetheless, running without sudo gives the following:

docker run -v "${INPUT_DIR}":"/input" google/deepvariant:"${BIN_VERSION}" ls -l /input
total 0 

docker run -v "${INPUT_DIR}":"/input" google/deepvariant:"${BIN_VERSION}" ls -l /input | grep NC_045426.1_A_filt_fixed_markdup_csort.bam
(this gave no outputs at all)

Lastly, I tried specifying the directories as you did above:

INPUT_DIR="/tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs"


And I still had no output at all when running:

docker run -v "${INPUT_DIR}":"/input" google/deepvariant:"${BIN_VERSION}" ls -l /input | grep NC_045426.1_A_filt_fixed_markdup_csort.bam

**Comment by pgrosu** [comment]
Hi Charles,

Usually `mount` (`-v`) require specialized access that the administrator can provide. 
 Maybe you can show them our tests that worked for you previously.  In any case, here are a few more tests:

$`1)`$ The first is to use the `mount` command explicitly:

```
docker run \
  --mount type=bind,source="/tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs",target="/input" \
  google/deepvariant:"1.5.0" ls -l /input
```

$`2)`$ This is using volumes, which is a different approach:

```
docker volume create --name dv-vol

docker run \
  --mount source=dv-vol,target="/input" \
  google/deepvariant:"latest" touch /input/a-new-file

docker run \
  --mount source=dv-vol,target="/input" \
  google/deepvariant:"latest" ls -l /input

docker container create --name dv-cp-cont -v dv-vol:/input-path-cont hello-world

docker cp dv-cp-cont:/input-path-cont .

ls input-path-cont

touch input-path-cont/file-2

docker cp input-path-cont/file-2 dv-cp-cont:/input-path-cont 

docker run \
  --mount source=dv-vol,target="/input" \
  google/deepvariant:"latest" ls -l /input

docker rmi --force hello-world:latest

docker volume rm dv-vol
```

Let me know the results of both.

Thanks,
Paul

**Comment by charlesfeigin** [comment]
Hi Paul,

Thank you again for your replies and sorry mine are so slow (I think we are in very different time zones).

So I’m administering this system but am not really a system administrator (I’m a biologist). Since I have root access, if there is something that can be done (or undone) to re-establish the ability of non-root users to run deepvariant, I can do that, I just don’t know enough to fix this specific issue myself.

1) The following gives me 
docker run --mount type=bind,source="/tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs",target="/input" google/deepvariant:"1.5.0" ls -l /input

docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling.
See 'docker run --help'.


2) I’ve run the following, but confess I don’t understand what is going on past the second command and then deleting what was done at the end. If creating volumes can be skirted by changing some admin permission that is doable on my end.

docker volume create --name dv-vol
dv-vol

docker run --mount source=dv-vol,target="/input" google/deepvariant:"1.5.0" touch /input/a-new-file

docker run --mount source=dv-vol,target="/input" google/deepvariant:"1.5.0" ls -l /input
total 0
-rw-r--r-- 1 root root 0 Sep  1 00:21 a-new-file

docker container create --name dv-cp-cont -v dv-vol:/input-path-cont hello-world
4d2015a9c2dbe3fc6d27854c440ce8505222ed6a8f2a3c945d36315081a832b6

docker cp dv-cp-cont:/input-path-cont .

ls input-path-cont

a-new-file
touch input-path-cont/file-2

-rw-r--r-- 1 root root 0 Sep  1 00:21 a-new-file
-rw-rw-r-- 1 1005 1010 0 Sep  1 00:26 file-2

docker cp input-path-cont/file-2 dv-cp-cont:/input-path-cont 

docker run --mount source=dv-vol,target="/input" google/deepvariant:"1.5.0" ls -l /input
total 0
-rw-r--r-- 1 root root 0 Sep  1 00:21 a-new-file
-rw-rw-r-- 1 1005 1010 0 Sep  1 00:26 file-2


docker rmi --force hello-world:latest

Untagged: hello-world:latest
Untagged: hello-world@sha256:dcba6daec718f547568c562956fa47e1b03673dd010fe6ee58ca806767031d1c
Deleted: sha256:9c7a54a9a43cca047013b82af109fe963fde787f63f9e016fdc3384500c2823d

# This gave the error you indicated, and the fix worked as well
docker volume rm dv-vol

Best,
Charles

**Comment by pgrosu** [comment]
Hi Charles,

You are right, we are probably in different time zones.  I am on the East Coast of the United States.

Thank you for being so patient and going through the commands, as each provides new information telling us how to proceed forward.  So the good thing is that now we know volumes would work, but you are right they can be cumbersome to use under some circumstances.  

So let's try the `mount` approach.  The reason we used `--mount` instead of `-v` is because it is more granular, telling us specifically which directory it is having an issue with.  In this case it is getting stuck on the `variant_calling` directory, and somehow Docker is not able to recognize it.  So let's try to determine what type of directory, and what permissions it has (including above and below it).

$`1)`$ So if you could please type the following commands, then we can inspect the output to determine what might be the issue:

```
stat /tiger/home/ajp1/analysis/demography/tasmanian_devil

stat /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling

stat /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling/inputs

ls -l /tiger/home/ajp1/analysis/demography | grep tasmanian_devil

ls -l /tiger/home/ajp1/analysis/demography/tasmanian_devil/ | grep variant_calling

ls -l /tiger/home/ajp1/analysis/demography/tasmanian_devil/variant_calling | grep inputs
```

$`2)`$ Now I have some minor questions about your system and Docker, in order to determine if there could be other underlying causes.  For the following questions, it's okay if you don't remember everything:  

* What operating system and version are your running?  
* How long ago did you install Docker?
* What commands did you use to install Docker?  
* What version of Docker are you running?  (The command is in the commands below.)

You previously mention that `ajp1` is part of the docker group, so we can use that as guidance when we inspect the output from the commands above.

Below is a set of commands if you could please run, to answer some of the questions above (except for the installation ones).  For Linux usually the commands are as follows (some will provide you information, as I included them for multiple operating systems):

```
uname -a

cat /etc/lsb-release

cat /etc/redhat-release

cat /etc/os-release

docker --version
```

Thank you,
Paul
