### ISSUE TITLE
postprocess_variants fails when output is empty

### ISSUE THREAD

**Issue by arostamianfar** [google/deepvariant#186]
`postprocess_variants` fails (stack trace below) when the final VCF output is empty. There are use cases where this is expected (e.g. `regions` is small enough to not contain any variants for a subset of samples).

Expected outcome is to generate an empty VCF file with just the headers. Note that `make_examples` and `call_variants` correctly handle the empty case, so just `postprocess_variants` needs to change.

```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_NZTcBp/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 955, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_NZTcBp/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 897, in main
    raise ValueError('Cannot find any records in {}'.format(','.join(paths)))
ValueError: Cannot find any records in /tmp/deepvariant_tmp_output/call_variants_output.tfrecord.gz
```

**Comment by gunjanbaid** [comment]
Hi @arostamianfar, thanks for reporting this issue. We plan to push out a fix for this problem in a future release.

**Comment by JoshuaUrrutia** [comment]
Has this been patched yet?

**Comment by pichuan** [comment]
Hi @JoshuaUrrutia , thanks for checking back.
The issue has been fixed in this change:
https://github.com/google/deepvariant/commit/7ed8c6bbcfb2dc0da9b1011ba21d12791239de79

If you're using the latest version (v0.10.0), we don't expect you to see this error before. If you still observe some issues with this, please let us know by reopening this issue or filing a new one.
