### ISSUE TITLE
chrY variants on Females

### ISSUE THREAD

**Issue by kokyriakidis** [google/deepvariant#196]
When I run the pipeline on females I get lots of PASSED variants on chrY. Why is that?

**Comment by AndrewCarroll** [comment]
Hi @kokyriakidis

Thank you for your question. There are a few possibilities for this. First, chrX and chrY do share regions of homology, the pseudo autosomal regions (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2435358/), which allows them to pair and segregate appropriately during meiosis.

Because the reference sequence for both chrX and chrY contains these sequences, even in a female individual, reads will map to either and this can manifest as HET calls. It could be good to look at whether these calls occur in PAR regions. This will depend on which reference you are using, as some references mask this region. Can you tell us the reference build that you are using?

Second, reads may end up mismapped onto chrY from autosomes. When mismapping occurs, there is signal that will look like variation. The variant callers are not told whether a sample is male or female, and have to judge whether the signal is consistent with a variant or if the sample is female. Errors in this process can occur. How many variants are you seeing as PASS, it could be illustrative to compare this number to other benchmark human samples.

Thank you,
Andrew

**Comment by kokyriakidis** [comment]
I used the right one for hg38 with the PAR regions masked as stated here:
```
http://lh3.github.io/2017/11/13/which-human-reference-genome-to-use
```
I see 401 variants on Y out of total 117.009

**Comment by AndrewCarroll** [comment]
Hi @kokyriakidis 

That reference should mask the PAR regions. It's unclear what could be going on for those variants which DeepVariant calls. They may be FP variants in difficult regions, or could be positions where additional copies exist that are similar on autosomes.

In general, there are always likely to be some calls made on chrY. For reference, the New York Genome Center has sequenced all 1000genomes at 30x coverage and mapped to hg38. For the NA12878 (a female sample), GATK4 makes 6,935 heterozygous variant calls and 6,422 homozygous variant calls.

(This VCF file is available at: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20190425_NYGC_GATK/raw_calls/CEU/Sample_NA12878/analysis/NA12878.haplotypeCalls.er.raw.vcf.gz)
