### ISSUE TITLE
Variant Normalization

### ISSUE THREAD

**Issue by aardes** [google/deepvariant#205]
Hi,

I would like to know Deepvariant do the variant normalization (for example left-align for InDels)?, or I need to it with another tool?

Regards

**Comment by AndrewCarroll** [comment]
Hi @aardes 

DeepVariant uses processes that effectively normalize variants in most or all cases in the process of running. As part of candidate generation, DeepVariant constructs a candidate haplotype for the reference and alternate alleles. Reads are aligned to these candidates using Smith Waterman (specifically this library: https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library)

The candidate position reported in the VCF is taken from the realigned location, so this will be normalized as a function of how the SSW library works.

Note that this process does not occur with the PacBio model, since it does not do reassembly.

Finally, variant normalization is a complex area with many edge cases to compare between two files. When we do comparisons (like between DeepVariant and the Genome in a Bottle Truth sets) we use the hap.py + RTG in the hap.py Docker image (https://github.com/Illumina/hap.py).
