### ISSUE TITLE
cant find gcsfuse

### ISSUE THREAD

**Issue by case3526** [google/deepvariant#210]
# Model for calling whole genome sequencing data.
MODEL=gs://deepvariant/models/DeepVariant/0.8.0/DeepVariant-inception_v3-0.8.0+data-wgs_standard
IMAGE_VERSION=0.8.0
DOCKER_IMAGE=gcr.io/deepvariant-docker/deepvariant:"${IMAGE_VERSION}"
COMMAND="/opt/deepvariant_runner/bin/gcp_deepvariant_runner \
  --project ${PROJECT_ID} \
  --zones us-west1-* \
  --docker_image ${DOCKER_IMAGE} \
  --outfile ${OUTPUT_BUCKET}/${OUTPUT_FILE_NAME} \
  --gvcf_outfile ${OUTPUT_BUCKET}/${OUTPUT_gVCF_FILE_NAME} \
  --staging ${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME} \
  --model ${MODEL} \
  --bam gs://files_jays/bam/bqsr.realign.markdup.sorted.merged.bam \
  --bai gs://files_jays/bam/bqsr.realign.markdup.sorted.merged.bai \
  --ref gs://genomics-public-data/references/GRCh38_Verily/GRCh38_Verily_v1.genome.fa \
  --shards 512 \
  --make_examples_workers 32 \
  --make_examples_cores_per_worker 16 \
  --make_examples_ram_per_worker_gb 60 \
  --make_examples_disk_per_worker_gb 200 \
  --call_variants_workers 32 \
  --call_variants_cores_per_worker 32 \
  --call_variants_ram_per_worker_gb 60 \
  --call_variants_disk_per_worker_gb 50 \
  --preemptible \
  --max_preemptible_tries 5 \
  --gcsfuse"
# Run the pipeline.
gcloud alpha genomics pipelines run \
    --project "${PROJECT_ID}" \
    --service-account-scopes="https://www.googleapis.com/auth/cloud-platform" \
    --logging "${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME}/runner_logs_$(date +%Y%m%d_%H%M%S).log" \
    --regions us-west1 \
    --docker-image gcr.io/cloud-genomics-pipelines/gcp-deepvariant-runner \
    --command-line "${COMMAND}"

# logs on one of the VMs
/bin/bash: gcsfuse: command not found
parallel: This job failed:
mkdir -p ./input-gcsfused-0 && gcsfuse --implicit-dirs files_jays /input-gcsfused-0
/bin/bash: gcsfuse: command not found
parallel: This job failed:
mkdir -p ./input-gcsfused-1 && gcsfuse --implicit-dirs files_jays /input-gcsfused-1
/bin/bash: gcsfuse: command not found

**Comment by gunjanbaid** [comment]
Hi @case3526, we recommend running DeepVariant v0.8.0 using the Docker image or prebuilt binaries, instead of the `gcp_deepvariant_runner` pipeline. Here are links to case studies that show how you can run using Docker or binaries. Note: we recommend running the binaries on an Ubuntu 16.04 machine.

* [DeepVariant quickstart with Docker](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md)
* [Script to run WGS case study using binaries](https://github.com/google/deepvariant/blob/r0.8/scripts/run_wgs_case_study_binaries.sh)
