### ISSUE TITLE
 Issue  'No non-empty sample name found in the input reads. Please provide the '

### ISSUE THREAD

**Issue by anitagh** [google/deepvariant#222]
I just downloaded the docker image and ran the following test on Centos OS 7.  Everything worked fine. 

          INPUT_DIR="/test/DeepVariant/quickstart-testdata"
          OUTPUT_DIR="/test/DeepVariant/quickstart-output"
          BIN_VERSION="0.8.0"

          docker run \
               -v "${INPUT_DIR}":"/input" \
               -v "${OUTPUT_DIR}:/output" \
               gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
               /opt/deepvariant/bin/run_deepvariant \
               --model_type=WGS \
               --ref=/input/ucsc.hg19.chr20.unittest.fasta \
               --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
               --regions "chr20:10,000,000-10,010,000" \
               --output_vcf=/output/output.vcf.gz \
               --output_gvcf=/output/output.g.vcf.gz \
               --num_shards=1

Then I modified the shell script to run my sample  
> I'm using the custom ref - included fa, fai, .gz. gzi files in the input dir

          >RHA
            CTGGG .....

> I aligned my reads to the ref and extracted only mapped paired-end reads

    @HD     VN:1.6  SO:coordinate
    @SQ     SN:RHA  LN:911
    @PG     ID:bwa  PN:bwa  VN:0.7.17-r1194-dirty   CL:bwa mem -M -t 10 /.....

> now when I run the docker tool, I get the following error message

2019-09-24 15:23:14.405094: W third_party/nucleus/io/sam_reader.cc:564] Unrecognized SAM header type, ignoring:
I0924 15:23:14.405213 139913087186688 genomics_reader.py:218] Reading /input/test.bam with NativeSamReader
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_iYr42Y/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1235, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_iYr42Y/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1186, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_iYr42Y/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 316, in default_options
    sample_name = extract_sample_name_from_sam_reader(sam_reader)
  File "/tmp/Bazel.runfiles_iYr42Y/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 458, in extract_sample_name_from_sam_reader
    'No non-empty sample name found in the input reads. Please provide the '
ValueError: No non-empty sample name found in the input reads. Please provide the name of the sample with the --sample_name argument.

real    0m1.587s
user    0m3.748s
sys     0m6.337s

What could be wrong?

Thanks,
Azita

**Comment by sidharthgoel** [comment]
Hi, it looks like you need to provide a value for the sample_name flag, but to do that you'll need to run each stage of DeepVariant separately. See https://github.com/google/deepvariant/issues/173 for an explanation of how and why to do this.

**Comment by samanvp** [comment]
Alternatively, you can use [DeepVarianatRunner](https://cloud.google.com/genomics/docs/tutorials/deepvariant#run_deepvariant). It will run all 3 stages and final VCF file will be available at the output bucket.

Note that if you want gVCF output you need to also set the [corresponding flag](https://cloud.google.com/genomics/docs/tutorials/deepvariant#genomic_vcf_gvcf_configuration). Similarly if your index files does not follow standard naming convention (such as `.bam.bai`) you need to set them using their flags.

**Comment by pichuan** [comment]
Hi @anitagh 
From my experience it's not too uncommon for BAM files in the wild to have either no sample name in the BAM file, or multiple sample names (which will crash DeepVariant right now).

We can easily add `--sample_name` to the run_deepvariant.py script, so you can still run that script once. We'll do this so it'll come out in the next release.

So far, we want users to explicitly add this --sample_name this flag because we want to make sure users are aware that their BAM file has more than one (or 0) sample names. But it seems like all the cases I've seen so far, none of them actually intended for them to be different sample names anyway. So I might consider just removing this constraint and just make it a warning message instead.

Either way, in our next release, you should be expecting to have  `--sample_name` flag in the run_deepvariant.py script which you can do in one step. Thanks for reporting.

**Comment by pichuan** [comment]
Hi @anitagh and @PlatonB , 
to give you an update on this issue, we have made a change internally that:
1) Added `--sample_name` to run_deepvariant.py
2) When input BAM files has no sample names or more than one sample names, instead of crashing with the error message you reported, we now use a default string as the sample name (or pick one from the multiple names) and prints out a warning.

This behavior should be less cumbersome to our users, and shouldn't cause any issues for most use cases.

Our team is working towards a next release. Once the release is out, I can post another update to this issue to let you know.

For now, please bear with us and use the solution in https://github.com/google/deepvariant/issues/222#issuecomment-534768468. We'll keep you posted!

**Comment by anitagh** [comment]
Thanks for the quick response. 
I checked my bam file and see only one sample name in the header as shown below.

   @HD     VN:1.6  SO:coordinate
   @SQ     SN:RHA  LN:911
   @PG     ID:bwa  PN:bwa  VN:0.7.17-r1194-dirty   CL:bwa mem -M -t 10 ./references/bwa_index/RHA.fa  ./SNP_Control_Fastq/SNP-Cnt-5p_S6_L001_R1_001.fastq.gz ./SNP_Control_Fastq/SNP-Cnt-5p_S6_L001_R2_001.fastq.gz

I also check the content of the bam file and all records contain the same sample name.

> samtools view SNP-Cnt-5p_S6_L001_001_paired.bam | cut -f 3 | sort | uniq -c
 418776 RHA

Do you know when the next release is out? I have to complete my analysis within a week. I guess for now I should figure out how to call the three steps separately. 

Thanks again, 
Azita

**Comment by samanvp** [comment]
@anitagh [DeepVarianatRunner](https://cloud.google.com/genomics/docs/tutorials/deepvariant#run_deepvariant) runs all 3 stages  and passes the `--sample_name` to all 3 stages if you set it.

@pichuan another option is to use (part of) BAM filename.
> use a default string as the sample name (or pick one from the multiple names)

**Comment by pichuan** [comment]
Hi @anitagh ,
the release won't come out within a week. Sorry for the inconvenience. For now you'll have to run make_examples separately and add the `--sample_name` flag. Another way to fix this is to make sure your BAM file header has one SM tag in it. If your BAM file is not very big, using `samtools reheader` to add a proper SM tag might also be a reasonable solution for now.

If you're using GCP, you can try out the Google Cloud version that @samanvp pointed to in earlier comments. (If you have any feedback on that tool, please report to https://github.com/googlegenomics/gcp-deepvariant-runner/issues.)

**Comment by anitagh** [comment]
Thanks  @samanvp  - unfortunately, because of confidentially issues,  we won't be able to use GCP .

@pichuan - I managed to run the three scripts but am seeing a surprising result. We have sequenced a panel of control amplicons with spiked inputs containing SNP at position 41. I aligned the reads to the ref using bwa mem and filtered paired reads. Then I ran GATK Mutect2, Illumina Pisces, and Deepvariants to confirm the presence of SNP at position 41. Below is my result. 

![image](https://user-images.githubusercontent.com/24441131/65831442-65545a00-e287-11e9-8c55-8541a8ef3fce.png)

I'm not sure what mistake I have made. Below is the set of commands I used to generate the vcf files from the 10% spiked-in sample

BIN_VERSION="0.8.0"
docker run \
  -v "${HOME_DIR}":"/home" \
  -v "${TMP_DIR}":"/tmpdir" \
  gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/make_examples \
  --mode=calling \
  --sample_name=RHA \
  --examples=/tmpdir/make_examples.tfrecord.gz \
  --ref=/home/RHA.fa \
  --reads=/home/SNP-Cnt-10p_S7_L001_001.bam \
  --gvcf=/tmpdir/gvcf.tfrecord.gztest.gv


docker run \
  -v "${HOME_DIR}":"/home" \
  -v "${TMP_DIR}":"/tmpdir" \
  gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/call_variants \
  --checkpoint=/opt/models/wgs/model.ckpt \
  --examples=/tmpdir/make_examples.tfrecord.gz \
  --outfile=/tmpdir/call_variants_output.tfrecord.gz

docker run \
  -v "${HOME_DIR}":"/home" \
  -v "${TMP_DIR}":"/tmpdir" \
  gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/postprocess_variants \
  --ref=/home/RHA.fa \
  --infile=/tmpdir/call_variants_output.tfrecord.gz \
  --nonvariant_site_tfrecord_path=/tmpdir/gvcf.tfrecord.gztest.gv \
  --outfile=/home/out.vcf \
  --gvcf_outfile=/home/out.gvcf

Thanks for all your help
Azita

**Comment by AndrewCarroll** [comment]
Hi @anitagh 

Thank you for putting effort into detailed analyses. However, there is a key mistake. DeepVariant is not a somatic caller. It is not designed to detect subclonal variants. In the same way that for GATK you would not use HaplotypeCaller, you would use a different tool, Mutect2, you would not use DeepVariant for this problem.

Before DeepVariant's neural net, there is a human-written candidate generation component which finds candidate positions. There is a threshold for this to even nominate a candidate for later classification. This is set to 12% (based on tuning for germline calling), so we would not expect that DeepVariant would nominate a 10% mix as candidates. 

We do have a somatic calling tool in early access that we are making available to trusted partners. If you would be interested in that method, you can email me (awcarroll@google.com)

Thank you,
Andrew

**Comment by anitagh** [comment]
Thanks @AndrewCarroll. I'm interested in trying out your new somatic calling tool. I'll contact you shortly. 

Thanks so much, 
Azita

**Comment by pichuan** [comment]
Hi @anitagh , I want to give you an update that after today's release (v0.9.0), you can now use the `--sample_name` flag with run_deepvariant.py:
https://github.com/google/deepvariant/blob/r0.9/scripts/run_deepvariant.py#L89

And, we also made the behavior more robust so that even with multiple or no sample names, we'll try to assign a reasonable default, and proceed with a warning (but without crashing).

If you have more questions please feel free to follow up here, or file new issues.
