### ISSUE TITLE
show image generated from make example

### ISSUE THREAD

**Issue by BowenKwan** [google/deepvariant#229]
I would like to view and save the pileup images generated. 

I was trying to get the features (image/encoded, and image/shape) from the example genereated, and decode then save it using the following code

````
for candidate in candidates:
    for example in self.create_pileup_examples(candidate):
        features_temp = tf.parse_single_example(example_temp, features={'image/encoded': tf.FixedLenFeature([], tf.string),"image/shape": tf.FixedLenFeature([], tf.int64)})
               
        image_temp = features_temp['image/encoded']                                
        shape_temp = features_temp['image/shape']    

        image_temp1 = tf.reshape(tf.decode_raw(image_temp, tf.uint8), shape_temp)

        fh = open(filename_temp, "wb")
        fh.write(image_temp1)
        fh.close()
````

and got the following error

````
TypeError: Failed to convert object of type <class 'tensorflow.core.example.example_pb2.Example'> to Tensor.
````
Is there a neat way to save all pileup images generated when we run the "make example" code?

**Comment by sidharthgoel** [comment]
Hi @BowenKwan, there are a couple things I'll point you to --
1. When you run `run_deepvariant` you can specify the `--intermediate_results_dir` flag where the examples will be saved.
2. In order to visualize, we have [this notebook](https://github.com/google/deepvariant/blob/r0.8/docs/visualizing_examples.ipynb).

That should allow you to visualize the pileup images, let me know if you face any issues.

**Comment by BowenKwan** [comment]
Thank you very much for your reply. However I have 2 question regarding the example visualization. 

1. As I am using multiple cores, the example files are splitted in to 
examples.tfrecord-00000-of-00008.gz to examples.tfrecord-00007-of-00008.gz

can I simply use "examples.tfrecord-00000-of-00008.gz" as the source path? or do I have to combine the 8 examples file together first?

2. I cannot run the program as stated in the notebook as the `label` is not one of the features in the example for deepvariant. Is the label in the notebook the same as  'alt_allele_indices/encoded' in Deepvariant? If so, how can I extract the information from the feature? I have tried  'alt_allele_indices/encoded': tf.FixedLenFeature([], tf.string), but it just gives my random symbols.

**Comment by sidharthgoel** [comment]
1. You can use each shard as the source path, no need to combine.
2. Modify the notebook as needed - the notebook goes through training examples, but in your case there won't be labels for the examples, since you're running inference (see [this](https://github.com/google/deepvariant/blob/aff131aac3bd0cb63ee8314e32bcbf5590987fb8/deepvariant/make_examples.py#L852) for difference).

My general recommendation is to use the notebook as a reference/template for what the Example parsing should look like, but feel free to only include keys that you are interested in.

**Comment by pichuan** [comment]
Hi @BowenKwan , I'm closing this issue. If you have more questions, let us know.
