### ISSUE TITLE
MNP Support

### ISSUE THREAD

**Issue by segoerge** [google/deepvariant#238]
Dear DeepVariant Team,

I have a short question. Are there any plans for calling MNPs in near future? This would be really helpfull for variant annotations further downstream.

Sebastian

**Comment by AndrewCarroll** [comment]
Hi @segoerge 

Thank you for your question. It is a good observation that better support for MNP would be helpful. We have discussed this internally to a limited extent, but have not yet mapped out what would be involved to make the change. I couldn't give a timeframe for this yet (or give an indication as to whether this could be something in the next release).

Your feedback is appreciated, as it helps us understand the needs of the user community.

Thank you,
Andrew

**Comment by splaisan** [comment]
HI!
any update on this topic?

We called multiple genomes recently and found a first example of 4 adjacent base substitution AACT => GGTC being called 4 separate SNVs.

The support information is very similar for the 4 calls and I wonder why deepvariant did not call them as one single MNP. This makes that the annotation and effect prediction downstream are wrong.

Thanks for your support

![failed_MNP-call](https://github.com/google/deepvariant/assets/858516/a02c3b5a-0362-4030-be8a-8b3c49129a8f)

here is the extract of the gVCF at that location for one sample

```
chrNN   51225801        .       T       <*>     0       .       END=51225807    GT:GQ:MIN_DP:PL 0/0:50:27:0,81,809
chrNN   51225808        .       A       G,<*>   30.5    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:30:26:17,9,0:0.346154,0:30,0,37,990,990,990
chrNN   51225809        .       A       G,<*>   31.8    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:31:26:17,9,0:0.346154,0:31,0,38,990,990,990
chrNN   51225810        .       C       T,<*>   31.6    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:31:26:17,9,0:0.346154,0:31,0,39,990,990,990
chrNN   51225811        .       T       C,<*>   32.2    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:31:28:17,9,0:0.321429,0:32,0,37,990,990,990
chrNN   51225812        .       C       <*>     0       .       END=51225881    GT:GQ:MIN_DP:PL 0/0:48:26:0,87,869
```

**Comment by splaisan** [comment]
identical issue as in https://github.com/google/deepvariant/issues/520

**Comment by pgrosu** [comment]
Hi Stephane,

In the meantime would running `freebayes` (alongside DeepVariant) to generate MNPs using your DeepVariant realigned BAMs, and then `bcftools merge` the results from the two VCFs (FB + DV) help out?

~p

**Comment by AndrewCarroll** [comment]
Hi @splaisan 

We are currently working on a more complete approach for MNPs, but we don't have any update at this time and it won't be in the very next release. Hopefully sometime after that we will have results for MNPs, but I can't give a specific timeline.

**Comment by splaisan** [comment]
Thanks both for your answers,
@pgrosu this is hardly a solution as the calling took now more than a week on 88 threads plus merging the calls will lead to overlaps and discordances difficult to resolve without manual inspection (which I cannot do as a service) and also as I am going through gVCF and GLnexus merging which is not that well supported for freebayes in my experience (I might have overlooked though).
@AndrewCarroll this is great, it will surely be appreciated by the community as this issue has been raised by several already and is annoying in a clinical setting. Please make sure to advertise it when it comes out so that we can try it.
Cheers

**Comment by pgrosu** [comment]
Hi @splaisan,

That is a very complex the experimental setup.  I initially proposed freebayes + DV in order to merge and observe them together, for making proper selection in study-specific regions as a follow-up among the two results.  Of course it would easier to write a program to compare between the two filtered on thresholds appropriate to you design.

In any case, even though [freebayes has gVCF output](https://github.com/freebayes/freebayes/blob/master/README.md#usage), let's ignore that for now and look closer at GLnexus algorithm - as it gives nice insights about how variants are processed from gVCF files.  Thus when it generates the pVCF, unified variant sites are collected from variants spanning overlapping regions.  Since it performs $`\arg \max_{g} Pr(Genotype = g) Pr(Data | Genotype = g)`$, having multiple possible MNPs in the unified site (across gVCFs) dilutes the probability of each genotype, and thus having them as individual SNPs ensures the GQ and PL are maximally contributed to for each base.  This is also because for such unified sites, it considers all discovered QC-filtered alleles greedily in descending order of frequency, and might be exacerbated with rare alleles when calling sites.

Therefore given the above, utilizing the combined output of the VCF for post-processing into MNPs might be optimal.  Ideally, having phasing information would also provide more confidence in the quality of MNPs from combined adjacent SNPs belonging to a haplotype.  If possible, limiting via a BED file to regions that are more relevant for your study - especially under heavy multi-threaded conditions - might shorted the analysis time.  With many threads you might be thrashing, thus limiting your performance by spending more time context-switching.

Hope it helps,
Paul

**Comment by pziarsolo** [comment]
> Hi [@splaisan](https://github.com/splaisan)
> 
> We are currently working on a more complete approach for MNPs, but we don't have any update at this time and it won't be in the very next release. Hopefully sometime after that we will have results for MNPs, but I can't give a specific timeline.

Do we have any update regarding this feature?

Thanks in advance!
