### ISSUE TITLE
Singularity Issue - libopenblas.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jguhlin** [google/deepvariant#243]
Converting the deepvariant 0.9.0-gpu docker image to singularity results in the following issue when run as non-root user:

```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_lkokkqy4/runfiles/com_google_deepvariant/deepvariant/model_train.py", line 46, in <module>
    from tensor2tensor.utils import metrics_hook
  File "/home/josephguhlin/.local/lib/python2.7/site-packages/tensor2tensor/utils/metrics_hook.py", line 22, in <module>
    import tensorflow as tf
  File "/home/josephguhlin/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/josephguhlin/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "/home/josephguhlin/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/josephguhlin/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory
```

I need to run deepvariant as a non-root user via singulairty on the HPC platform. The non-GPU version works just fine.

**Comment by pichuan** [comment]
Hi @jguhlin ,
thanks for the feedback, and for letting us know that our users are still interested in Singularity images.
I have been a bit hesitated to make Singularity images part of our formal release process, mostly because the additional quality control burden. 
But, in the future we'll consider building these *.simg files and just distribute them.

The steps below I used were documented here:
https://github.com/google/deepvariant/issues/132#issuecomment-482430728

I have the detailed commands that I used for my conversion, and I copied the output *.simg files here:

```
gs://deepvariant/singularity_images/deepvariant-0.9.0-gpu.simg
gs://deepvariant/singularity_images/deepvariant-0.9.0.simg
```
Or you can find them in the browser here:
https://console.cloud.google.com/storage/browser/deepvariant/singularity_images/

I was able to test both CPU and GPU version on the Quick Start data (see below). Can you see if if my `deepvariant-0.9.0-gpu.simg` file works for you?

------

# @pichuan 's notes on building DeepVariant Singularity images for CPU and GPU (v0.9.0)

If you don't have singularity on your computer, install it first:
https://sylabs.io/docs/

Once you do, you can pull the DeepVariant Docker image and convert it to a Singularity image.

## CPU image

```
VERSION=0.9.0
sudo apt -y update && sudo apt-get install -y docker.io
sudo docker pull google/deepvariant:${VERSION}
sudo docker tag google/deepvariant:${VERSION} localhost:5000/deepvariant:latest
sudo docker run -d -p 5000:5000 --restart=always --name registry registry:2
sudo docker push localhost:5000/deepvariant:latest
SINGULARITY_NOHTTPS=1 singularity build deepvariant-${VERSION}.simg docker://localhost:5000/deepvariant:latest
```

To run [Quick Start](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md), instead of using the docker command, you can use this command instead:

```
singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/  \
  deepvariant-${VERSION}.simg \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta \
  --reads=${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=output.vcf.gz \
  --output_gvcf=output.g.vcf.gz   
```

## GPU image
```
VERSION=0.9.0-gpu
sudo nvidia-docker pull google/deepvariant:${VERSION}
sudo nvidia-docker tag google/deepvariant:${VERSION} localhost:5000/deepvariant_gpu:latest
sudo nvidia-docker run -d -p 5000:5000 --restart=always --name registry registry:2
sudo nvidia-docker push localhost:5000/deepvariant_gpu:latest
SINGULARITY_NOHTTPS=1 singularity build deepvariant-${VERSION}.simg docker://localhost:5000/deepvariant_gpu:latest
```

Running through Quick Start just to make sure nothing wrong:
```
singularity -s exec --nv -B /usr/lib/locale/:/usr/lib/locale/  \
  deepvariant-${VERSION}.simg \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta \
  --reads=${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=output.vcf.gz \
  --output_gvcf=output.g.vcf.gz   
```

Both CPU and GPU versions finished on Quick Start data without errors.

## Misc
For installing nvidia-docker and singularity, you can also refer to https://github.com/google/deepvariant/blob/r0.9/scripts/install_nvidia_docker.sh
and
https://github.com/google/deepvariant/blob/r0.9/scripts/install_singularity.sh

**Comment by aderzelle** [comment]
I strongly concur. Singularity images would be nice. Using Docker has already given me multiple diseases. It's such a hassle and from what other colleagues tell me, I am not the only one. 
Note that there is nothing wrong with the deepvariant image, it's the Docker process that can cause many problems running, pulling images, restarting, generating errors, etc ... 
Like this issue, unresolved since 2017: 
https://github.com/docker/for-win/issues/813

Dark Souls bosses are easier to take down than pulling a docker image on some systems. 
So to be clear again, nothing wrong at all with deepvariant, which I love more and more btw, but having something else than Docker would be indeed really great.

**Comment by pichuan** [comment]
Hi @aderzelle 
thanks for your feedback. If you have a chance to try out the two images I shared:
```
gs://deepvariant/singularity_images/deepvariant-0.9.0-gpu.simg
gs://deepvariant/singularity_images/deepvariant-0.9.0.simg
```
Please let me know whether they work for you or not. If you see any issues, please let us know.

**Comment by jguhlin** [comment]
Hi @pichuan. It looks like this singularity container works well, thanks. A singularity container would be great, although possibly figuring out what's wrong with the docker conversion might be the way to go (it could be something on my end as well).

Docker is being phased out at some research institutions due to its reliance on the root user, so singularity is where we are at. But the conversion usually just works. Now to figure why training with deepvariant is only producing refcalls.....

**Comment by pichuan** [comment]
Thanks @jguhlin . In the next release we'll plan to include the converted version in the same GCS bucket.

**Comment by ksw9** [comment]
Hi @pichuan,
Thank you for posting these Singularity images. I tested them on a computing cluster on the test data, following the instructions above and ran into errors similar to those posted in another issue, below. I'm wondering if you have any suggestions for workarounds? Thank you in advance for your help! 
Best,
```

***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/labs/jandr/walter/tb/test/deepV/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/labs/jandr/walter/tb/test/deepV/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

ImportError: No module named _multiarray_umath
ImportError: No module named _multiarray_umath
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2020-01-28 19:06:29.164168: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 

real	0m4.153s
user	0m0.699s
sys	0m1.614s

```

**Comment by pichuan** [comment]
FYI:
I plan to remove the gs://deepvariant/singularity_images directory , and suggest our users to directly pull from our Docker image instead. Example:
```
BIN_VERSION="1.0.0"
singularity pull docker://google/deepvariant:"${BIN_VERSION}"
```
