### ISSUE TITLE
Deepvariant on a diploid asexual?

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#257]
Hello, 
out of curiosity, I wondered if any of you had tried out deepvariant in an asexual diploid organism. I know some people have tried it on bacteria. My understanding is that deepvariant will technically work, i.e produce a vcf. The biological relevance of the calls might not be guaranteed (but anyway that would be true for any methods). I will compare it with GATK and probably Octopus.

**Comment by MariaNattestad** [comment]
We have not tried DeepVariant on an asexual diploid organism, but I see no reason why it shouldn't work. However, we have observed that the models we have trained on human data are good but not optimal for non-human genomes. See this blog post for an example in mosquitos where training a species-specific model improved performance: https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/

Now we are curious, which organism are you working on?

**Comment by aderzelle** [comment]
Thanks for the reply. I had seen the blog post, we are thinking about implementing it. 
We are working with ancient asexual species, among others, the bdelloid rotifers, very tricky organisms to work with for many reasons.

**Comment by AndrewCarroll** [comment]
Hi @aderzelle 

As Maria indicates, generally, applying DeepVariant to this organism should work. I think the main question is: How close is there reference genome to the organisms you are sequencing. If the reference genome is highly diverged relative to your population, reference incompleteness will make analysis difficult, and the nearby variants observed in the mosquito blog may also be an issue.

However, if the reference genome is close to the population (which can be measured by the variant density X bps/SNP), then I think that applying DeepVariant to this genome should work well.

I was always a fan of rotifers, how interesting to study them!

**Comment by aderzelle** [comment]
Thank you! 
My experiment was designed for the reference to be as close as possible to the studied populations so that shouldn't be an issue. Thanks for the always fast feedback.
I read in the blog post

> Of the 94,554 Mendelian violations where the child is HOM_REF, **only 17,475 (18%) of those have the HOM_REF call based just upon reference and non-reference read counts, the remaining 82% had the HOM_REF call produced by the CNN**. This seemed suspicious, so we investigated the allele depth fractions for each of HOM_REF, HETEROZYGOUS, and HOM_ALT calls in all three individuals

That's interesting because I also get quite a non trivial number of HOM_REF calls which, just based on the biology and specifics of my experiment (I prefer to remain vague about that publicly) is highly suspicious. In fact, all new homozygous variants are suspicious in my experiment. 

I have highlighted a sentence in boldface, simply: how did you do that? How do you know that deepvariant made the call based on non-reference/reference read ratio or that it made the call based on its CNN interpretation? I thought the CNN was used for all calls? Or I am missing something obvious here?

**Comment by AndrewCarroll** [comment]
Hi @aderzelle 

I have two recommendations: First, to tell whether the CNN made a RefCall classification, you can look for an output line in the VCF itself. DeepVariant will write a RefCall for every candidate considered. If a line is not present in the output VCF, it means that the reference and non-reference read counts instead generated the reference call because a candidate was not made at that position.

Second, I would recommend that you look at the visual report that @MariaNattestad created in the most recent DeepVariant release. There is a way to run this on previous VCF files, see: [This page](https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-vcf-stats-report.md)

In that visualization, take a look at the VAF support for each call. The nearby variant phenomenon manifests as a higher number of REF calls with a VAF close to 1.0. In humans, this seems to be DeepVariant avoiding false calls in LINE elements and segmental duplications, but this could be undesirable depending on your reference genome and population structure.

**Comment by aderzelle** [comment]
Ok thank you for the clarification.
Oh yes, I noticed the new html report, I used to make those plot with a custom script, I think it's a great addition to deepvariant output to have them out of the box. Just an idea: I think some users might like it if you generated the data table used for each of the plot (I guess you must have them produced at some point anyway). That could make comparison between different runs, callers, etc ... easier.  At least in our team, we spent a lot of time making those kind of plots for different runs/callers/conditions and cross-comparing. Having the raw numbers is then easier (okay it's not really a big deal to extract them from the vcf).

**Comment by MariaNattestad** [comment]
Great, glad you found the report useful!

If you need the numbers from the visual report, you can extract them by clicking the button on the top right of the report and in the dropdown selecting "View Source". This gives the JSON that in vega-lite produces those plots, and it has the summarized data inside it. These are all summarized data though, since the raw data is the VCF itself. 

Also note that you can run our DeepVariant visual report with VCFs from other callers if you want to compare. Other VCFs may be missing some of the information used to make a few of the plots, but otherwise it should work fine -- I stress tested the visual report a lot to make sure of that. Let me know if you try it whether that works for you. And good luck with your research!

**Comment by aderzelle** [comment]
> Hi @aderzelle
> 
> I have two recommendations: First, to tell whether the CNN made a RefCall classification, you can look for an output line in the VCF itself. DeepVariant will write a RefCall for every candidate considered. If a line is not present in the output VCF, it means that the reference and non-reference read counts instead generated the reference call because a candidate was not made at that position.
> 
> Second, I would recommend that you look at the visual report that @MariaNattestad created in the most recent DeepVariant release. There is a way to run this on previous VCF files, see: [This page](https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-vcf-stats-report.md)
> 
> In that visualization, take a look at the VAF support for each call. The nearby variant phenomenon manifests as a higher number of REF calls with a VAF close to 1.0. In humans, this seems to be DeepVariant avoiding false calls in LINE elements and segmental duplications, but this could be undesirable depending on your reference genome and population structure.

Hello, in my case, which is not humans, I find the following. First, the reads I used are the same used during the reference genome assembly process. Therefore, any new homozygous variant with a vaf of ~ 1 is either the reflect of assembly errors / mapping errors. I do find such variants. But I am more intrigued by the peak of Hom (x/x) at a vaf of ~ 0.5 

am I right to assume this is not typical and might reflect a problem? 
Interestingly for the reference calls, there also seems to be 2 peaks, one with a vaf around 0.2 which I guess is all right and one with a vaf around 0.5 which I guess also indicates a potential problem.

![genotypes_deepvariant](https://user-images.githubusercontent.com/23341393/72908229-7db81b00-3d35-11ea-99f9-e3dfa126a127.png)

As I am working with an asexual diploid, I can't replicate the methodology of the mosquito to retrain deepvariant. I, however, have an ancestral population and the direct descendant, with absolutely no reason to believe the descendant might exhibit new mutations (except for the ones that might randomly occur but those should be negligible). Therefore, I was thinking of comparing the ancestral and daughter populations, and regard each new variant in the daughter as artefacts and/or the shared variants are the "truth set". Does that sound reasonable as a way to retrain the CNN?

Thanks a lot!

**Comment by aderzelle** [comment]
May I gently bump up the issue? I have never trained a CNN before and I would like an opinion, if what I plan make sense
thank you =)

**Comment by AndrewCarroll** [comment]
Hi @aderzelle 

I followed up to this similar question in the GitHub issue #266 thread. There we are suggesting to use an experimental non-human model.
