### ISSUE TITLE
DeepVariant calling homozygote at obvious heterozygote sites

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#266]
Hello, 
the following sites are all called with high confidence (GQ >=20) to be RefCall.
![RefCall](https://user-images.githubusercontent.com/23341393/73534867-8211c180-4422-11ea-9521-162cfbe215d2.png)

However, they seem rather obviously to be het sites, the VAF is 0.5. 
But, they are all close to each other and on the same reads actually ... Is this the reason, would deepvariant regard those as "too close"? My genome is much smaller than the human genome and has a very low repetitive content (~3%).

**Comment by AndrewCarroll** [comment]
Hi @aderzelle 

Thank you, this is a good question. We have observed this phenomenon as well. The answer is somewhat complicated. 

DeepVariant seems to have learned something about the concept of segmental duplication, where positions that appear to be variants are actually due to mismapping of similar regions which may (or may not) be captured in the reference genome. The way this manifests in a genome pileup is as one phased haplotype that is mostly reference and (one or more) phased haplotype that is variant-dense. The signal for this is further enhanced when the VAF is closer to 0.33 or 0.25 (more directly suggesting copy number 3 or 4), but it can also occur close to 0.5 (which can still indicate a copy number of 4).

These regions can be variants in thee diploid genome that are incorrectly called as REF, or they could be markers of a copy number variant.

In human genomes, this can suggest a user look into that region for either known copy number variants or coverage differences. One question to ask - are these regions at generally higher coverage than you would expect? 

In certain variant-dense species, we have observed this phenomenon to complicate calling [in this blog we investigate this for mosquito genomes](https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/)

In this blog, we show the ability to re-train for a variant-dense species using a pedigree. If you have a pedigree available, we could also explore this with you.

We are working on ways that will allow DeepVariant to more explicitly indicate when it thinks this is the case, and to provide more information (e.g. average coverage in the sample) to DeepVariant that will allow it to better separate variants from makers of segmental duplication.

**Comment by aderzelle** [comment]
Hello, thanks for your answer. Actually my organism is an ancient tetraploid; it's quite old but we are able to find back the old duplicates easily (they just look like alleles with high divergence).  The coverage in those regions doesn't deviate from what is expected. 

I would bet the rotifers are variant dense, their genome is small (100 Mb) and there doesn't seem to be a lot of repeats. Somehow, it's quite the exact opposite of the human genome (large and full of repeats). 
The thing is, as it is an asexual, I can't replicate the trio strategy, as I only have a mother and a descendant. So I am unsure about what to do here. I was planning to call the variant in the mother and the daughter, assuming there should be all identical. Any new variant in the daughter I would regard as calling errors. (and I see new variants, though most of the variant in the daughter are the same as in the mother). I am unsure if retraining would make sense here.

**Comment by aderzelle** [comment]
I am kindly bumping up this thread. I know it's not good etiquette so I am sorry but I don't see how to retrain DeepVariant despite having mother daughter samples.

**Comment by AndrewCarroll** [comment]
Hi @aderzelle 

Would you be interested to experiment with a model we have trained on non-human species? If so, perhaps we can move this discussion to email (awcarroll@google.com) and we can provide you the model with some instructions. No guarantee that this will resolve the issue, but we think it is worth trying.
