### ISSUE TITLE
Plotting tool not working properly

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#267]
Hello, I tried the plotting tool of DeepVariant on the vcf produced by the Octopus caller
![ARCcestor octopus visual_report](https://user-images.githubusercontent.com/23341393/73610464-c8f4e800-45d7-11ea-834a-78603d414f80.png)

As you see many plots are empty. Well, it's not critical as of course I can redo these plots but I thought you might like to know. 

Cheers.

EDIT: is it because octopus produces phased genotypes?

**Comment by MariaNattestad** [comment]
The vcf_stats_report script can only use the data that is in the VCF file. Since this is built for DeepVariant VCF files, other callers may not include all the same metrics in their output VCFs. We made sure the script is flexible enough to finish creating a report despite this missing info, but the charts cannot be made if the data isn't there.

**Comment by aderzelle** [comment]
yes sorry, I thought by closing the issue you wouldn't have to look at it. 
Indeed octopus doesn't produce VAF (well, it does but you have to ask for it at the command line). 
Sorry.

**Comment by tyrserleu** [comment]
![Image](https:github.com/user-attachments/assets/017b2b2a-c882-40e0-ae36-00b2e97210a3)
Hello, I would like to ask, why is the minus sign not displayed correctly?

**Comment by tyrserleu** [comment]
Why won't my minus sign (-) display correctly?

![Image](https://github.com/user-attachments/assets/979dd551-f5e4-4b48-ad09-847f7888e2d9)

**Comment by MariaNattestad** [comment]
@tyrserleu please open a new issue with your question. This is an old closed issue, which is harder for the team to track and respond to.
