### ISSUE TITLE
threads per shard

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#271]
Hello,
It seems that 1 shard = 1 thread, however at some point in its run it seems that DeepVariant takes more threads N_SHARD is set to 20, no one else is using the computer at this moment and clearly more than 20 threads are taken.

![higdpgpplenjbaao](https://user-images.githubusercontent.com/23341393/74519762-a12a4c00-4f16-11ea-986c-b785044a618b.png)

Is it expected?

**Comment by pichuan** [comment]
Hi @aderzelle 
This is not unexpected:
the relationship between n_shards and how many processes is not 1:1 in the `call_variants` step. In `call_variants` step, the parallelism is decided by TensorFlow, which can be controlled by the `config_string` flag of call_variants.

If you're using the run_deepvariant script, you should be able to add a flag like this:
`--call_variants_extra_args config_string="gpu_options: {per_process_gpu_memory_fraction: 0.5}"` to specify your config_string.

I think this is the options you have: https://www.tensorflow.org/api_docs/python/tf/compat/v1/ConfigProto
(I can't find a better documentation, though. @gunjanbaid do you know?)

@aderzelle - Let me know if this works. I usually don't specify this because the default setting works well for my own use case. It'll be great if you share what your use case is, and let us know whether you're successful by setting this flag.

**Comment by aderzelle** [comment]
I am running it on a local machine, as far as I know I am not running on the GPU.

**Comment by pichuan** [comment]
Hi @aderzelle 
The flag option I gave was just an example.
Maybe use_per_session_threads in the config proto can be relevant. I haven't used this option before so I can't be completely sure. 
Are you trying to limit to just one thread?

**Comment by aderzelle** [comment]
Oh no, it's just that we are 3 sharing a local big computer, hence it's important we know exactly what resource each piece of software uses. But now that I know that 1 shard =/= 1 cpu thread that's already a big help. It's just a matter of planning with coworkers.

**Comment by pichuan** [comment]
Got it. Thanks for the context! If you end up tweaking the config, let me know whether it works for you or not.
I'll close this bug now.
