### ISSUE TITLE
Missing data/low coverage handling

### ISSUE THREAD

**Issue by yassineS** [google/deepvariant#279]
- How does deepVariant behave with low-coverage data which results in a lot of missingness? 

- What's the lowest coverage the tool could be used with?

Thanks!
Yassine

**Comment by AndrewCarroll** [comment]
Hi @yassineS 

Thank you for the question. In short, DeepVariant tends to call fewer variants as coverage drops (this is similar to other callers). We have benchmarks for down to 15x of Illumina WGS [at our "20 is the new 30 blog post](https://google.github.io/deepvariant/posts/2019-09-10-twenty-is-the-new-thirty-comparing-current-and-historical-wgs-accuracy-across-coverage/). This also breaks down the types of errors by class as coverage falls.

I am not sure what the lower bound of coverage for using DeepVariant. At some point, imputation approaches will be required instead of variant calling ones. I would guess this is somewhere around 5x-8x. 

I am curious how low you consider low coverage, so I understand your use case.

**Comment by yassineS** [comment]
Hi Andy, thank you for your response.

I am working with ancient DNA which in the vast majority of the cases comes
at coverages between 0.1-1X. So data missingness is a reality we know how
to deal with, I just want to make sure that the calls we are making are
accurate.

The second family of data I am working with are indigenous groups that are
at least diverged from the reference over 2000 generations ago. We observe
a strong bias towards the reference allele using GATK, but it'll be very
interesting to see how DeepVariant behave in such cases.

**Comment by gunjanbaid** [comment]
@yassineS thanks for the details! For 0.1-1x data, I would not recommend using DeepVariant.  In it's current form, is not suited to handle such low coverages.

**Comment by gunjanbaid** [comment]
@yassineS I'll go ahead and close this issue, but feel free to reopen if you still have pending questions. Thanks!
