### ISSUE TITLE
RNAseq

### ISSUE THREAD

**Issue by claudiologiudice** [google/deepvariant#283]
Is it possible to use deepvariant with RNAseq data?

**Comment by pichuan** [comment]
Hi @claudiologiudice ,
You can find the answers in this older thread: https://github.com/google/deepvariant/issues/115
Our answer would still be the same.

I think some of our users have adapted DeepVariant to run on RNAseq data. If some of them would like to share here, that will be great. But we don't have an official solution right now.

**Comment by danielecook** [comment]
@claudiologiudice although this issue was closed some time ago, we have just released a new RNA-seq model and [case study](https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-rnaseq-case-study.md) for Illumina data. 

Please take a look if you are still considering this and let us know if you have any feedback.
