### ISSUE TITLE
Does the function "binarize(labels, target_class)" in modeling.py have an error return?

### ISSUE THREAD

**Issue by PythRs** [google/deepvariant#286]
It says in the notes "The labels that are not equal to target_class parameter are set to zero."
But return is "The labels that are equal to target_class parameter are set to zero."
Is there a problem with my understanding?

**Comment by pichuan** [comment]
Hi @PythRs , thank you for pointing this out.

You're correct.

Specifically, this logic:
```
  labels_binary = tf.compat.v1.where(
      tf.equal(labels, tf.constant(target_class, dtype=tf.int64)),
      tf.zeros_like(labels), labels)
```
Will actually make everything that is target_class become 0, and keep other class that is not target_class the original label.

However, because of the way we use this "binarize" downstream with F1s, flipping class 0 and 1 doesn't make a difference, so a good news (at least for me) is our internal training and model picking process doesn't get affected by this.

Thinking through this a bit more, I think the logic should be something like:

```
  labels_binary = tf.compat.v1.where(
      tf.equal(labels, tf.constant(target_class, dtype=tf.int64)),
      tf.ones_like(labels), tf.zeros_like(labels))
```

I will work on an internal fix first, and add corresponding unit tests. This won't come out in v0.10.0 (because we've already cut the release; it'll come out soon). But we'll make sure the fix is in the next one.

Thanks @PythRs again for reporting this!

**Comment by pichuan** [comment]
Hi @PythRs ,

to give you a quick update on this issue: I have made the code changes in our codebase, which will come out in our next release.

I ended up updating the comments, fixing an issue in the logic. Now the function looks like this:

```
def binarize(labels, target_class):
  """Binarize labels and predictions.

  The labels that are equal to target_class parameter are set to 0, else
  set to 1.

  Args:
    labels: the ground-truth labels for the examples.
    target_class: index of the class that is left as zero.

  Returns:
    Tensor of the same shape as labels.
  """
  labels_binary = tf.compat.v1.where(
      tf.equal(labels, tf.constant(target_class, dtype=tf.int64)),
      tf.zeros_like(labels), tf.ones_like(labels))
  return labels_binary
```
