### ISSUE TITLE
AVX2 or AVX512 enable deepvariant binaries

### ISSUE THREAD

**Issue by forumsan** [google/deepvariant#301]
I'm using google/deepvariant-0.10.0 through docker on AVX-512 instruction capable Intel skylake processor. But the docker image "google/deepvariant-0.10.0" binaries are not built for AVX-512. Here are the warnings for the same:

 ` I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA `

Where can I get deepvariant or tensorflow binaries with AVX-512 optimzation? I tried to build deepvariant from source, but couldn't due to lot of dependencies. 

Please let me know if there is any way to get AVX-512 optimized binaries for deepvariant/tensorflow.

**Comment by gunjanbaid** [comment]
Hi @forumsan, thanks for reporting this issue! Others users have reported seeing this message as well. When we looked into this issue internally, we found out that this was actually a problem with logging in TensorFlow, and AVX-512 instructions are being used correctly. If you try running DeepVariant on a CPU-only machine that does not support AVX-512, you should see a clear increase in the overall runtime.

The logging issue has since been fixed in TensorFlow, but won't show up in our current Docker images. This is because we are installing a version of the intel-tensorflow package that does not contain the fix. I'll close this issue for now, but feel free to reopen if you still have other questions. Thanks!

**Comment by forumsan** [comment]
Thanks @gunjanbaid for the quick response. 
I'm using the recent version of deepvariant docker image 0.10.0. But still it shows up this issue. Do you have a more recent version docker image than 0.10.0? If yes, then getting that docker image will be helpful for us to get AVX2 or AVX-512 benefits. Thanks

**Comment by gunjanbaid** [comment]
Hi @forumsan, you are already getting the speedup from AVX2/AVX-512 if you are using Intel Skylake or later! :) The message you are seeing is an issue with logging in TensorFlow. Feel free to ignore that message.

**Comment by forumsan** [comment]
Thanks @gunjanbaid for reconfirming.
