### ISSUE TITLE
What does " . /0" or  " . /1" stand for?

### ISSUE THREAD

**Issue by tetsuro90** [google/deepvariant#302]
Hi,

I used DeepVariant+GLnexus to detect the mutations.
In the GT area of the VCF file, there were descriptions such as " . /0" , " . /1" or " . /2".

I've never seen a pattern like " . /0" or " . /1" when using gatk's haplotypecaller.
Basically, I recognized " . " as a missing value. What do the missing values and the heterogeneity of ALT mean?
Does this mean that it is different from the heterozygous mutation of "REF/ALT",  which is different from " 0/0"  or " 0/1"??

Thanks

**Comment by AndrewCarroll** [comment]
Hi @tetsuro90  (+ @mlin),

The ./0, ./1, etc... GT comes from GLnexus. Mike Lin is the definitive expert on GLnexus and the representations of its output. I believe this occurs in situations where multiple rows of ALTs have to be separated due to many overlapping alleles. In this case, the information of one of the REF+ALT combinations is represented on the line, but the information for another REF may be present elsewhere in a different line.

**Comment by mlin** [comment]
Hi @tetsuro90 [this documentation](https://github.com/dnanexus-rnd/GLnexus/wiki/Reading-GLnexus-pVCFs) has more information about the representation and the "half-calls" specifically. It involves some gnarly issues with overlapping variants in VCF for which there isn't a lot of standardization across tools unfortunately.

[This issue](https://github.com/dnanexus-rnd/GLnexus/issues/210) also discusses some potential future developments. Any feedback there is welcome. Thanks!

**Comment by tetsuro90** [comment]
Hi @AndrewCarroll @mlin 

I guess I didn't try hard enough to find the information, and apologize for my laziness.

I read the documentation and the issue.
Now,  I understand the "half-calls" specifically.

It's a bit complicated, but I think this notation is a reasonable way to describe the information of the overlap.

Thanks!!
