### ISSUE TITLE
Troubleshooting segmentation fault 

### ISSUE THREAD

**Issue by cjain7** [google/deepvariant#313]
Dear deepvariant developers,

I'm using deepvariant (0.10.0) to call variants in HG002 human genome using Pacbio hifi sequencing data. However, I am getting a seg-fault error in the process. 

```
REF=GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
BAM=output.primary.bam
MODEL="/opt/models/pacbio/model.ckpt"
N_SHARDS=24
CALL_VARIANTS_OUTPUT="output/call_variants_output.tfrecord.gz"

mkdir input output logs

/usr/bin/time seq 0 $((N_SHARDS-1)) \
  | parallel -P ${SLURM_CPUS_PER_TASK} --eta --halt 2 \
  --joblog "logs/log" --res "logs" \
  make_examples --mode calling \
  --ref "${REF}" \
  --reads "${wd}/${BAM}" \
  --examples output/examples.tfrecord@${N_SHARDS}.gz\
  --task {} \
  || exit 1
```

Here is the [output log file](https://github.com/google/deepvariant/files/4714025/slurm-58983130.log)

Please let me know if I can share more details.

**Comment by pichuan** [comment]
Hi @cjain7 
First of all, we recommend using the one command version to run:
https://github.com/google/deepvariant#how-to-run
If you use this command, you'll want to use `--model_type=PACBIO` for HiFi data.

In your example, you're running make_examples directly. In that case, you need to add `--norealign_reads --vsc_min_fraction_indels 0.12` to your make_examples command.
These flags are documented in https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-pacbio-model-case-study.md#running 

Once you specify `--norealign_reads`, your run should also be significantly faster.

I'm closing this issue now. If you're still encountering any issues, please feel free to report again.

(FYI @williamrowell because this is a PacBio related question)

**Comment by cjain7** [comment]
Thanks!
