### ISSUE TITLE
Running DeepVariant for several alignment files

### ISSUE THREAD

**Issue by Reedwarbler** [google/deepvariant#33]
I am running DeepVariant on google cloud following the wiki (Cost-optimized configuration): https://cloud.google.com/genomics/deepvariant, and it works for one of our sample. 

Now I have several bam files for several samples. I can run them one by one. But I wonder is there some options to set a list of bam files? Thank you.

**Comment by depristo** [comment]
@arostamianfar for visibility.

**Comment by arostamianfar** [comment]
There isn't an option to provide multiple BAM files in a single request since each request needs a separate staging directory and needs to be processed independently.

However, you may run multiple pipelines at the same time provided you have enough quota in your project (IPs, CPU, GPU (if applicable), disk). If you are running a substantial (>1000) number of jobs, then please also increase the genomics API quota. See https://cloud.google.com/compute/quotas for details on how to adjust your quota.

**Comment by Reedwarbler** [comment]
So it should charge same amount of money right (compare running one by one and in parallel)?

**Comment by arostamianfar** [comment]
Correct. The amount of compute is the same regardless.

**Comment by Reedwarbler** [comment]
Thank you for all the information and help!
