### ISSUE TITLE
sudo authority problem

### ISSUE THREAD

**Issue by BIjoy92** [google/deepvariant#335]
**Describe the issue:**
(A clear and concise description of what the issue is.)
I have no "sudo" authority
I think deepvariant tool have to run "sudo" authority 
and I did this command
`sudo docker pull google/deepvariant:"0.10.0"`

as far as I understand, this next step is 
`sudo docker run \
-v "${INPUT_DIR}":"/3.Sort" \
-v "${OUTPUT_DIR}:/output" \
google/deepvariant:"${BIN_VERSION}" \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref="${ref_fasta}" \
--reads="/3.Sort/$1_Markdup_sort.bam" \
--output_vcf=/output/$1_Deepvariant.output.vcf.gz \
--output_gvcf=/output/$1_Deepvariant.output.g.vcf.gz \
--num_shards=${N_SHARDS}
`
is that right?
But I can't use "sudo" every time

how can I run 'deepvariant' without 'sudo' ??  

**Setup**
  - Operating system: Ubuntu
  - DeepVariant version:0.10.0

**Comment by Roj4ck** [comment]
Since you're running this via docker this sounds like more of a docker / linux permission issue than a Deepvariant issue.   I personally haven't done it but later versions of Docker do allow you to run without sudo access.  Please take a look here https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo .  I would, however, additionally state that you want to make sure your account does full access to those folders / file as well.  I'll let the Deepvariant team also add in any other suggestions as well.

**Comment by PlatonB** [comment]
That works for me (Ubuntu 18.04.1-based OS with Docker 19.03.6): https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by gunjanbaid** [comment]
Thanks for the suggestion, @Roj4ck. @PlatonB I'll close this issue, but feel free to reopen if you have other questions.
