### ISSUE TITLE
Can WES and WGS sequencing data of the same person be merged and analyzed with --model_type=WGS?

### ISSUE THREAD

**Issue by chrausch** [google/deepvariant#338]
I have WGS data (about 200x) and WES data (about 1000x) of the same individual.
Ideally I would like to merge the 2 datasets and run DeepVariant with --model_type=WGS on the merged data and obtain one VCF file.

Or is the model behind "--model_type=WES" really a different machine learning model (ML) trained on real Exome data?
I could imagine that such a ML model would learn a slightly different sequencing error model specific for sequencing data derived from target enrichment (hybridization probes) as the ones used for WES.

Thank you for your advice.

**Setup**
  - Operating system: Ubuntu 18.04
  - DeepVariant version: r0.10
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: Illumina WGS and WES data

**Comment by MariaNattestad** [comment]
Since you already have 200X coverage of WGS data, the best quality variant calls would probably come from just taking the WGS data and running with that alone with `--model_type=WGS`. This is because the pileup images only fit up to 95 reads for each variant, so the 200X will already be downsampled during runtime to fit. The WES data will have some inherent biases due to the target enrichment process, so combining the datasets would carry its own potential issues. Luckily you don't need that since you have plenty of WGS data.

Also I just want to check that you are only doing germline variant calling, since in my experience people with high coverage are often looking for low-frequency variants. DeepVariant is built and trained for germline variant calling only, and it can only report heterozygous, homozygous reference, and homozygous alternate genotypes.

**Comment by chrausch** [comment]
Hi Maria,
thanks for your answer. I will thus not merge WGS and WES data, but analyze them separately instead. This way I can compare and have a look at the potential issues you mention. 
And thanks for checking: I am indeed looking at germline variant calling.

A question regarding the pileup images you mention that are downsampled during runtime to 95x:
Here (https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-details.md#updates-on-deepvariant-since-precisionfda-truth-challenge-and-biorxiv-preprint) it says: "_The biggest change was to move away from RGB-encoded (3-channel) pileup images and instead represent the aligned read data using a multi-channel tensor data layout. We currently represent the data as a 6-channel raw tensor in which we encode: ..._" Is the downsampling to 95x still applied in the new design?

thanks, Christian.

**Comment by MariaNattestad** [comment]
Sounds good!
Yes, we still call it a pileup "image", it is just in the form of a TensorFlow tensor with 6 channels instead of an RGB image, which was limited to 3 color channels plus opacity. The downsampling to 95x is still applied and has been in all versions of DeepVariant.

This blog post gives more detail on how the pileup images are structured: https://google.github.io/deepvariant/posts/2020-02-20-looking-through-deepvariants-eyes/

**Comment by gc00** [comment]
Hi Maria (@MariaNattestad),

Do you have a comparative analysis on models trained with larger values set [here](https://github.com/google/deepvariant/blob/master/deepvariant/dv_constants.py#L43-L44) for `PILEUP_DEFAULT_HEIGHT` allowing for larger values of coverage than 95?

https://github.com/google/deepvariant/blob/master/deepvariant/dv_constants.py#L43-L44

Thanks,
Paul

**Comment by pgrosu** [comment]
Hi Maria (@MariaNattestad),

Do you have a comparative analysis on models trained with larger values set [here](https://github.com/google/deepvariant/blob/master/deepvariant/dv_constants.py#L43-L44) for `PILEUP_DEFAULT_HEIGHT` allowing for larger values of coverage than 95?

https://github.com/google/deepvariant/blob/master/deepvariant/dv_constants.py#L43-L44

Thanks,
Paul

**Comment by pichuan** [comment]
Hi @pgrosu 

The default of `--pileup_image_height=100` was initially determined by the most common use case of Illumina WGS data.

In terms of tweaking pileup_image_height, there are 2 past experiments that I can recall right now:

## Illumina WES:
Before we released an Illumina WES model, I experimented with training a WES model with `--pileup_image_height=200`.  At the time (end of 2017), I observed that the Indel F1 dropped quite a bit when increasing the height, but helped SNP F1 a bit. This investigationwas why we didn’t change this default for the Illumina WES model release.

## PacBio:
In Nov 2019, I trained a model with `--pileup_image_height=75` to see if we can decrease runtime without too much accuracy tradeoff. At the time, my results were:

* Reducing height to 75 (from 100) reduces calling time to ~85% (from 3h20m to 2h50m)
* Accuracy (on case study chr20)
    - Indel F1: 0.983872 —> 0.982728
    - SNP F1: 0.998913 —> 0.998867

Based on feedback, we decided it’s not a high priority to continue. Because:
1. Amplicon will likely use the height=100
2. 30min is not a big bottleneck for them now.
