### ISSUE TITLE
Output for variants with zero coverage is hom ref instead of missing

### ISSUE THREAD

**Issue by edg1983** [google/deepvariant#346]
Hello,

I'm trying to apply deepvariant v1.0.0 to a small cohort to generate multi-sample VCF. I've followed the steps described in your tutorial on multi-sample calling, so:
1. generate single sample g.vcf with deepvariant
2. merge g.vcf using GLnexus

However, I'm confused by the output in the multi-sample VCF. Looking at the variants I've found several positions where one or more of the samples are reported as `0/0` genotype, but with DP = 0. In this case, I assume the position has no reads in the data and so I'm expecting a missing genotype (`./.`) not a hom ref. This error can really mess up segregation analysis.
Trying to understand what is going on, I've looked at the single g.vcf generated by deepvariant for some of this position and I've noticed that the errors seem related to variants output as a hom ref block with MIN_DP zero in the g.vcf file. See the following example:

**multi-sample VCF:**
```
chr1    72787   chr1_72787_C_T  C       T       18      .       AF=0.5;AQ=18    GT:DP:AD:GQ:PL:RNC      0/0:0:0,0:1:0,3,29:..   1/1:2:0,2:6:18,9,0:..
```
**g.vcf sample1:**
```
chr1    72121   .       A       <*>     0       .       END=73000       GT:GQ:MIN_DP:PL 0/0:1:0:0,3,29
```
**g.vcf sample2:**
```
chr1    72787   .       C       T,<*>   18.8    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:10:2:0,2,0:1,0:18,9,0,990,990,990
```

Instead, if the g.vcf line is like the one below the genotype is correctly reported as missing in the multi-sample VCF.
```
chr1    20595   .       A       <*>     0       .       END=20595       GT:GQ:MIN_DP:PL ./.:0:4:17,0,77
```

So a couple of questions:
1. Is this behavior expected for deepvariant or is it a kind of bug?
2. How to interpret a g.vcf block like the one above with MIN_DP zero? Does it mean that some of the positions in this block have actually non-zero coverage or all of them have zero? In the first case, I suggest splitting the block when a position has zero coverage; in the second case, it is probably better to output the block with `./.` genotype.
3. How can I interpret `0/0` genotypes with zero DP in the multi-sample VCF? Currently, I assume that the DP notation is correct and thus convert all these ones to missing genotypes. Or is it possible that some of them actually have reads covering the position? This latter case would be particularly problematic since I would not be able to safely distinguish between an actual home ref and a missing call due to zero coverage.
4. Is there any setting I can change in GLnexus to have positions with DP zero outputted as missing?

Thanks a lot!

**Comment by tedyun** [comment]
Hi Edoardo,

Thank you for filing this issue. This is an expected behavior in the current implementation of DeepVariant. As it is impractical & inefficient to represent each base position with hom. ref. calls in gVCF files, we consolidate multiple hom. ref. positions with similar GQ values into one gVCF block. A gVCF block with `MIN_DP=0` (but with positive GQ/PL values) will be created when the nearby hom. ref. positions also have very low GQ (but not all 0). Another thing that makes this problem more subtle is that we exclude lower quality from counting the DP.

We think it makes sense to separate out blocks with no coverage in gVCF records and set GT to `./.` as you suggested. We started internal discussion about it and started tracking the issue internally. We will be sure to give an update here whenever we have any update.

For your last question about GLnexus, I'm not aware of a GLnexus setting that can set DP zero outputs as missing. The only thing I can think of for now is adding an annotation for DP=0 calls using [bcftools](http://samtools.github.io/bcftools/bcftools.html), etc. and handling them separately in downstream analysis.

I hope this helps and please let us know if you have any follow up questions or comments. I'll keep this issue open until we have an update. Thank you.

Best,
Ted

**Comment by edg1983** [comment]
Hi Ted,
Thanks for your feedback. Just to be sure I've got this right. You confirm that variants with 0/0 genotype and zero DP in the merged VCF are actually positions with no reads in that sample and so can be set to missing?

**Comment by tedyun** [comment]
Hi Edoardo, in the current implementation, `DP=0` (which is used in variant records) will imply that there is no read covering that position, while `MIN_DP=0` (used in hom. ref. band in gVCF) does not necessarily imply that there is no read covering the reference band, due to consolidation of multiple hom.ref. records into one record for the reason stated in my previous response (as the name suggests, it means the *minimum* of DPs in all of the consolidated records were 0). Please also note that reads that don't satisfy the minimum mapping quality threshold (set to 5 by default [here](https://github.com/google/deepvariant/blob/r1.0/deepvariant/make_examples.py#L219)), don't count for DP/MIN_DP as far as I know.

Again, we agree with your suggestion about separating out the `DP=0` regions into a separate record and setting the genotype to `./.`.

The performance issue you mentioned is not expected as far as I know, and I asked my colleague to follow up on that aspect.

I hope this help and please let me know if I can help with anything else.

Best,
Ted

**Comment by pichuan** [comment]
Hi @edg1983 , I'll help with the runtime increase question. There are a few reasons I can think of that might have increased overall runtime between v0.9.0 and v1.0.0, but the magnitude of increase you're observing is not quite what I'd expected.

First, let's take a quick comparison on our GitHub documentation:
- https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-case-study.md :  82m+189m+36m = 307m
- https://github.com/google/deepvariant/blob/r1.0/docs/metrics.md : 89m+258m+84m = 431m

Before we talk about code changes, note that r0.9 was done on a 50x BAM ([see script](https://raw.githubusercontent.com/google/deepvariant/r0.9/scripts/run_wgs_case_study_docker.sh)), and in r1.0 we used a 35x BAM ([see script](https://raw.githubusercontent.com/google/deepvariant/r1.0/scripts/run_wgs_case_study_docker.sh)). The lower coverage BAM is one main reason why the `postprocess_variants` took more time (84m vs 36m).

There are a few known reasons why runtime would increase.
1. In [v1.0.0 release notes](https://github.com/google/deepvariant/releases/tag/v1.0.0), we mentioned that `--min_mapping_quality` is now set to 5 (previously 10). This would increase the number of reads being considered, as a result, increase the number of candidates generated. Which is why `make_examples` runtime might increase. And if there are more candidates, `call_variants` runtime can also increase.

2. In [v0.10.0 release notes](https://github.com/google/deepvariant/releases/tag/v0.10.0), we mentioned that we have turned off `--ws_use_window_selector_model` to improve accuracy but increased runtime too. 

All these being said, I am surprised by your observation "v0.9.0 takes 10-14h while v1.0.0 takes more than 24h per sample". If you can provide the following information, it'll be very helpful for us:

1. What is the runtime breakdown of the 3 steps on v0.9.0 and v1.0.0? This will help us understand which step (make_examples, call_variants, postprocess_variants) might be increasing the most.
2. On exactly the same BAM, just with different versions, how many lines are in your VCF and GVCF?
For example, here is what I have after running [the wgs script](https://raw.githubusercontent.com/google/deepvariant/r1.0/scripts/run_wgs_case_study_docker.sh)
```
$ zcat HG002.output.vcf.gz | grep -v '^#' | wc -l
7753721
$ zcat HG002.output.g.vcf.gz | grep -v '^#' | wc -l
91714977
```
And here is the breakdown of PASS/RefCall:
```
$ zcat HG002.output.vcf.gz | grep -v '^#' | cut -f 7 | sort | uniq -c
4845593 PASS
2908128 RefCall
```

**Comment by edg1983** [comment]
Hi. After your comment I've repeated the test using the same input BAM (18X WGS sequenced with 150bp paired reads), running deepvar 0.9.0 and 1.0.0 with singularity v.3.5.2-1.1.el7 and exactly the same command (`--num_shards=10`). The running time is now almost the same, much longer than my old test with deepvar 0.9.0 on a 30X WGS. 

Below I've reported running time in min for make_example+call_variants+post_process:
- **v0.9.0**: 290+1494+281 = 2065min (~34h)
- **v1.0.0**: 335+1487+300 = 2122min (~35h)
- **v0.9.0 OLD TEST ON 30X WGS**: 198+456+82 = 736min (~12h)

The number of variants for the 3 runs are:
- **v0.9.0**: 531371190 g.vcf.gz; 10784757 vcf.gz (4552313 PASS, 6232444 RefCall)
- **v1.0.0**: 547491396 g.vcf.gz; 11892262 vcf.gz (4619350 PASS, 7272912 RefCall)
- **v0.9.0 OLD TEST ON 30X WGS**: 213244705 g.vcf.gz; 9096927 vcf.gz (4661618 PASS,  4435309 RefCall)

So, the first question is: are these running times expected? The running times you reported are much shorter it seems. Can it be that the running time increased from 12 to 34h just because of the lower coverage?  

The exact command I've used is below (it is the same for v1.0.0 but using the corresponding singularity image):
```
singularity exec \
--bind /data/ref/genomes/GRCh38:/genomes \
--bind /data/projects/HICF2_project/BAM:/bam_files \
/well/gel/HICF2/software/singularity/deepvariant-0.9.0.simg \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS --ref="/genomes/GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set.fna" \
--reads="/bam_files/${bamfile}" \
--output_vcf="VCF/${sampleID}.vcf.gz" \
--output_gvcf="VCF/${sampleID}.g.vcf.gz" \
--intermediate_results_dir="tmp_data" \
--num_shards=10
```

I've uploaded the log files from the 3 runs if you want to take a look:
[deepvar_0.9.0_oldrun.log](https://github.com/google/deepvariant/files/5281370/deepvar_0.9.0_oldrun.log)
[deepvar_1.0.0.log](https://github.com/google/deepvariant/files/5281371/deepvar_1.0.0.log)
[deepvar_0.9.0.log](https://github.com/google/deepvariant/files/5281372/deepvar_0.9.0.log)

Thanks for your support!

**Comment by pichuan** [comment]
Thanks @edg1983 
Looking at your numbers.

Comparing **v0.9.0** (slower)  and **v0.9.0 OLD TEST ON 30X WGS**
1. make_examples runtime: 290/198 = about 1.5 times
2. #entries in VCF: 10784757/9096927 = about 1.2 times entries
3. #entries in gVCF: 531371190/213244705 = about 2.5 times
4. call_variants runtime: 1494/456 = about 3.3 times
5. postprocess_variants runtime: 281/82 = about 3.4 times

My observations:
(1) gVCF entries is higher, which is not unexpected on lower coverage BAMs.
(2) The increase on call_variants runtime should be linear to the number of examples presented to the classifier, which should be roughly similar to the #entries in VCF. One reason this could change significantly is: if you end up having too many multi-allelic entries. I guess it is possible with lower coverage files, but I'm still surprised by this. I'll see if I can find some internal benchmarking runs to see if we observe this. This one is currently a surprise to me.
(3) The increase on postprocess_variants runtime - We know that lower coverage will increase gVCF entries and postprocess_variants runtime. Given that the #entries in gVCF has increased to 2.5 times, this number might not be unexpected here.

**Comment by gunjanbaid** [comment]
@edg1983 one other possibility: was the run corresponding to `deepvar_0.9.0_oldrun.log` on different hardware than the other two runs? If you are running the other two runs on older hardware that does not support AVX2 or AVX512 instructions, runtime will be noticeably slower because the code will not be able to take advantage of TensorFlow MKL optimizations.

**Comment by pichuan** [comment]
And an follow up on gVCF file size, (thanks to @tedyun for reminding me of the flag):

There is a flag in `gvcf_gq_binsize` in make_examples that you can set to reduce the size of gVCF file, the tradeoff being the gVCF file size & runtime vs. more accurate representation of GQ in each hom. ref. site.

**Comment by edg1983** [comment]
I want to give you an update on the situation. Following your suggestions, I've discussed with the system administrators and I found out that some older nodes on the cluster do not have AVX2 or AVX512 instructions. I've now completed a test running on nodes supporting those and the running time on the same BAM file is ~14h (290+326+134). So I've discussed with them and found a way to allocate all deepvar jobs to the new nodes supporting the AVX instruction. 

Thanks for your support!

**Comment by tedyun** [comment]
Hi Edoardo,

I'm glad to hear that you got the runtime issue sorted out! I'll keep this ticket open for your original issue about hom. ref. calls in zero coverage regions. Please let us know if you have any other issues/questions.

Thanks,
Ted
