### ISSUE TITLE
Deep variant for tumor derived CCS data

### ISSUE THREAD

**Issue by ndesar** [google/deepvariant#352]
Deepvariant 1.0 is still not considering polyploid polyclonal tumor data analysis in consideration. Anything in the pipeline or any plug in?

**Setup**
  - Operating system:
  - DeepVariant version:
  - Installation method (Docker, built from source, etc.):
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by AndrewCarroll** [comment]
Hi @ndesar 

We do have a prototype implementation for somatic calling, which can take a tumor and normal BAM and call subclonal variants. However, we don't yet have enough confidence in the available truth sets, and that they come from a diverse enough sampling of cancers with mutational profiles, for us be certain in releasing something of high quality.

From the title of your issue, is it correct that you have PacBio HiFi data for a tumor line? This is interesting, we're keeping an eye on adoption of HiFi data for cancer sequencing, since it has potential to improve some of the truth sets.

For the present, we don't have a widely released method you can use for somatic calling, and this isn't on the immediate roadmap. However, hopefully in the medium-to-long term this is an area we'll be able to get to.

**Comment by wangjiawen2013** [comment]
Have you tried DeepSSV, a somatic small variants caller ?
https://www.biorxiv.org/content/10.1101/555680v1.full.pdf
