### ISSUE TITLE
Unsolved References/Imports Using The Provided Docker

### ISSUE THREAD

**Issue by yonatansc97** [google/deepvariant#359]
**Issue**
I am using the docker you provided, while working on a remote machine.
Using Pycharm Professional's Services tab, I configured my interpreter to run the code I have on my local clone of the entire git. 
I am trying to run the "make_examples.py" file line-by-line, to understand it better. The entire clone is on my remote machine, and it runs with the docker container's interpreter. When I debug the code, there are many unresolved references. 
Some examples are:
`from third_party.nucleus.protos import reads_pb2`
`from deepvariant.protos import deepvariant_pb2`
`from deepvariant.python import pileup_image_native`
`from deepvariant.protos import deepvariant_pb2`
`from deepvariant.python import allelecounter`
`from third_party.nucleus.io.python import hts_verbose`
...
I looked for these files, and they aren't there.
I understand there is something very basic that I misunderstand, so thanks in advance for your patience!

**Setup**
  - Operating system: Ubuntu 18.04
  - DeepVariant version: 1.0.0
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: irrelevant

**Does the quick start test work on your system?**
I have succeeded in running the quick start example on the remote machine, through the terminal.

**Comment by MariaNattestad** [comment]
Hi @yonatansc97 

Those imports you listed have something in common: they are in C++ (or protos) and therefore need to be compiled first.
Inside the docker container, we have these already compiled into the binaries like `/opt/deepvariant/bin/make_examples`, while `make_examples.py` is the source, but it won't work without compiling its C++ dependencies.

I don't know how to make this work with your special setup, but perhaps the documentation on building from source will help get you started: https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-build-test.md

I hope that helps at least point you in the right direction!
Maria

**Comment by yonatansc97** [comment]
Thank you for the answer @MariaNattestad !

**Comment by yonatansc97** [comment]
Hi again :)
I tried running the build-prereq / run-prereq. Right now they fail on my machine. However, I feel like building it from scratch on kind of makes the docker useless (which I would like to make use of). 
Is it possible that in order to have the entire code files (without the python packages to run it), I can perhaps run only certain lines in the build-prereq?

**Comment by MariaNattestad** [comment]
Docker is very useful for running DeepVariant, but usually people who want to experiment with making changes in DeepVariant will build from source, and then they can always package that up into a Docker image afterwards.

We don't really have much ability to support you in running DeepVariant line-by-line, since that's not how it's meant to be used. But you are of course welcome to experiment with it anyway, it just means we don't have bandwidth to help you get it working.

I'll leave you with one resource you may find interesting: this blog post by Jason Chin at DNAnexus: https://blog.dnanexus.com/2019-02-19-deep-dive-into-deepvariant/

Good luck with your explorations!
Maria

**Comment by yonatansc97** [comment]
Ok, Thanks!
