### ISSUE TITLE
Is the TPU training case-study deprecated?

### ISSUE THREAD

**Issue by anands-repo** [google/deepvariant#376]
In v0.9 there is a TPU training case-study. Are the tpu-based options/setup given there not valid from v0.10 onwards?

**Comment by pichuan** [comment]
Hi @anands-repo 
Our codebase still supports TPU like before!
We decided to change our training tutorial to use GPU and CPU because it's a more general setting. Even though our code still supports TPU, we think it's better to simplify our tutorial.
If you encounter any issues when using DeepVariant with TPU, and if you suspect the issue might be in our codebase, please let us know.
(Btw, out of curiosity : have you been training DeepVariant model with TPUs? If you are using that, I would actually really love to hear your feedback. I didn't think we have that many external users with this functionality yet.)

**Comment by anands-repo** [comment]
@pichuan Thanks for confirming!

I tried GPU-based training, but since the codebase currently doesn't support multi-GPU runs, it may not be efficient for me to use GPU-based training. Hence I am looking into using TPUs for the same. I will gladly provide feedback once I am able to do it.

**Comment by pichuan** [comment]
Sounds good. You might also want to refer to the latest TPU documentation to see if anything changed, but overall it should still work. If you have any questions, feel free to open another issue.
