### ISSUE TITLE
Understanding insertions in DeepVariant

### ISSUE THREAD

**Issue by yonatansc97** [google/deepvariant#379]
Hi,
I am trying to deepen my understanding of DeepVariant (pun unintended), similar to what is written here (https://github.com/google/deepvariant/issues/306).
If I understand the discussion above correctly, whenever there is an insertion, the insertion itself will not be present in the pileup image, and the preceding pixel will be zero'd out.

So if we have a cigar 6M3I1M such as:
ref: ACGCCT T
alt: ACGCCTCCCT
this will actually be represented in the pileup as:
ref: ACGCCTT
alt: ACGCC0T

I visualized the examples you provided in testdata, and on the 3rd example [fig1] (chr20:10001436-10001436) there is a case in which an insertion occurs right after the variant's position. Following the above logic, the center column should be zero'd out. However, it seems to not be the case. What happens instead is that the last channels center column indicates a diversion from the reference genome (a pixel is 'lit' up). So it looks like the bam read is a basic SNP, even though it actually is a length 5 insertion (the bam is an indel and the variant in the vcf is an snp).
In fact, I haven't seen any case of zero'd out pixels which aren't deletions.
Some options are:

1. Did I not understand the insertions logic correctly? Whas it changed since the above git issue in April?
2. Am I possibly working with the wrong files? I use the NA12878_S1.chr20.10_10p1mb.bam/.bai bam file with the golden.training_examples.tfrecord for your examples.
Sorry for the long post, I hope I was clear but let me know if more information/explanations are needed.
![fig1](https://user-images.githubusercontent.com/52149642/98434660-6ab2e380-20da-11eb-887c-4683bb759d1c.png)

**Comment by jumpyknight** [comment]
Hi, glad to see my issue is helping you.
Since DeepVariant performs local-realignment on indel sites, it is possible that DeepVarianat sees a variant site differently with CIGAR in BAM file.As shown in channel 6 of this site, there's another site very close, sometimes DeepVariant treats an insertion-deletion haplotype as an snp-snp one.
It would be helpful if you can provide the variant information along with the referred example.

**Comment by yonatansc97** [comment]
Thanks for the comment, @jumpyknight 

What you suggest is interesting, but do you think it is plausible even if the insertion is of length 5? If that was the case, I would have expected to have more pixels 'lit up' as snps, or more pixeld 'darkened' as insertions, right after the position at which the insertion took place. However, no such behaviour takes place (referring again to the 6th channel).

I'm not sure what infomation is relevant here so I'll post a bunch of stuff:

1. The variant: as I said it is at chr20-10001435, it is labeled to be a simple SNP, hom-alt 1/1.
2. The bam-file read I mentioned: 

- Starts at: 10001358
- Cigar: 78M, 5I, 18M

That means that we have
10001358 ... 10001435 X  X  X  X  X  10001436 ... 10001453
        M     ...        M       I   I    I   I   I         M        ...  M
Where M indicated Match and I indicates Insertion

- It is the forward read, with mapping quality 60, 
- Has the following tags: [(RG, NA12878), (XT, U), (NM, 5), (SM, 37), (AM, 37), (X0, 1), (X1, 0), (XM, 0), (XO, 1), (XG, 5), (MD, 96)]

**Comment by AndrewCarroll** [comment]
Hi @yonatansc97 

In the default WGS and exome models, DeepVariant does not expand the content of insertion sequences. Instead, it represents them with a character marker that indicates that an insertion is present at the position. To a human, this visually looks like a SNP in the pileup, but the machine learning model can easily distinguish this from a SNP event.

This representation is necessary in order to keep the pileup at a consistent width. The information of the content of the insertion is also implicitly present in the 5th channel (supports variant) which only gets a value of 255 with the read when the insertion sequence matches the event to be called.

The representation is in some ways sub-optimal, because in some cases information is lost in the presentation to the network. We have developed an additional process, which aligns reads to the ALT allele as well, which expands insertion sequences and makes the full sequence of ALT insertion events visible. This improves accuracy for calling variants in PacBio HiFi data and Oxford Nanopore data, and is defaulted to on in those models. 

The flag for this option is: --alt_aligned_pileup, which can have the values: --alt_aligned_pileup=diff_channels and --alt_aligned_pileup=rows. 

From our benchmarks, the --alt_aligned_pileup flag did increase accuracy in Illumina WGS and exome models, but only marginally. Since this also somewhat increases the compute cost, we do not use this option in Illumina WGS and exome models.

We discuss this feature in more detail in our [blog on DeepVariant v1.0](https://ai.googleblog.com/2020/09/improving-accuracy-of-genomic-analysis.html)

**Comment by yonatansc97** [comment]
Thanks @AndrewCarroll 
I think I understand the encoding better now.
