### ISSUE TITLE
Information about pre-trained PacBio models in v1.0.0

### ISSUE THREAD

**Issue by umahsn** [google/deepvariant#381]
Hi, is it possible to get some information regarding training of default PacBio models in v1.0.0? Specifically,

1. What genomes were used in training?
2. What was the source of BAM or FASTQ files of genomes used for training, and are they publicly available?
3. What ground truth variant call set was used for training? If GIAB benchmark variants were used, then which version was used?

I see this information is available [here ](https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-details-training-data.md)for Illumina models but not for PacBio. Also, can you please tell us which is the latest PacBio model trained on v3.3.2 of GIAB benchmark variant calls?

**Comment by AndrewCarroll** [comment]
Hi @umahsn

1. Training data comes from: the Human Pangenome Reference Consortium, [linked in this GitHub repo](https://github.com/human-pangenomics/HG002_Data_Freeze_v1.0). This includes HiFi sequencing for HG003 and HG004 which we contributed. It also includes data available on the [Genome in a Bottle FTP](ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/) in the CCS folders for individuals.

2. Most of these datasets are available as FASTQ files. These are mapped with pbmm2 using the default parameters for HiFi.

3. For HG002 and HG004, we use v4.2 truth set. For the other samples, we use the v3.3.2 truth set.

For HG001, HG005, HG006, and HG007, the truth set used is still v3.3.2 for training, since we do not yet have v4.2 for these samples.

**Comment by umahsn** [comment]
Thank you. I want to use a PacBio model trained on v3.3.2 benchmark variants. I assumed that the following model:  deepvariant/models/DeepVariant/0.9.0/DeepVariant-inception_v3-0.9.0+data-pacbio_standard from DeepVariant bucket released in 2019 is trained on v3.3.2. However, when I run this model in call_variants using examples created by make_examples from DeepVariant v1.0.0, I get the following error:

`ValueError: The number of channels in examples and checkpoint should match, but the checkpoint has 6 channels while the examples have 8.`

Does this mean this model is not compatible with DeepVariant v1.0.0? If I recreate examples with 6 channels using DeepVariant v0.9, will that have a significant drop in accuracy? Also, is there a trained model on v3.3.2 of benchmark variants that is compatible with 8 channels?

**Comment by AndrewCarroll** [comment]
DeepVariant v1.0 includes two additional channels which align reads to the ALT sequences (with the channels being different when more than one ALT allele is present). 

Even if the model shapes between versions are compatible, it is not a good idea to apply the model from one version with the machinery of another. This is because the training process for each model uses the machinery of that same version.

I am not sure I understand the reason to use a model trained on only the v3.3.2 examples? The v4.2 truth set is more comprehensive and correct. It would be better to use chromsome20, which is always fully withheld from all training as a benchmark. Starting from the next release, we will fully withhold HG003 from all PacBio training.

**Comment by umahsn** [comment]
Thank you, I agree with you about v4.2 being more comprehensive and correct. However, the reason why I am interested in a model trained on v3.3.2 is because I wanted to test DeepVariant's performance on v4.2 benchmark variants, for which it would be better to use a model that was not already trained on v4.2 benchmark variants. Just to get final clarification, PacBio model in the current v.1.0.0 release is trained on chr1-22 (except chr20 which is withheld) of all three Ashkenazim trio genomes, or just HG002 and HG004?

**Comment by AndrewCarroll** [comment]
In the current release, training occurs on chr1-19 using the v3.3.2 benchmark set for HG001, HG005-HG006 using BAM files mapped to GRCh37 (it's important to use GRCh37 when benchmarking with v3.3.2 as there are liftover artifacts on GRCh38 since v3.3.2 was not constructed on this truth set.

v4.2 regions are used in training with HG002-HG004 in the current version with GRCh38. With the next version, we plan to fully withhold HG003 from training for all data types.

chr20 is never used for training or model selection or anything that would influence model performance. It is a fully held-out test set.

chr21 and chr22 are not used for training, but the performance on chr21 and chr22 are used in a tune set that identifies at what checkpoint to select the model.

**Comment by umahsn** [comment]
Great, thank you!
