### ISSUE TITLE
(TRAINING) model-ckpt-0 shows low accuracy even when loaded from a previous checkpoint

### ISSUE THREAD

**Issue by anands-repo** [google/deepvariant#383]
I ran training for a number of epochs and obtained a model checkpoint (lets call it `checkpoint-first`) with accuracy > 0.99 (F1/All). Then I launched training again with `--start_from_checkpoint=checkpoint-first`

I expected `model-ckpt-0` for the second training run to show the same high accuracy as `checkpoint-first`. But it shows very low accuracy instead (F1/All is 0.85 or so). However the next checkpoint after `model-ckpt-0` (lets call it `model-ckpt-N`) shows high accuracy.

Does this mean `model-ckpt-0` is dumped before loading parameters from `checkpoint-first`, and `model-ckpt-N` is the first checkpoint I should be looking at for meaningful results for the second training run?

I used Google Cloud TPU for both training runs.

Thanks!

**Comment by AndrewCarroll** [comment]
Hi @anands-repo 

This is something that we observe in training as well, and has also been reported by other users - [see this GitHub issue](https://github.com/google/deepvariant/issues/185) for deeper discussion

In short, this occurs because not all variables are loaded when warmstarting a model. Retraining does quickly re-learn, but this is the reason for the initial drop. You should still be able to train models to high accuracy, despite this phenomenon.

**Comment by anands-repo** [comment]
Thanks for the explanation!
