### ISSUE TITLE
Missed variant - Illumina WGS

### ISSUE THREAD

**Issue by gevro** [google/deepvariant#388]
Hi, The attached variant was missed. It was detected in 39 / 39 reads (100%) at the locus, and all reads have high MAPQ. Very strange, but warrants an explanation. It was not even a RefCall variant. Appreciate any advice.
<img width="943" alt="Screen Shot 2020-11-24 at 4 31 05 PM" src="https://user-images.githubusercontent.com/47928628/100153865-bd2e2700-2e72-11eb-9af1-c182b3fd57ee.png">

**Comment by gevro** [comment]
Here it is: https://www.dropbox.com/s/0jw1dmmtxxikgxv/sample.bam?dl=0
Aligned to CHM13: https://github.com/nanopore-wgs-consortium/CHM13
https://s3.amazonaws.com/nanopore-human-wgs/chm13/assemblies/chm13.draft_v1.0.fasta.gz

**Comment by AndrewCarroll** [comment]
Thank you, we're taking a look at the example and expect to have feedback relatively soon (with some delay for holidays in the US).

**Comment by akolesnikov** [comment]
We tried to reproduce the problem with the sample.bam. From the original post it was not obvious what variant was missing. I assume it is the one at position chr3:76,275,581.
Here is what we get when running with all default parameters:
```
chr3    76275186        .       A       C       64.3    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:62:43:0,43:1:64,66,0
chr3    76275271        .       CT      C       60.7    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:59:37:0,36:0.972973:60,64,0
chr3    76275581        .       C       CAGTGCCACTCTCATTTTACAAGTGGGTAACTCAGGGTGATGGTGAGT        0.1     RefCall .       GT:GQ:DP:AD:VAF:PL      ./.:19:38:0,12:0.315789:0,34,18
chr3    76275753        .       T       A       66.8    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:61:41:0,41:1:66,62,0
chr3    76275830        .       T       C       96.7    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:67:39:0,39:1:96,67,0
chr3    76275879        .       A       C       40.9    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:41:34:21,13:0.382353:40,0,60
```

The variant at position chr3:76,275,581 is an insertion which doesn't match the original alignment in sample.bam. That happened  as a result of a local realignment (which is a part of a default make_example workflow). The image below shows the original (top) and realigned (bottom) reads for this region.

![image](https://user-images.githubusercontent.com/1168691/100527570-8dd82c80-3188-11eb-9880-740b724fef43.png)

We tried to run make_examples without local realignement `--norealign_reads` flag. In that case all 6 variants are reported as expected.

```
chr3    76275186        .       A       C       64.2    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:62:43:0,43:1:64,66,0
chr3    76275271        .       CT      C       61.2    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:60:36:0,36:1:61,65,0
chr3    76275581        .       C       T       62.2    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:58:38:0,38:1:62,60,0
chr3    76275753        .       T       A       68.2    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:63:40:0,40:1:68,64,0
chr3    76275830        .       T       C       99      PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:67:39:0,39:1:99,67,0
chr3    76275879        .       A       C       40.8    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:41:34:21,13:0.382353:40,0,60
```

It is not recommenced to run DeepVariant with Illumna data with `--norealign_reads` since accuracy drops significantly when local realignment is skipped. In most of the cases (if not all) local realignment leads to the most accurate reads alignment. In this particular case it looks like the given set of reads represents an insertion at position chr3:76275581.

**Comment by gevro** [comment]
Thanks so much! I think I understand the issue now, but Deepvariant is still giving a wrong answer.
You can see that this particular location in the genome has a tandem repeat of 6 copies of a 47 bp sequence:
https://genome.ucsc.edu/cgi-bin/hgc?hgsid=960400993_qiSzxsvvUkaPrDYeYJ2KhGLAK2ay&c=chr3&l=76220845&r=76221817&o=76221234&t=76221509&g=simpleRepeat&i=trf

But I actually have long PacBio reads for this reason, with the zmw consensus sequence:
TGAGCTTAATCATAGAACATGGTAATACTAGGAGACATCATGAAGGATCCCTGTGTTGTAGATATACTCTTCTTTACTTCCATTGAGAAGTAGTAGTTCAATTTCCCCAGGTAGTCTGAATCAATAACCCCAGGCAATATTGACTGTTTCTGTGGTGAAAGCATTCCTCCATCTAGAACTAAGTCCTCTTGCCCAACAGAAGATAAAGTCATGAGCATGGGAAGCAAAAATTTTGCTAGTGGGTAACTCAGGGTGATGGTGAGTAGTGCCACTCTCATTTTACAAGTGGGTAACTCAGGGTGATGGTGAGCAGTGCCACTCTCATTTTACAAGTGGGTAACTCAGGGTGATGGTGAGTAGTGCCACTCTCATTTTACAAGTGGGTAACTCAGGGTGATGGTGAGCAGTGCCCCTCTCATTTTACAAGTGGGTAACTCAGGGTGACGGTGAGCAGTGCCACTCTCATTTTACAAGTAACTCAGGGTGATGGTGAGCAGTGCCACTCTCATTTTCCACGCTTTGATTCCTGAACCCATTAATTGTGGCTGTTGATGAAACTACTATATGTTGGAAACTGCTTCAGAGAATATACAACCTTCTGCAGAACCTTGGCCCAGCTGTGTAAGGTATTGCGATCTAGCTGGTACTGTAACTGAATTCAAAAGACCCTTTTATCATTTTTATCAAGTTAGCTGCTTCTGGATGATGGGGAACATGGTAAGACCGATGGACTTCATGACCATGAGCCCATTGCCACACTTTTTTGTCTTTGAGGTGAGTTCCTTGATCAGAAGCAATGCTGTATTTAATACTGTGCCTGTGGATAAGACATTTTATAAGTCCACGGATGGTAGTTTCGGTGGAAGCATTGCACCCACGGAAGACAAATCCATAACCTGAGAAGGGTCTATTCCAATAAGCACAAAATGCTGCCACTTCCATAGTGGAAGCAGTCTAATGTAGATAAACTGCCACTAGGTAGCTGGCTGATCACCCTGGGGAATAATGCCAAATGGGATCACAATGTGGTCTCTACTGCTGGCAGATTGTATAATCTGCCAGTGGTGGCCATAGCTAGGTCAGCCTTGGTGAGTGGAAACCTATGTTGCTGAGTGCATGCATAACCTTCATCCCTGCCACCATGTCCACCTGTTACTGGTGGAATGTATCTGAGCCACGTGGCACCAAAACACGTTACCAGTGGCAAATTGGTATGGGTTTGCAGCAACTTCAGTTCTTGCCTCCTCAGAAGAAAGAATCTGACTGAGAGGCATAAGGTAGAAGGAGGGGCTGAGGCAAGTTTTAGAGCAGGAGTGAATGTTTATTTAAAAAGCCTTAGAGCAGGAATGAAAGGAAGGAAAGAAAGTATACTTGGAAGAGGGCCAAGTGGGTGACTTGAAAGACAAGTGTACATGTTGACCTTGTGACTAGGCTTATACGTTGGCATAATTCCAGGGTCTTGTGTCACTTCTCCCAACCCGCCCAACCCTTGAGATCTTATTGGGAAGCTGCTGATAACCAGTTTTAGGTATTTTCTATCCAGCAGGAGACTGCCTTTCCCTGGCACTGTCTGTGACCAATTATTACTTTAGAAAGACAGTTAACAACCATCTGACCATCACCTGATGGTGCCTGACATTCCTGGTGTGTGTGGGTGGGGGAGAGCCCTCTCCTACCCGGCTCATACCAGACTACTATAACAGATCCATGTCAATAAATTCAGACTGATCCAAGTTTATGTTTGTTTCACCATTATCCCACACTTTTTTTTTTTCAGATGGAGTCTCCTTCTGTCGCCCACGCTGGGGTGCAGTGGCATGATCTGGGCTCACTGCAACA

You can see that this maps all the way across this tandem repeat, and there is definitely not an insertion.

So it looks like the local realignment if falsely calling an insertion instead of an SNV.

I would think that local realignment has a higher penalty for large insertions than one SNV, so I'm not sure why local realignment settled on a large insertion?

**Comment by akolesnikov** [comment]
Local realignment first builds a DeBruijn graph by aligning all read k-mers. There is a graph output from make_examples (I didn't check it) which can show how the final graph looks like. In this particular case most likely graph was build with multiple haplotypes: with insertion and with a SNP. Then, when reads are realigned, they are realigned to haplotypes first. Most likely reads were better aligned to the insertion haplotype. Most likely reads could be aligned to the insertion haplotype with zero mismatches. That's why the final alignment was chosen like that.

**Comment by gevro** [comment]
Ok thank you for explaining.
