### ISSUE TITLE
conda install dv without model PACBIO

### ISSUE THREAD

**Issue by bitezhu** [google/deepvariant#395]
Dear Authors,
I just install deepvariant using conda and prepare to test the software with HiFi data. I noticed in the recently published DipAsm [package](https://github.com/shilpagarg/DipAsm) the parameters 'model_type' was set as 'PACBIO' in 'dv.sh' file, but there are only two options supplied in conda-deepvariant(wgs & wes). Since the alleged HiFidata base accuracy is very close to Illumina data,  I wonder can I use wgs model for now?  

Thanks!

**Comment by MariaNattestad** [comment]
Hi @bitezhu 

No, we don't recommend using the WGS model for PacBio data.

The conda-deepvariant package is a community contribution by @chapmanb and is not maintained directly by the DeepVariant team -- we are not experts on Conda, unfortunately.

William Rowell of PacBio contributed a case study that uses Conda, so you may find this helpful: https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-pacbio-model-case-study.md

Otherwise we recommend using Docker or Singularity (or one of the external solutions) to run DeepVariant.

If you have trouble running DipAsm because of this, it might be worth asking them about it directly.

Maria

**Comment by bitezhu** [comment]
> 
> 
> Hi @bitezhu
> 
> No, we don't recommend using the WGS model for PacBio data.
> 
> The conda-deepvariant package is a community contribution by @chapmanb and is not maintained directly by the DeepVariant team -- we are not experts on Conda, unfortunately.
> 
> William Rowell of PacBio contributed a case study that uses Conda, so you may find this helpful: https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-pacbio-model-case-study.md
> 
> Otherwise we recommend using Docker or Singularity (or one of the external solutions) to run DeepVariant.
> 
> If you have trouble running DipAsm because of this, it might be worth asking them about it directly.
> 
> Maria

Hi, Maria, thanks for your quick reply, it's very helpful!
