### ISSUE TITLE
parameters for low-coverage WGS?

### ISSUE THREAD

**Issue by avilella** [google/deepvariant#40]
What are the recommended parameters for low-coverage WGS? E.g. 2.5x-5x coverage of the human genome.

**Comment by depristo** [comment]
Hi @avilella,

That's a great question. We done some limited experiments with DeepVariant on lower coverage samples, but not at the 2.5x-5x range directly  (see attached image using an earlier version of DeepVariant than available on GitHub). 

Typically at such a low depth you need to follow a joint calling strategy like the 1000 Genomes project in order to get accurate allele discovery across many samples. If you are trying to do single sample calling from low coverage, despite the relatively low quality of calls you'll get due to the low coverage, you can certainly use DeepVariant. You really don't need to do anything different than for a deep WGS sample, so just follow the case study example command lines. 

There are some options in make_examples.py to manipulate the thresholds for generating candidate variant calls, but I'm not sure tweaking those will materially change the results. We'd be interested in hearing about your experiences with such low coverage samples if you do decide to try it out.

![screen shot 2018-01-17 at 11 14 01 am](https://user-images.githubusercontent.com/2250400/35062234-632d9068-fb78-11e7-84eb-66062ba79a43.png)

**Comment by avilella** [comment]
Thanks for the quick reply Mark. How about joint calling hundreds (100-200)
of low coverage WGS? Would that make a difference to DeepVariant?

**Comment by depristo** [comment]
I'm not sure what you mean. DeepVariant only does single sample calling. I'm really not sure what would happen if you tried to send in a merged BAM file containing hundreds of samples, but it could be an interesting experiment...
