### ISSUE TITLE
DeepVariant on corrected ONT in difficult to map regions

### ISSUE THREAD

**Issue by GuillaumeHolley** [google/deepvariant#403]
Hi,

So I am trying a little bit of a peculiar setup in which I am using ONT corrected reads (with [Ratatosk](https://github.com/DecodeGenetics/Ratatosk)) to call variants with DeepVariant 1.1 in difficult to map regions. For that, I am using the default PACBIO model which works pretty well in the non-difficult to map regions from what I've seen so far.
Now in the difficult to map regions, it is a little bit of a mixed bag which I am trying to understand. More specifically, I get variants in my GVCFs such as:
```
chr1	26740	.	C	<*>	0	.	END=26740	GT:GQ:MIN_DP:PL	./.:0:7:38,0,128
```
What I do not understand is that the PL values seems to clearly indicate 0/1, yet the genotype is undefined. Also, my understanding of GQ is that it is derived from the PL values as the difference between most likely and second most likely genotypes. Yet, the GQ is 0 in this example. 

I would really appreciate if you could shed some light on this.

Thank you very much.
Guillaume

**Comment by AndrewCarroll** [comment]
Hi @GuillaumeHolley 

This is a complicated issue, and though I've looked into it, I'm not 100% sure the following is correct, but I am reasonably confident:

DeepVariant is consists of some human-written heuristics which are used to identify positions that are candidate to be variant. Identified candidates are given to the neural network for classification. After this classification, another set of human-written heuristics converts the output probabilities of the network to VCF and gVCF entries. 

As part of this process, there are positions that were never proposed as candidates because they do not have enough support to reach the candidate generation threshold (for the PacBio defaults, this is at least 2 reads which support an alternate event with a minimum ALT fraction of 0.12, and where the reads used for the calculation have MAPQ>=5). When this threshold is not met, the site is always considered either a reference or a no-call, and human-written heuristics are used to make a determine the genotype quality of the position for binning in the gVCF. This logic is fairly simple, and can sometimes result in a calculation of HET being the most likely, even if DeepVariant's neural network never made a call. The GQ should be set to 0 in these cases. This occurs because we value the neural network's output much more highly, and would like only it to make calls. 

Hopefully this helps clarify what is going on here. The situation and explanation is complicated, so please feel free to ask further questions.

Thanks,
Andrew

**Comment by GuillaumeHolley** [comment]
Hi @AndrewCarroll,

Thank you very much for this detailed explanation, it is clear to me what is happening now. Unfortunately, this is rather problematic for my use case because I am processing a cohort (DeepVariant + GLnexus) and I impute the variants afterwards. The imputation is based on the PL values: If there are sites where some samples have an actual variant but most of the other samples have a no call (hence with a discrepancy between GQ and PLs), those sites will end up with a low imputation score. Since my reads are ONT corrected, I rely very much on the imputation scores as a post-filtering step to guarantee the quality of my set.

Guillaume

**Comment by tedyun** [comment]
Hi Guillaume,

Thank you for filing the issue and for the detailed explanation of your use case. I'd like to ask you some more questions to better understand the situation and to find a potential solution.

1. If we call the cohort you're processing with DeepVariant+GLnexus "cohort **X**", are you (a) using cohort **X** as a reference panel to impute another cohort **Y**, (b) using another cohort **Y** to impute your cohort **X**, or (c) using imputation software (e.g. Beagle) to re-genotype cohort **X** using the PL values in cohort **X** itself?
2. In the example case you mentioned ("some samples have an actual variant but most of the other samples have a no call"), the no calls in the other samples would imply we don't have enough evidence (in terms of coverage, read quality, mapping quality, etc.) to call the other samples either reference or variant. Would keeping that cohort-level variant desirable for your downstream application? If it is, is there any other type of filters you can use (other than the imputation score) to keep those records (e.g. maximum of GQs in all samples)?
3. Changing the no-call genotypes `./.` to the reference calls `0/0` is a relatively simple transformation (e.g. `bcftools +missing2ref`) that we use for some specific downstream applications. Would that help in your situation?

Thank you,
Ted

**Comment by GuillaumeHolley** [comment]
Hi @tedyun,

1. Use case here is (b): I am using another (much larger) cohort **Y** as a reference panel to impute my cohort **X**. 
2. I was actually thinking about simply deleting the GQ=0 sites from my GVCFs which seem to be the simpler solution. As you said, they don't provide any useful information. I just wanted to point out here that having those records in output might confuse downstream applications (i.e. imputation).
3. Unfortunately not. The problem is that our imputation system is exclusively based on the PL values and doesn't even read GT or GQ.

Thank you for your questions and suggestions.

Guillaume

**Comment by tedyun** [comment]
Thank you for clarification Guillaume - I think deleting `GQ = 0` sites is a reasonable solution if that works for your use case.

I agree with you that the current `GT`, `GQ`, `PL` values we emit in this particular case can be confusing. Please let us know if you have any suggestion on improving it for your downstream application (i.e. emitting different `PL` values) - I'll be sure to discuss it with my team.

Thank you,
Ted

**Comment by GuillaumeHolley** [comment]
Sorry for the delay, I appreciate your feedback in the matter. Closing the issue now.
