### ISSUE TITLE
Using the human-trained PacBio model for zebrafish data

### ISSUE THREAD

**Issue by YSchaefer** [google/deepvariant#415]
Dear developers,

we have generated reads from zebrafish (danio rerio) via PacBio HiFi sequencing and are now wondering whether or not we should attempt to re-train the human-trained PacBio model using existent zebrafish data or whether the human-trained PacBio model is precise enough to further process and analyse our data. We are aware that the human-trained models work well in other mammals but, as you know, studies in mosquitoes showed a significant increase in accuracy upon re-training from mosquito data. Of course, mammals are a lot more closely related to zebrafish than to mosquitoes, so we wanted to hear your opinion on the questions.

Thanks in advance for any help.

**Comment by danielecook** [comment]
We have previously highlighted two examples where DeepVariant has been applied in non-human organisms:

* [Rice](https://cloud.google.com/blog/products/data-analytics/analyzing-3024-rice-genomes-characterized-by-deepvariant) - are diploid and have similar variant density to humans with short-read data. The existing model worked well.
* [Mosquitos](https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/) - Used a retrained model to account for high variant density with short-read data.

With mosquitos we found that our human-trained model had high numbers of false positive calls. This is likely because in humans increased variant density is often caused by mismapping of similar genomic regions, leading DeepVariant to not call what are likely artifactual variants.

Fortunately, zebrafish appear to have similar SNP densities with humans, and the fact you are using PacBio HiFi reads may also reduce variant-density issues. However, there are a number of factors that may contribute to poor performance: The specific strains being experimented with, regions of the genome being evaluated, differences in structural variation, coverage, etc.

We would expect the DV human model to perform well in zebrafish, but it would be a good idea to estimate the error rate through a mendelian analysis, Sanger sequencing, or other methods to determine whether retraining is needed.

**Comment by YSchaefer** [comment]
Thank you for your elaborate answer!
