### ISSUE TITLE
Running DeepVariant without the reference genome

### ISSUE THREAD

**Issue by B10inform** [google/deepvariant#418]
**DeepVariant without Reference:**
I am trying to phase a diploid genome. But i don't have a reference genome. How would deepvariant work without the reference genome. (How to get the bam file?).

Any help would be great.

Thanks

**Comment by husamia** [comment]
You could assemble your reads first. Then align them to the consensus to get the bam. Then call variants with the consensus as your reference.

**Comment by danielecook** [comment]
@B10inform I'm not sure phasing is necessary for a haploid genome - because there is only one set of chromosomes the expectation is that identified variants are all already in phase.

Additionally, DeepVariant is designed to perform germline variant calling in diploid organisms, and requires a reference genome.

If the species you are working with does not have a reference genome than as @husamia suggested, this sounds like more of an assembly issue.

**Comment by B10inform** [comment]
@husamia @danielecook I meant a diploid genome (I have corrected the question). My plan is to obtain heterozygous SNP sites using deepvariant and than to phase the genome.

**Comment by danielecook** [comment]
Okay. You will still need a reference to use DeepVariant. I am closing this for now but if you have any further questions please feel free to reopen.
