### ISSUE TITLE
Limit number of CPUs used by DeepVariant

### ISSUE THREAD

**Issue by B1T0** [google/deepvariant#42]
I am using DeepVariant on a local machine with docker. When I start DeepVariant it uses all the CPU cores of my machine. Since I want to test DeepVariant without any time limitations and use the machine for other tasks I am curious whether it is possible to limit the number of threads or the number of CPUs used by DeepVariant.

**Comment by pgrosu** [comment]
Hi Tobi,

Since you're using Docker you can use the `--cpuset-cpus` CLI argument, or if you want to change it in Tensorflow for DeepVariant, that could be performed via the `Session` configuration - though that would require a small change in the code in `call_variants.py`:

```
config = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1, \
                        allow_soft_placement=True, device_count = {'CPU': 1})
session = tf.Session(config=config)
```

The change in `call_variants.py` would be in the following line of code, and can be changed based on your preference:

https://github.com/google/deepvariant/blob/r0.4/deepvariant/call_variants.py#L343

Hope it helps,
~p

**Comment by B1T0** [comment]
Thank you! Although while testing I will continue to use Docker, changing the code might become important to me 👍
