### ISSUE TITLE
Coverage depth over 100X

### ISSUE THREAD

**Issue by zwangwustl** [google/deepvariant#425]
This might not be an issue, but a question.

For dataset with sequencing depth >100X,  will the pre-trained model still be fully functional if we modify the tensor size following https://github.com/google/deepvariant/blob/r0.5/deepvariant/make_examples.py#L177? or the model has to be retrained after the modification?

Thank you,

Hugh

**Comment by gunjanbaid** [comment]
If the actual depth in a particular region is greater than the pileup image height, DeepVariant randomly downsamples reads until the image has been filled up. For the default DeepVariant models (height 100), an image can accommodate at most 95 reads in a given region (5 rows are reserved for the reference sequence). 

You may be able to successfully run our pretrained models with a different pileup image height (via `--pileup_image_height` in `make_examples.py`), depending on the new height. However, we generally do not recommend using different image heights at training and inference time. If you wish to use a different pileup image height, we recommend retraining a new model with images of that height. 

If you are working with extremely high coverage sequencing data for applications such as somatic sequencing, we recommend using a somatic caller instead of DeepVariant, which is a germline caller.

**Comment by MariaNattestad** [comment]
Closing now, but feel free to reopen if you have any more questions about this @zwangwustl
