### ISSUE TITLE
[no]realign_reads parameter for make_examples.py script

### ISSUE THREAD

**Issue by ajsa-nukovic** [google/deepvariant#437]
Hi,
I have a question regarding the use of the _**realign_reads**_ parameter for make_examples.py script. I am interested in running DeepVariant for PACBIO long reads data, and I don't want to realign reads before variant calling.

It is stated in the official description: _--[no]realign_reads: If True, locally realign reads before calling variants. Reads longer than 500 bp are never realigned.(default: 'true')_, but, in the description for running PACBIO data it is stated that **_Please note, that if you create your own script make_examples must be called with --norealign_reads flag for PacBio long reads._**

I am having trouble understanding the meaning of realign reads parameter, does the TRUE value realign or doesn't realign reads (basically is the parameter  NOrealign _reads, or realign reads)? Just want to clear things up so I don't waste time on long runs.

Thank you in advance! :)

**Comment by MariaNattestad** [comment]
The parameter (see the flags at the top of make_examples.py) is "realign_reads", and the way to set it to false is to pass `--norealign_reads`.

As stated in the usage you quoted above, reads longer than 500 bp are never realigned (this was added in v1.0). We still add `--norealign_reads` to PacBio runs, but if you forget to add it, there's likely not a big difference since very few pacbio reads will be below 500 bp.

If you want to try a shorter run before the full one to test your setup, you can always run DeepVariant all the way through with a small region, like `--regions "chr20:10,000,000-10,010,000"`, which should only take a few minutes.

**Comment by ajsa-nukovic** [comment]
Thanks a lot @MariaNattestad, I just thought that this one needed clarification.
