### ISSUE TITLE
Can I make a pileup image for the locus I want? ( using "make_examples")

### ISSUE THREAD

**Issue by gyuhee0928** [google/deepvariant#438]
Can I make a pileup image for the locus I want? ( using "make_examples")

I am trying to create pileup images using the command "make_examples".
By the way, "make_example" creates an image by selecting a location to create a pileup image from inside.

But I want to create pileup images of specific locations I want, is there any way?

I look forward to your reply.

**Comment by pichuan** [comment]
Hi @gyuhee0928 ,

By default, `make_examples` only creates pileup images for candidates that are created by our default candidate generation logic. After the examples are created, you can then visualize these examples by using `show_examples`: https://github.com/google/deepvariant/blob/r1.1/docs/show-examples.md

We do have a more advanced optional flag you can specify to use `vcf_candidate_importer` instead. It is a more advanced / experimental implementation , where we allow the users to provide a list of candidates that they want DeepVariant to call. You can see an example use case here: https://gist.github.com/pichuan/baba6ee9bd9890be2a45076a4934dd38

Another important use case for `vcf_candidate_importer` is [PEPPER-DeepVariant](https://github.com/kishwarshafin/pepper) which works on Oxford Nanopore long-read data.

We haven't written an official documentation for this, because there are many subtle details when providing the VCF file for --proposed_variants, otherwise it might confuse DeepVariant. You're welcome to give it a try, and feel free to ask questions here.

Our team might be a bit slower to answer specific questions on vcf_candidate_importer, but we can try our best to support.

Thanks!
