### ISSUE TITLE
Option to include invariant sites in output

### ISSUE THREAD

**Issue by elcortegano** [google/deepvariant#447]
For some uses, having a vcf file generated with information for all variant and invariant sites is useful. This was possible in other variant callers such as GATK.

Would it be possible to include such an option in deepvariant?

Thank you,
Eugenio

**Comment by AndrewCarroll** [comment]
Hi @elcortegano 

For this question, do you mean the ability to include statistics about reference confidence blocks in a GVCF format, or do you mean the ability to write a line in a VCF for every genome position (equivalent to the EMIT_ALL_SITES option of GATK).

If you mean a GVCF, this can be done in DeepVariant by adding the flag ```--output_gvcf=${GVCF_FILE} ``` to the executed command. We generally feel that this provides sufficient statistics and information about reference confidence.

We're hesitant to implement the one line per site feature due to how long it takes to write this amount of data and the file size. If this is the desire, is it tractable to get such statistics for support from tools like mosdepth or samtools?

Thanks,
Andrew

**Comment by elcortegano** [comment]
Hi Andrew, sorry for the delay,

I was aiming to get per nucleotide values of read depth, base and mapping qualities. I just come to check that this information can in fact be obtained from `samtools depth` and `samtools mpileup`, so I guess that will work for us.

Thank you for the feedback!
Eugenio
