### ISSUE TITLE
No class labeling output in variant calls by model trained with customized_classes_labeler

### ISSUE THREAD

**Issue by maryawood** [google/deepvariant#454]
Hello, 

I've been attempting to use the customized_classes_labeler to train a DeepVariant model. Specifically, I've been trying use the "callsets" field from the INFO field of a Genome In A Bottle VCF file. I've been working with NA12878, VCF/BED files available here: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/latest/GRCh38/

At first, I could not make training examples using this as that field is an integer, but by making a copy of the VCF where I changed that field to be a string, I was able to make examples (using the `--labeler algorithm`, `--customized_classes_labeler_info_field_name`, and `--customized_classes_labeler_classes_list` options) and train the model. However, when I use the best model from training to predict variants, this class label information is not included in the VCF file.

Am I misinterpreting how to use this customized class labeling? Any suggestions on how to incorporate this field into training and variant prediction? Thank you for your time!

**Comment by pichuan** [comment]
Hi @maryawood ,
`customized_classes_labeler` is an internal, experimental feature that we didn't provide documentation because we don't plan to provide support on it at this moment?

Can you provide a bit more detail on your problem definition - E..g, what are you trying to predict? 
You mentioned `callsets` in INFO -- does that mean you're trying to build a variant classifier that could predict these callsets values? If so, if you don't mind sharing, what's the problem that you're trying to solve? 

In general, DeepVariant utilizes a general classification algorithm (InceptionV3), however, our codebase serves a much more specialized purpose than InceptionV3, so the codebase does have a lot more hard-coded constraint. For example, the codebase assumes that there are 3 class: 0, 1, 2. [This blog post](https://google.github.io/deepvariant/posts/2020-02-20-looking-through-deepvariants-eyes/) has more details on what the inputs and outputs are for the InceptionV3 model.

It is possible to make enough changes to DeepVariant to get it work on other problems. But, if you're solving a very different problem from DeepVariant, I strongly suggest that you look into more general libraries - such as other image classification libraries in TensorFlow or other frameworks you like. If you need to process files such as VCFs, you can consider using [Nucleus](https://github.com/google/nucleus) which is what we used to process common genomics file formats in DeepVariant.

**Comment by maryawood** [comment]
Hi @pichuan, thanks for your response! Yes, ideally I'd like to build a variant classifier that could predict those callset values that I could then use as a proxy for the "confidence level" of a variant, i.e. a variant identified in multiple callsets might be more likely to be a "real" variant than one predicted in just one or two. 

Based on your description of the 3-class system in the codebase, would it theoretically be more feasible to feed the algorithm an edited VCF files that bins the callset values into three categories? (E.g. 0 = 1 callset, 1 = 2-4 callsets, 2 = >5 callsets)

Thank you for sharing the blog post and other resources, I'll take a look through those to try to learn more as well!
