### ISSUE TITLE
Recommendations regarding minimum values for advancing candidates in make_examples?

### ISSUE THREAD

**Issue by maryawood** [google/deepvariant#464]
Hello,

I was wondering if you had any recommendations as far as deviating from default values for options like `--min_base_quality`, `--min_mapping_quality`, `--vsc_min_count_snps`, etc. when running `make_examples` for retraining DeepVariant? How were the default values selected? Are there specific situations in which you would recommend changing them? 

Thank you for your help!

**Comment by pichuan** [comment]
Hi @maryawood ,
The default values in make_examples.py are our recommendations.
We do adjust things a bit based on different datatypes. For example, for PacBio, we changed --vsc_min_fraction_indels to 0.12:
https://github.com/google/deepvariant/blob/r1.1/scripts/run_deepvariant.py#L238
```
    special_args['vsc_min_fraction_indels'] = 0.12
```

For retraining, it will depend on your data. For example, using different mappers could end up with different expected distributions of the mapping quality, and you might want to adjust accordingly. Given that training is a more advanced topic and it highly depends on your data, I don't have a simple recipe for that.

One general rule is that you want to adjust these thresholds so that the candidate generation step is sensitive enough to propose the true variants, but not over sensitive that it ends up proposing too much noise.
