### ISSUE TITLE
Emit all sites in final VCF

### ISSUE THREAD

**Issue by kokyriakidis** [google/deepvariant#484]
Hi!

Is there a way to emit all sites in given regions (using a bed file) in the final VCF even if they are the same as reference? I want to use it in a pipeline in which any position not in the input VCF is assumed to be a "no call". Missing positions will not be interpreted as reference.

**Comment by MariaNattestad** [comment]
DeepVariant outputs all sites for which candidate variants are found, all of which had pileup images created and classified by the neural network. All candidates show up in the final VCF as `PASS` in the `FILTER` column if a het or hom-alt call was made, otherwise `RefCall`. And assuming you supply `--output_gvcf=` (see README for example) you'll get the gVCF as well. We do not have a way to output every single base on its own line.
