### ISSUE TITLE
Deepvariant output html file 

### ISSUE THREAD

**Issue by madhubioinfo** [google/deepvariant#493]
output html file of deepvariant allele frequency plot is bizarre-looking, I don't know how to read that or either I made a mistake while running deep variant 

Main genotypes plot Het (0/X) have one big peak and another one has
[output.visual_report.pdf](https://github.com/google/deepvariant/files/7499896/output.visual_report.pdf)
 a very small peak. I am having a hard time in understanding that 

Commands i used to run on my fungal dataset
~/minimap2-2.22_x64-linux/minimap2 --MD -ax map-hifi G1_cleaned.fasta G1_HiFi_reads.fastq -t 20 > G1_align.sam
samtools view -bS -@ 20 G1_align.sam | samtools sort -@ 20 -o G1_sorted.bam

        -v "/media/eniac/WD1/Hifi_Assemblies/mapping/":"/input" \
        -v "/media/eniac/WD1/Hifi_Assemblies/mapping/docker_out:/output" \
google/deepvariant:1.2.0 \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=/input/G1_cleaned.fasta \
--reads=/input/G1_HiFi_reads.fastq \
--output_vcf=/output/output.vcf \
--num_shards=4

Output file is attached

**Comment by MariaNattestad** [comment]
Is it possible the genome is tetraploid? The distribution looks just about perfectly like I would expect if there are 4 copies of each sequence, since the middle peaks of allele frequency are around 0.25 and 0.75. It's funny there isn't a peak at 0.5 then, so I'm curious what you think is going on here.

DeepVariant assumes the genome is diploid and is only trained on human autosomes, so I want to make sure you are aware of that when interpreting the results!

**Comment by AndrewCarroll** [comment]
Hi @madhubioinfo 

Maria's explanation is very interesting. If this is a plausible explanation, this is consistent with one grandparent being much more divergent from the reference genome. So most of the variants are contributed by this grandparent (and also explains why variants are either at 0.25 or 0.75. If this is a strain which does not undergo much recombination, it would also be consistent that one haploid genome is more diverged and this is either a tetraploid, or pooled sequencing with one sub-population at suspiciously close to 25% of the bulk size.

This is a very interesting observation. I am curious for your thoughts on this possibility.

**Comment by madhubioinfo** [comment]
Bit more background information. The genome used here is a haploid ( dikaryon ) fungi.  The assembled genome is from a Hifasm assembler. Haploid information is confirmed with flow cytometry experiment.

It's haploid for sure, and one of the two parental genotypes is known to represent 80% more abundant. So the question is why is the first peak not at the same level as the one at 80 given that they are heterozygous. 

So one parent is represent 0.8% of the genome present in the cell and the other is 0.2. We know that using molecular methods - one genotypes = 80% of the nuclei coexisting in the cell.

What we don't know is why do the bi-allelic freqs have different sizes.

It looks like there is a small shared portion of the frequencies that are shared, and the rest of the peak at 0.2 represents something else.

**Comment by AndrewCarroll** [comment]
Hi @madhubioinfo 

Thank you for the additional information. I'll propose one observation consistent with what you've provided. Of the two genomes, the one representing 20% of the net genomic content is much more diverged from the reference genome you are using in comparison to the other parent. The amount of divergence determines how many variants one would expect relative to a reference.

Since this plot represent the frequencies at a position, you should notice that if you look at absolute depth (DP) of the variant calls in the peak at 0.8 AF that they should be noticeably higher than the depth for the 0.2 AF peak.

If this hypothesis is correct, I would draw the following conclusions:

1. The less abundant genome is more diverged relative to the reference.
2. The more abundant genome has one 1,000 - 2,000 positions that differ from the reference. 
3. (Just eyeballing from the graph of absolute # of HET and HOM calls), among the positions that do vary in the less abundant parent, about half of those positions are shared with the more abundant parent.

Is it possible that your assembly is what ended up contributing most of the genomic content used in the assembly process, and this is why there is relatively less divergence in your sample relative to the reference?

**Comment by danielecook** [comment]
@madhubioinfo I will close this issue for now, but you are welcome to reopen it if you have any further questions.
