### ISSUE TITLE
how to find call_variants args

### ISSUE THREAD

**Issue by aude-darracq** [google/deepvariant#496]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.2/docs/FAQ.md**:

**Describe the issue:**
Hello,

I would like to run deepvariant on a very depth datasets (up to 10K reads at the same locus). When I am looking to the VCF, I can see depth per allele at max 1.5K. Is it possible to modify the call_variant parameter to allow more reads per bp position ?
I am also wondering how I can see the full list of parameters for call_variant (the allowed flags to put in "--call_variants_extra_args" like min_fraction_snps, min_fraction_indels, ...)

Thanks 

**Setup**
  - Operating system:CentOS
  - DeepVariant version:1.2
  - Installation method (Docker, built from source, etc.):docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)PacBio

**Comment by MariaNattestad** [comment]
Hi!

DeepVariant is not made to call variants in super high depth datasets, so this is not something we recommend doing.
There are several reasons for this, but one is that the pileup images can't be much taller than around 400 reads total due to limitations in the type of machine learning model we use. The cutoff of 1.5k reads is how many reads are considered when creating candidates, but a random selection of 95 of those are actually shown to the model.  Increasing the pileup image height above 95 would require retraining, and we don't find that this helps significantly enough to justify the longer runtime.

For high-depth applications we generally recommend that you use a specialized variant caller that is meant to support and make full use of all those reads. 

To answer your question of The flags that can be set with call_variants are all the ones listed with "flags.DEFINE"... in https://github.com/google/deepvariant/blob/r1.2/deepvariant/call_variants.py. The cutoff of 1.5k reads is `max_reads_per_partition` in https://github.com/google/deepvariant/blob/r1.2/deepvariant/make_examples_options.py. This is not a flag we recommend users to change though.


Just for my curiosity though, can you share what your application is and why the depth is so high?

**Comment by aude-darracq** [comment]
Hello Maria,

Thanks for your reply, this is very clear.
I have such a depth because only a small region of my genome is amplified (~15kb) and several DNA are pooled by "sample". As the aim is to find if one out of the pooled DNA contain SNPs, I need to use all PacBio sequences and not a subset.
