### ISSUE TITLE
Is deepvariant free to use?

### ISSUE THREAD

**Issue by amyhouseman** [google/deepvariant#502]
Hi, 

I can't see anywhere that explicitly states if deepvariant is free to use for the user? Also, if possible, because I am new to deepvariant (and running complex tools) - if I could possibly have some help in the initial running of it for my sequences from yourselves? I have looked at the documentation but still have a few questions and can't find anyone to ask for help. My email is HousemanA@cardiff.ac.uk.

Thanks!
Amy

**Comment by MariaNattestad** [comment]
Hi Amy

Yes, DeepVariant is free to use. A good place to start is to see if you can run the quick start: https://github.com/google/deepvariant/blob/r1.3/docs/deepvariant-quick-start.md
You might also find this video to be an accessible introduction to DeepVariant: https://www.youtube.com/watch?v=pZEMSBmoyi0
You can ask your questions here, though we ask that you try to read the documentation first and try to see if that answers your questions. And if you have any questions you can't ask publicly, then let me know and I can email you and try to help. Otherwise it's great to have questions and answers documented in the issues so if anyone else has the same question, they can find it by searching the issues.

Maria

**Comment by amyhouseman** [comment]
Hi Maria, 

Thank you so much for your response, it really helped!

Best wishes,
Amy

**Comment by MariaNattestad** [comment]
Glad to hear that!
