### ISSUE TITLE
Question about 'Could not create PileupImage' warning

### ISSUE THREAD

**Issue by celine-mercier** [google/deepvariant#512]
Hello, more of a question than an issue: what does the "Could not create PileupImage for candidate" mean during make_examples? What triggers it?

**Setup**
  - DeepVariant version: 1.1.0 and 1.3.0
  - Installation method: Singularity
  - Type of data: illumina on a Pinus genome (big, repetitive genome)

 **Error trace** 
```
W1203 19:21:43.514668 139865530996480 make_examples.py:1855] Could not create PileupImage for candidate at scaffold_1:9     
W1203 19:21:43.515001 139865530996480 make_examples.py:1855] Could not create PileupImage for candidate at scaffold_1:83    
W1203 19:21:43.515132 139865530996480 make_examples.py:1855] Could not create PileupImage for candidate at scaffold_1:91    
W1203 19:21:48.118362 140507900241664 make_examples.py:1855] Could not create PileupImage for candidate at scaffold_4:129804
W1203 19:21:51.183064 139737683482368 make_examples.py:1855] Could not create PileupImage for candidate at scaffold_19:82   
W1203 19:21:51.183443 139737683482368 make_examples.py:1855] Could not create PileupImage for candidate at scaffold_19:106  
```

Thanks

**Comment by MariaNattestad** [comment]
This happens when the variant is within 110 bp of the edge of a reference chromosome, or in your case too close to the edge of a scaffold. DeepVariant is built for calling on alignments to a reference genome, so on assemblies it will still work, but for things like this you may need to be careful. 

For reference, this is the relevant code: https://github.com/google/deepvariant/blob/5469fec47e57febba751c30f1eb587cbffea8d89/deepvariant/pileup_image.py#L436 -- it is when this function returns None that it triggers that warning in make_examples.py.

**Comment by celine-mercier** [comment]
Thank you!
