### ISSUE TITLE
Training non-human model of deep-trio 

### ISSUE THREAD

**Issue by jessieshen97** [google/deepvariant#532]
**Describe the issue:**
Hi! I am trying to use deep-trio to call variants of drosophila (PACBIO data). I have noticed you have provide guides for training CNN model of deep variant, but I have no idea of training model of deep trio. Can I train a drosophila model of deep trio?

**Setup**
  - Operating system: Cent OS
  - DeepVariant version: 1.3.0
  - Installation method (Docker, built from source, etc.): Singularity
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) pacbio sequencing data

**Comment by akolesnikov** [comment]
Hello jessieshen97,

In order to train a good model you need to run make_examples on multiple sets on different coverages. Internally we use Google scheduler with thousands of hosts. You may try to do it on one machine but it may be challenging.  
To answer you question, yes you can train a DeepTrio model of the diploid organism. Although, we don't have a document with detailed steps on training a DeepTrio model you can try following the steps for DeepVariant toy model training. The only difference is that you need to use DeepTrio make_examples. All other sets would be identical.

**Comment by jessieshen97** [comment]
> 

Thank you! I am gonna try that.

**Comment by pichuan** [comment]
I'll close this issue now @jessieshen97 . Feel free to reopen, or open a new issue if you have more questions.
