### ISSUE TITLE
representing depth

### ISSUE THREAD

**Issue by paupaiz** [google/deepvariant#536]
## ❓ Questions & Help

Apologies for the naive question: 
In [visualizing_examples](https://github.com/google/deepvariant/blob/r0.6/docs/visualizing_examples.ipynb), I get that the reconstructed image has bases on the x-axis and y-axis is a measure of sequencing depth, but why have so many rows empty if none of the examples reach that depth (there's so much space between the last aligned read and the end of the "image").

**Comment by MariaNattestad** [comment]
The images all have to be the same size for the model, so they are standardized to a height of 100 (5 rows for reference + 95 reads). Standardization like this is common in machine learning. Coverage does actually get that high for many of our training datasets when we use the full coverage without downsampling.
By the way, where did you find that link? It's a pretty old version of the notebook. We have since updated it here: https://github.com/google/deepvariant/blob/r1.3/docs/visualizing_examples.ipynb

**Comment by pichuan** [comment]
Hi @paupaiz , I'll close this issue now. Hopefully Maria's response answered your question.
One thing I'll add is that when you use make_examples, you can use the `pileup_image_height` to change the height of images you create. 
But, be careful that our default release models won't work directly if you change the pileup_image_height, so if you create images of different heights, you'll likely need to retrain your own model.
I'll close this issue now. Feel free to reopen or ask another question.

**Comment by paupaiz** [comment]
thank you both!
