### ISSUE TITLE
QUAL is systematically lower for heterozygote than homozygote sites

### ISSUE THREAD

**Issue by elcortegano** [google/deepvariant#547]
I am running the docker image of deepvariant 1.1.0 to find mutations in PacBio HiFi reads aligned with NGMLR (see command below). The issue I am finding is that QUAL values seem to be consistently lower for heterozygote than homozygote sites (around 3x lower median QUAL for heterozygote sites), which results in differential filtering of these types of variants. Why this happen?  

# Command to run docker
    docker run   -v "/myfolder/":/input   -v "/myfolder/":/output   google/deepvariant:1.1.0   /opt/deepvariant/bin/run_deepvariant   --model_type=PACBIO   --ref=/input/pool_founders.bp.p_ctg.fa   --reads=/input/sample.ngmlr.sort.bam   --output_vcf=/output/sample.deepvariant.vcf --num_shards=16

**Comment by AndrewCarroll** [comment]
Hi @elcortegano 

Just to clarify, are you referring to the QUAL field of the VCF (the 6th column of tab-file itself), or the GQ field (the 10th column of a single sample).

If you are referring to QUAL as the 6th column, this observation is expected. QUAL measures the probability that the ALT field has at least one allele with the ALT base. So you can think of it as p(HET) + p(HOM), or alternatively as 1 - p(REF). For homozygous positions, they look more clearly non-reference as in many cases they may not have any reference bases. 

Heterozygous positions likely have at least some evidence for the Ref allele, which suggests a higher probability that the position might be Ref.

If you are interested in filtering, we often recommend that the GQ field in the samples is preferable, as this is a measure of the genotype call itself being correct. There may be some differences between HET and HOM for this due to differences in difficulty in making those types of calls. However, it should be lower.

**Comment by elcortegano** [comment]
Hi Andrew,

Yes, I was referring to that QUAL value and your explanation makes a lot of sense. Thank you!
