### ISSUE TITLE
Additional documentation on single-step phasing

### ISSUE THREAD

**Issue by james-lawlor** [google/deepvariant#557]
Hi,
Is there any additional documentation available on the new single-step phasing method? It would be very helpful to have an overview of how that compares to the previous WhatsHap-based process in terms of how the phasing information is generated.

**Comment by akolesnikov** [comment]
Unfortunately we don't have any documentation on the method except release notes. The main motivation was to reduce the runtime and simplify the pipeline for PacBio data. The phasing is generated from DeepVariant proposed candidates. Proposed candidates are generated by counting alleles at each position and applying heuristics to reduce the number of proposed candidates. The main differences between one-step phasing and WhatsHap are:

* One-step phasing uses a greedy algorithm that processes intervals of 25000 bases long at a time. Using a greedy algorithm makes it inferior to WhatsHap. Although, experiments showed that final DeepVariant accuracy only slightly suffers.

* Another big difference is that one-step phasing uses "noisy" proposed candidates when WhatsHap is run on genotyped variants produced by running DeepVariant on unphased data. The code which performs the phasing operation is in https://github.com/google/deepvariant/blob/r1.4/deepvariant/direct_phasing.cc. 


Please note that our the DeepVariant model in v1.4 is able to run on candidates phased by WhatsHap, and the model has similar performance. This can be done by adding flags to the step of make_examples if run separately. If it is of interest for you to run DeepVariant v1.4 using the WhatsHap flags instead of the direct phasing, we can provide you with instructions to do so.

**Comment by james-lawlor** [comment]
Thank you, that's very helpful! That's just the sort of information I was looking for. It might be beneficial for other users to add that info to the docs
