### ISSUE TITLE
BAQ's effect on results quality (HiFi reads)

### ISSUE THREAD

**Issue by SHuang-Broad** [google/deepvariant#565]
Hi,

I am wondering if the DV team has done an evaluation on how the availability of BAQ (the `BQ:Z:...` tag) affects the quality of calls generated from HiFi reads.

Thank you!
Steve

**Comment by AndrewCarroll** [comment]
Hi @SHuang-Broad 

By default, DeepVariant only looks at the content of the QUAL field (column 11) in order to populate the quality values. DeepVariant is able to look at and read in arbitrary additional tags (e.g. we have used the HP tag for phasing in the past). We have not previously experimented with BAQ, but with the framework above it would not be hard to look at it if you have an intuition that it might help.

If you think it is promising, we could either do this investigation ourselves, or we could try to give you some instructions on how to do an experimental training if you are interested.

Thanks,
Andrew

**Comment by amwenger** [comment]
@SHuang-Broad - Which read aligner populates the BAQ values for HiFi reads?

With the standard PacBio tools, there is a PacBio `bq:i` tag output by `lima` demuliplexing that stores the quality of a barcode call.  But, `BQ:Z` is not a standard output for `pbmm2`.

**Comment by SHuang-Broad** [comment]
@AndrewCarroll 
Thanks for the answer.
We're in a bit of a time crunch now (operations), but knowing how to run that experiment will be super helpful!

@amwenger 
Right, `pbmm2` (used in our pipeline) doesn't provide the `BQ:Z` tag.
However, we also run `samtools calmd` on the BAM to generate the `MD:Z` tag. And `calmd` allows one to compute the BAQ by turning on the `-r` flag (off in our pipeline now). But as you can imagine, it will not be negligible compute.
Hence we are interested in doing some experiments to see if DV can benefit from this tag.

Steve

**Comment by AndrewCarroll** [comment]
Hi @SHuang-Broad 

I would like to conduct some experiments myself to investigate whether this field might help. Unfortunately, with many things going on those experiments might take some time to conclude. You mentioned you are in a time crunch. Given the uncertainty of whether this might help, I would recommend that if you need to proceed, you do so without the BAQ field (as we don't currently make use of it anyway).

**Comment by pichuan** [comment]
Hi @SHuang-Broad ,
this issue has been around for a while. If you'd like to follow up, please let us know! For now I'll close it.
