### ISSUE TITLE
RNA-seq model valid for genome-wide calling?

### ISSUE THREAD

**Issue by ASLeonard** [google/deepvariant#584]
Hi,

From the RNA example doc, it states
> We will also restrict analysis to CDS regions on chromosome 20 to make this demonstration quicker.

I'm not 100% on the biological nuances, but the total RNA samples I have access to should enable variant calling (nearly) genome-wide. Is that applicable with the RNA-seq model, or is that primarily trained on CDS/exome only?
 
Best,
Alex

**Comment by danielecook** [comment]
Hi @ASLeonard here is a table from the [preprint](https://www.biorxiv.org/content/10.1101/2022.10.16.512451v1). We stratify the F1-score across different region types. The published RNA-seq model is `DV RNA-seq [GTEx]`:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/1536935/200906677-4b6e2f11-8b29-44e3-871e-299f46d1cd64.png">

The model has no problem running genome wide, but the limitations are due to the nature of RNA-seq data. We observe the highest accuracy in CDS regions which is why the case study is limited to these regions. Users should filter variants depending on their use case. This might mean filtering by region, but you can also consider filtering by genotype quality (or both). We show how you can reduce the false-discovery rate in figure 5 of the preprint by filtering on genotype quality:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1536935/200907763-1d21cc44-daff-47d2-87c6-e7917ea62a32.png">

> Is that applicable with the RNA-seq model, or is that primarily trained on CDS/exome only?

The model is trained on exonic regions. We found this to give the best performance in our evaluations.

**Comment by ASLeonard** [comment]
Oh my, I missed that pre-print! So that _more_ than answers most of my questions. 

Also just heard about the A>I events earlier this week, so that will be an exciting direction if to have all-in-one if vcf can handle that cleanly.
