### ISSUE TITLE
If I stop halfway while running deepvariant, do I need to start all the steps again?

### ISSUE THREAD

**Issue by Sh1von** [google/deepvariant#587]
I finnished make_example and call_variant by docker, but somehow it stoped. So i restart docker and realized i have to do make_example and call_variant again even I already have set intermediate_results_dir to store intermediate outputs.

**Comment by pichuan** [comment]
Hi @Sh1von ,

Thanks for reporting this. Currently that's how our pipeline is designed unfortunately. We don't automatically resume.

However, if make_examples and call_variants has completed successfully, you can manually run postprocess_variants separately. The way to figure out the commands to use : You can run your original command with `--dry_run`, and then it'll break down the sequence of commands you need. Then, you can manually rerun the postprocess_variants command.

I understand that being able to resume can be a useful feature. To automatically detect existing data robustly will be challenging, because we don't know if there might be corrupted data. But, I think it'll be possible to add a flag for users to skip steps. I will think about it a bit more.

For now, please try manually re-run postprocess_variants, and see if that works for you. Sorry for the inconvenience!

**Comment by Sh1von** [comment]
Thank you！
