### ISSUE TITLE
How to run the pre-built bunaries DeepVariant

### ISSUE THREAD

**Issue by zivlang** [google/deepvariant#590]
**Describe the issue:**
Since I couldn't run DeepVariant with Docker, I thought I'd try the prebuilt binaries version, but I couldn't find a guide on how to use the prebuilt binaries DeepVariant.

**Comment by pichuan** [comment]
Hi @zivlang ,

In https://github.com/google/deepvariant/blob/r0.6/docs/deepvariant-quick-start.md and earlier versions, we show how you can use the pre-built binaries. The main thing is that you need to run `run-prereq.sh` first.

Some details might have changed since v0.6, but the steps should be similar. Please take a look at the older document first, and I'll plan to do a step-by-step documentation here later today.

**Comment by pichuan** [comment]
Before you proceed, if you can't use Docker because of root permission, I recommend that you try Singularity: https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-quick-start.md#notes-on-singularity

If you don't have root permission, you won't be able to install necessary things before running the binaries either.

---

Here is what I did:

Get a machine. (Not required to run on GCP. I just use this to get a machine to test)

`gcloud compute instances create "${USER}-cpu" --scopes "compute-rw,storage-full,cloud-platform" --image-family "ubuntu-2004-lts" --image-project "ubuntu-os-cloud" --machine-type "custom-64-131072" --boot-disk-size "300" --zone "us-west2-b" --min-cpu-platform "Intel Skylake"`

ssh into the machine:

```
gcloud compute ssh pichuan-cpu --zone us-west2-b
```

Get the binaries and models:

```
BUCKET="gs://deepvariant"
BIN_VERSION="1.4.0"
MODEL_VERSION="1.4.0"

BIN_BUCKET="${BUCKET}/binaries/DeepVariant/${BIN_VERSION}/DeepVariant-${BIN_VERSION}"
MODEL_NAME="DeepVariant-inception_v3-${MODEL_VERSION}+data-wgs_standard"

mkdir -p bin
# Download the DeepVariant binaries.
gsutil -m cp "${BIN_BUCKET}/*" bin/
chmod a+x bin/*
```

Then, I ran:
```
cd bin; bash run-prereq.sh; cd -
```

The `run-prereq.sh` tends to be the most tricky one - it will require root permission, and it'll install a bunch of stuff on your machine. If you can't use Docker because of root permissions, you likely won't be able to run this as well.

Download test data:

```
INPUT_DIR="${PWD}/quickstart-testdata"
DATA_HTTP_DIR="https://storage.googleapis.com/deepvariant/quickstart-testdata"

mkdir -p ${INPUT_DIR}
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/NA12878_S1.chr20.10_10p1mb.bam
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/NA12878_S1.chr20.10_10p1mb.bam.bai
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/test_nist.b37_chr20_100kbp_at_10mb.bed
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/test_nist.b37_chr20_100kbp_at_10mb.vcf.gz
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/test_nist.b37_chr20_100kbp_at_10mb.vcf.gz.tbi
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta.fai
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta.gz
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta.gz.fai
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta.gz.gzi
```

Run make_examples:

```
OUTPUT_DIR="${PWD}/quickstart-output"
mkdir -p "${OUTPUT_DIR}"
```

```
python bin/make_examples.zip \
  --mode calling   \
  --ref "${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta"   \
  --reads "${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam"   \
  --regions "chr20:10,000,000-10,010,000" \
  --examples "${OUTPUT_DIR}/examples.tfrecord.gz" \
  --channels "insert_size"
```

(To figure out which flags you need to add for each model, you can read https://github.com/google/deepvariant/blob/r1.4/scripts/run_deepvariant.py#L236-L253 . Sorry that we don't have better documentation than that right now)

For how to run this with multiple shards, and how to run the rest of the commands, please read https://github.com/google/deepvariant/blob/r0.6/docs/deepvariant-quick-start.md

I just tested the steps above and confirmed that it worked for me on v1.4.0, at least for the make_examples step.
If you encounter more issues with other steps, please feel free to ask again. I'd be happy to help.

Note that I don't plan to put this into an official documentation page now, because that adds to our maintenance burden to keep it up to date. Given that we have the Docker/Singularity solution that works generally well for our users, I don't expect many of our users to need to use pre-built binaries. @zivlang thank you for your question so I have a chance to test it again and document it here. Hopefully this is helpful for you. Happy to answer more questions if you encounter more problems.

**Comment by zivlang** [comment]
Thanks!

בתאריך יום ב׳, 21 בנוב׳ 2022, 23:50, מאת Pi-Chuan Chang ‏<
***@***.***>:

**Comment by George-du** [comment]
How to run the pre-built bunaries DeepVariant in Centos linux.

**Comment by pgrosu** [comment]
@George-du The most efficient pre-built binaries would be the Docker/Singularity approach.

**Comment by GooLey1025** [comment]
Hello, developers
Now I can use docker, but computer nodes in our HPC server did not have docker. So I need to do build from sources. I can use docker now, can i build from source via docker?
