### ISSUE TITLE
@clif not find!

### ISSUE THREAD

**Issue by huangl07** [google/deepvariant#6]
my dear:

   when I wos running ./build_and_test.sh,it print
`+ source settings.sh
++ export TF_CUDA_CLANG=0
++ TF_CUDA_CLANG=0
++ export TF_ENABLE_XLA=0
++ TF_ENABLE_XLA=0
++ export TF_NEED_CUDA=0
++ TF_NEED_CUDA=0
++ export TF_NEED_GCP=1
++ TF_NEED_GCP=1
++ export TF_NEED_GDR=0
++ TF_NEED_GDR=0
++ export TF_NEED_HDFS=0
++ TF_NEED_HDFS=0
++ export TF_NEED_JEMALLOC=0
++ TF_NEED_JEMALLOC=0
++ export TF_NEED_MKL=0
++ TF_NEED_MKL=0
++ export TF_NEED_MPI=0
++ TF_NEED_MPI=0
++ export TF_NEED_OPENCL=0
++ TF_NEED_OPENCL=0
++ export TF_NEED_OPENCL_SYCL=0
++ TF_NEED_OPENCL_SYCL=0
++ export TF_NEED_S3=0
++ TF_NEED_S3=0
++ export TF_NEED_VERBS=0
++ TF_NEED_VERBS=0
++ export TF_CUDA_VERSION=8.0
++ TF_CUDA_VERSION=8.0
++ export CUDA_TOOLKIT_PATH=/usr/local/cuda
++ CUDA_TOOLKIT_PATH=/usr/local/cuda
++ export TF_CUDNN_VERSION=6
++ TF_CUDNN_VERSION=6
++ export CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
++ CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
++ export DEEPVARIANT_BUCKET=gs://deepvariant
++ DEEPVARIANT_BUCKET=gs://deepvariant
++ export DV_PACKAGE_BUCKET_PATH=gs://deepvariant/packages
++ DV_PACKAGE_BUCKET_PATH=gs://deepvariant/packages
++ export DV_GPU_BUILD=0
++ DV_GPU_BUILD=0
++ export DV_USE_GCP_OPTIMIZED_TF_WHL=1
++ DV_USE_GCP_OPTIMIZED_TF_WHL=1
++ export GCP_OPTIMIZED_TF_WHL_FILENAME=tensorflow-1.4.1.deepvariant_gcp-cp27-none-linux_x86_64.whl
++ GCP_OPTIMIZED_TF_WHL_FILENAME=tensorflow-1.4.1.deepvariant_gcp-cp27-none-linux_x86_64.whl
++ export GCP_OPTIMIZED_TF_WHL_PATH=gs://deepvariant/packages/tensorflow
++ GCP_OPTIMIZED_TF_WHL_PATH=gs://deepvariant/packages/tensorflow
++ export DV_TF_NIGHTLY_BUILD=0
++ DV_TF_NIGHTLY_BUILD=0
++ export DV_INSTALL_GPU_DRIVERS=0
++ DV_INSTALL_GPU_DRIVERS=0
+++ which python
++ export PYTHON_BIN_PATH=/home/huangl/publib/bin/python
++ PYTHON_BIN_PATH=/home/huangl/publib/bin/python
++ export USE_DEFAULT_PYTHON_LIB_PATH=1
++ USE_DEFAULT_PYTHON_LIB_PATH=1
++ export 'DV_COPT_FLAGS=--copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-O3'
++ DV_COPT_FLAGS='--copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-O3'
++ export DV_TENSORFLOW_GIT_SHA=ab0fcaceda001825654424bf18e8a8e0f8d39df2
++ DV_TENSORFLOW_GIT_SHA=ab0fcaceda001825654424bf18e8a8e0f8d39df2
+ [[ 0 = \1 ]]
+ bazel test -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-O3 deepvariant/...
(08:09:38) INFO: Current date is 2017-12-08
(08:09:38) WARNING: /home/huangl/.cache/bazel/_bazel_huangl/008c6ca154d923f28d39cff9fad40a7f/external/org_tensorflow/tensorflow/core/BUILD:1806:1: in includes attribute of cc_library rule @org_tensorflow//tensorflow/core:framework_headers_lib: '../../../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'external/org_tensorflow/tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /home/huangl/.cache/bazel/_bazel_huangl/008c6ca154d923f28d39cff9fad40a7f/external/org_tensorflow/tensorflow/tensorflow.bzl:1100:30
(08:09:38) INFO: Analysed 241 targets (0 packages loaded).
(08:09:38) INFO: Found 185 targets and 56 test targets...
(08:09:38) ERROR: missing input file '@clif//:clif/bin/pyclif_proto'
(08:09:38) ERROR: /home/huangl/biotools/deepvariant/deepvariant/core/protos/BUILD:32:1: //deepvariant/core/protos:core_pyclif_clif_rule: missing input file '@clif//:clif/bin/pyclif_proto'
(08:09:38) ERROR: /home/huangl/biotools/deepvariant/deepvariant/core/protos/BUILD:32:1 1 input file(s) do not exist
(08:09:38) INFO: Elapsed time: 0.334s, Critical Path: 0.00s
(08:09:38) FAILED: Build did NOT complete successfully
//deepvariant:allelecounter_test                                      NO STATUS
//deepvariant:call_variants_test                                      NO STATUS
//deepvariant:data_providers_test                                     NO STATUS
//deepvariant:make_examples_test                                      NO STATUS
//deepvariant:model_eval_test                                         NO STATUS
//deepvariant:model_train_test                                        NO STATUS
//deepvariant:modeling_test                                           NO STATUS
//deepvariant:pileup_image_test                                       NO STATUS
//deepvariant:postprocess_variants_lib_test                           NO STATUS
//deepvariant:postprocess_variants_test                               NO STATUS
//deepvariant:tf_utils_test                                           NO STATUS
//deepvariant:utils_test                                              NO STATUS
//deepvariant:variant_caller_test                                     NO STATUS
//deepvariant:variant_calling_test                                    NO STATUS
//deepvariant:variant_labeler_test                                    NO STATUS
//deepvariant/core:cigar_test                                         NO STATUS
//deepvariant/core:cpp_math_test                                      NO STATUS
//deepvariant/core:cpp_utils_test                                     NO STATUS
//deepvariant/core:errors_test                                        NO STATUS
//deepvariant/core:genomics_io_gcs_test                               NO STATUS
//deepvariant/core:genomics_io_noplugin_test                          NO STATUS
//deepvariant/core:genomics_io_test                                   NO STATUS
//deepvariant/core:hts_test                                           NO STATUS
//deepvariant/core:hts_verbose_test                                   NO STATUS
//deepvariant/core:io_utils_test                                      NO STATUS
//deepvariant/core:py_math_test                                       NO STATUS
//deepvariant/core:py_utils_test                                      NO STATUS
//deepvariant/core:ranges_test                                        NO STATUS
//deepvariant/core:reader_base_test                                   NO STATUS
//deepvariant/core:reference_fai_test                                 NO STATUS
//deepvariant/core:sam_reader_test                                    NO STATUS
//deepvariant/core:samplers_test                                      NO STATUS
//deepvariant/core:variantutils_test                                  NO STATUS
//deepvariant/core:vcf_reader_test                                    NO STATUS
//deepvariant/core:vcf_writer_test                                    NO STATUS
//deepvariant/core/python:hts_verbose_test                            NO STATUS
//deepvariant/core/python:math_wrap_test                              NO STATUS
//deepvariant/core/python:reference_wrap_test                         NO STATUS
//deepvariant/core/python:sam_reader_wrap_test                        NO STATUS
//deepvariant/core/python:vcf_reader_wrap_test                        NO STATUS
//deepvariant/core/python:vcf_writer_wrap_test                        NO STATUS
//deepvariant/environment_tests:env_smoke_test                        NO STATUS
//deepvariant/environment_tests:protobuf_implementation_test          NO STATUS
//deepvariant/python:allelecounter_wrap_test                          NO STATUS
//deepvariant/python:variant_calling_wrap_test                        NO STATUS
//deepvariant/realigner:aligner_test                                  NO STATUS
//deepvariant/realigner:realigner_test                                NO STATUS
//deepvariant/realigner:ssw_test                                      NO STATUS
//deepvariant/realigner:window_selector_test                          NO STATUS
//deepvariant/realigner/python:debruijn_graph_wrap_test               NO STATUS
//deepvariant/realigner/python:ssw_misc_test                          NO STATUS
//deepvariant/realigner/python:ssw_wrap_test                          NO STATUS
//deepvariant/testing:gunit_extras_test                               NO STATUS
//deepvariant/vendor:statusor_test                                    NO STATUS
//deepvariant/vendor:timer_test                                       NO STATUS
//deepvariant/vendor/python:statusor_examples_test                    NO STATUS
`
how to fix it ? I am not a root users

Thanks

**Comment by pichuan** [comment]
Hi,
can you give a bit more information about what OS you're using?
What do you get when you run 
uname -a
?

**Comment by huangl07** [comment]
Linux login02.local 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64 GNU/Linux

sorry，I forgot that

thanyou!

**Comment by huangl07** [comment]
P.S.
Maybe centos 6.5 is your need

**Comment by pichuan** [comment]
Hi,
currently the instructions are written for Ubuntu 16. I've not tried it on CentOS before.
If you have access to a Ubuntu 16 machine, can you give it a try and see if you're still seen the same issue? I can also try running on CentOS and report back, but that might take a while for me to do.

**Comment by pgrosu** [comment]
@huangl07 Does `./build-prereq.sh` complete successfully for you, as noted [here](https://github.com/google/deepvariant/blob/master/docs/deepvariant-build-test.md)?

**Comment by huangl07** [comment]
well，I have no  root permission

**Comment by pichuan** [comment]
huangl07, you will need to successfully run build-prereq.sh first. Please try it on a Ubuntu 16 machine where you have permission.
Thanks pgrosu for pointing out that issue.

**Comment by ardoli** [comment]
Got the same problem, but run build-prereq.sh is not possible on a CentOS 7 basis !

**Comment by pgrosu** [comment]
@ardoli You will need to use Ubuntu 14 or 16 - see the following:  

https://github.com/google/deepvariant/blob/59738f0ca91df3757d754e7ce6507f614816fd1c/docs/deepvariant-build-test.md

**Comment by ardoli** [comment]
Thank's for the answer, I saw it, but all servers in the genomic research center I work are on CentOS-7 and Ubuntu is not an option. So I can't use Ubuntu, and of course, no way to send human genomic data on the cloud. Maybe a more generic installation procedure, not stick on ubuntu, could be a good idea, at least for me.

**Comment by ink1** [comment]
I worked around that by creating a custom Docker image (the provided one didn't work for me) and then converting it to a Singularity image. And it worked on CentOS 7. I was going to share the recipe when I have the time. Of course, you'd need to convince your sysadmins to install Singularity for you but that should be possible because Singularity was designed with HPC in mind.

**Comment by pgrosu** [comment]
@ardoli, @ink1's suggestion is great, and there are two more:

* You can try [Udocker](https://blog.utar.co/blog/udocker) so that root privileges are not required for a Docker image.
* Tweak the DeepVariant source code to make it compile in user-space for your environment.  It's a bit hairy, but can be done.  The plus side is that you'll see DeepVariant is a pretty simple and modular pipeline, which you can tweak for your preferred analysis.  Deep neural networks can be applied to many areas in the -Omics space besides just variant analysis.

**Comment by ardoli** [comment]
Sound a good idea, and Singularity is installed on ours servers. I will try it, of course if in the meantime you had the time to share your recipe it will be great. If my Singularity image is ok, I will see to share it if their no licence restriction. Thank’s for this answer.


Le 12 mars 2018 à 20:47, ink1 <notifications@github.com<mailto:notifications@github.com>> a écrit :


I worked around that by creating a custom Docker image (the provided one didn't work for me) and then converting it to a Singularity image. And it worked on CentOS 7. I was going to share the recipe when I have the time. Of course, you'd need to convince your sysadmins to install Singularity for you but that should be possible because Singularity was designed with HPC in mind.

**Comment by ink1** [comment]
I created a build script and a singularity image updating to 0.5.2 in the processes; here is my fork:
https://github.com/ink1/deepvariant/releases/tag/v0.5.2a
The binary release is the singularity image.

My original image was quite large because I built everything inside of the container. Instead I resorted to the original Dockerfile which relies on pre-built zip files which my build script downloads. Still the image is 2 GB but then it should just run I presume. The changes I had to do to the Dockerfile are probably optional - my docker version does not like the lines with ARG.

**Comment by ardoli** [comment]
Thank’s ink1. I will try your singularity image, I have just finish build my own docker image.

Le 13 mars 2018 à 13:13, ink1 <notifications@github.com<mailto:notifications@github.com>> a écrit :


I created a build script and a singularity image updating to 0.5.2 in the processes; here is my fork:
https://github.com/ink1/deepvariant/releases/tag/v0.5.2a
The binary release is the singularity image.

My original image was quite large because I built everything inside of the container. Instead I resorted to the original Dockerfile which relies on pre-built zip files which my build script downloads. Still the image is 2 GB but then it should just run I presume. The changes I had to do to the Dockerfile are probably optional - my docker version does not like the lines with ARG.

**Comment by ardoli** [comment]
Building a deepvariant Singularity image is indeed really quite simple and portable. I did it and test it on CentOS7 and MacOS X and it run in both case with deepvariant quick-test data. I will post the complete "how-to" when I'll have a couple of minutes.
Thank's ink1 for the idea.

**Comment by DiableJambe** [comment]
I see the same issue, but with Ubuntu-16

(02:53:00) ERROR: /root/variant_calling/deepvariant/deepvariant/protos/BUILD:56:1: //deepvariant/protos:deepvariant_pyclif_clif_rule: missing input file '@clif//:clif/bin/pyclif_proto'
(02:53:00) ERROR: /root/variant_calling/deepvariant/deepvariant/protos/BUILD:56:1 1 input file(s) do not exist

This is running on IBM Power 8, so I build pyclif from source. However, the location of pyclif isn't the same as what is in build-prereq.sh, so I commented that section out because `which pyclif` works.
