### ISSUE TITLE
sample name "default" used in output VCF for one chromosome

### ISSUE THREAD

**Issue by ptrebert** [google/deepvariant#603]
Hi,

I have encountered a somewhat unexpected behavior related to the sample name written to the output VCF (possibly caused by the presence of chrEBV?!)

**Describe the issue:**
Sample name "default" is used in the output VCF for "chrEBV", all other chromosome VCFs contain correct sample name (chr1-chr22,chrX,chrY,chrM)

**Setup**
  - Operating system: CentOS
  - DeepVariant version: v1.2
  - Installation method (Docker, built from source, etc.): Singularity v3.5.2
  - Type of data: PacBio HiFi, Sequel-II

**Steps to reproduce:**
  - Command:
  ```
/opt/deepvariant/bin/run_deepvariant \
--model_type="PACBIO" \
--regions "$CHROM"
[ ... otherwise default options ...]
```
  - note: the input BAM alignment contains the sample name in the header (i.e. `SM:HG002`)
  - Error trace: (n/a - run finishes)

**Does the quick start test work on your system?**
can't be used to reproduce the problem

**Any additional context:**
In the log for each chromosome run, I see that all chromosomes except chrEBV are listed in lines like this
```
I0112 10:31:04.917984 47443049531200 \
make_examples_core.py:236] \
Task 6/12: Common contigs are [ HERE: list of all chromosomes except for chrEBV]
```

Best,
Peter

**Comment by pichuan** [comment]
Hi Peter,
Just to check that I understand your issue here:

Are you saying that: your reference contains information for chrEBV, your BAM file also has reads from chrEBV, and then your run completed without crashing. And you used the same BAM file for all these runs. And the only difference was just that the run where you specified `--regions "chrEBV"` gives you the sample name as "default", while all other runs with the same BAM file (but different `--regions`) gave the correct sample name?

Another question, if the common contigs didn't list chrEBV, were you actually able to get any calls for chrEBV?

Another question for you: Are these files publicly shareable (or if you have a publicly shareable version that can help us reproduce similar issues?)

Thank you!

**Comment by ptrebert** [comment]
Hi Pi-Chuan,
thanks for looking into this - to answer your questions:

1. yes, exactly as you summarized it
2. no, there are no calls in the `chrEBV` output VCF (just as comparison: the `chrM` VCF looks just like the others with correct sample name and has two calls)
3. I am running this analysis as a favor for a collaboration partner, so I cannot share ad hoc. I'll reach out to them, but this is very much WIP, so I have my doubts.

Thanks!

**Comment by ptrebert** [comment]
Ha, ignore that - I executed the run again to be sure, and the "default" sample name does only show up in the filtered version of the VCF, not in the raw output by DeepVariant (sorry, I just realize now that I had looked at wrong file...). So it's likely a bcftools issue... not your problem, that is! Sorry for the noise.
