### ISSUE TITLE
DeepTrio for quartet families

### ISSUE THREAD

**Issue by karoliinas** [google/deepvariant#609]
Hi,

I'm running DeepTrio for ~100 samples of WGS data from quartet families. Is it possible to specify such a quartet (or larger) families to DeepTrio? Currently it seems that the algorithm will call the variants for the parents multiple times when each trio is provided separately, which is not optimal.

I also have a question about de novo variant calling, I understand from the article that DeepTrio is not as sensitive to de novos as some other tools (as it will be less likely to call a variant in a child that is not present in either parent). What is currently your recommended practice regarding de novo variant calling?

I'm running DeepTrio (version 1.4.0, specified as deeptrio-latest) via Docker (version 20.10.6) using Singularity.

Many thanks!

Karoliina

**Comment by pichuan** [comment]
Hi @karoliinas ,

The DeepTrio model we trained and provided wasn't trained in the condition you described. So it won't work if you try to apply our model that way. 
DeepVariant is a general framework that could be extended to multiple samples. (DeepTrio is basically an extension as a 3-sample model, where we trained two models - one to predict child, one to predict parents). 
In order to create your own model with your customized semantics, you'll need to carefully create the examples and labels correctly, and train a model your own. We don't currently plan to extend the use cases for our officially released models.
If you're interested in the advanced usage (creating your own images+labels and train a model), you can look at a few pointers: https://github.com/google/deepvariant/blob/r1.4/deepvariant/multisample_make_examples.py , https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-training-case-study.md . But we won't be able to provide step-by-step instructions for each use cases.

In terms of de novo - directly using DeepVariant to call the single sample is one simple alternative.

**Comment by karoliinas** [comment]
Hi @pichuan,

thank you for the quick reply! I wasn't planning on training a model, but good to know it's an option. I will consider running DeepVariant in multisample mode, as calling the variants for each parent twice is taking long. Might be better for those de novos too. 

And thanks for the great tool! Previously I was using GATK haplotypecaller, but the workflow was quite cumbersome and the reference samples sequenced together with the families (hg002&hg005) have a much better concordance in DeepVariant, particularly with indels. Plus it's just one command :) 

-Karoliina

**Comment by AndrewCarroll** [comment]
Hi @karoliinas 

As Pi-Chuan mentioned, it is (in theory) possible to train a quartet model, but it would take work. If you want to always have consistent calls between parents and child, the best thing is probably to either use parent calling from only 1 DeepTrio run, or to run DeepVariant instead on the full quartet.

In the event that you do want to use DeepTrio on both trios as opposed to DeepVariant on the four, there are some things you can look at to increase sensitivity for de novos. From our benchmarks, DeepTrio has a higher overall accuracy for de novos, but is more conservative (lower sensitivity, higher specificity). You could potentially use the GQ/PL values for no-call sites that are potential de novos sites and rank these  by confidence, setting your own threshold.

I mention the above possibility as an option. It sounds like for your use case of having a quartet and wanting higher sensitivity, the most straightfoward approach is to just use DeepVariant for joint genotyping.

Thanks,
Andrew

**Comment by karoliinas** [comment]
Hi @AndrewCarroll and many thanks for these recommendations. I have carefully considered the options and decided to continue with DeepTrio. I'll look into ranking the denovos based on the GQ/PL sites, as you suggest. It will also be interesting to compare these with the previous results I have from GATK.

Best,
Karoliina

**Comment by karoliinas** [comment]
Hi @AndrewCarroll, one more question.  I didn't start the analysis yet and just found out there are more samples than I initially thought, so reconsidering DeepVariant in multisample mode for the quartets.

Is the idea to run GLnexus per family quartet or the entire cohort of now ~250 WGS samples? This step is somewhat equivalent to GATKs genotypeGVCFs, right? 

Thanks again!
Karoliina

Thanks again!
Karoliina
