### ISSUE TITLE
Empty INFO column

### ISSUE THREAD

**Issue by pamelameza** [google/deepvariant#620]
Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md: Yes

Describe the issue:
Hello,

I'm using WGS data from PacBio HiFi, however, in the output vcf file the column INFO is empty. Is there any way to fill this column or how can this be fixed?

![Captura de pantalla 2023-03-15 a la(s) 12 22 56 p m](https://user-images.githubusercontent.com/117956356/225406490-86833319-9e20-4099-8a32-81ef2ba877fc.png)

Thanks a lot!

**Comment by AndrewCarroll** [comment]
Hi @pamelameza 

The contents of the INFO field are generally used by other calling methods to describe statistics about the variant position that are used in the process of variant calling (for example "##INFO=<ID=ClippingRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref number of hard clipped bases">"). 

In DeepVariant, instead of directly calculating many of these values to use in a statistical model, the more raw read-level data is directly presented to a neural network and the neural network itself determines what properties in the raw data are useful for variant calling. So we don't populate the INFO field as we don't calculate many of those derived features.

One thing that people often use the INFO field for is to filter variant calls by different properties. We've looked into the most effective ways to filter calls, and it is consistently the case that the sample level GQ field is well-calibrated to the probability of a call being correct.

If you want to see some data for this, you can look at the calibration in Figure 2 of the DeepVariant paper (https://www.nature.com/articles/nbt.4235) or at the general work in our cohort calling paper (https://academic.oup.com/bioinformatics/article/36/24/5582/6064144).

Are there fields in particular you generally use within INFO? It's unlikely we could easily add them, but it might be useful for us to know.

Thank you,
Andrew
