### ISSUE TITLE
weird character for minus values in plot axis of the visual_report.html

### ISSUE THREAD

**Issue by splaisan** [google/deepvariant#643]
using the latest docker version 1.5.0 on ubuntu 22

```
latest: Pulling from google/deepvariant
Digest: sha256:6a27bc877db9191c8fad0fe5f98dce6192fd4eb6392551e1a3add8d01e08af2e
Status: Image is up to date for google/deepvariant:latest
docker.io/google/deepvariant:latest
```

When I open the final report html page, I get weird ```â^'``` characters where I would expect a minus '-' symbol for the x-axis scales of the bottom two biallelic size distribution plots.

All other plots lack negative values and are not affected.

![Screenshot 2023-05-04 at 17 13 33](https://user-images.githubusercontent.com/858516/236251296-d4169c1a-f3e1-4472-982b-893914b66747.png)

Is this something that can be fixed to get prettier scales?

Thanks in advance

**Comment by MariaNattestad** [comment]
Thanks for the question. Yes that is definitely some kind of bug, but I'm not able to reproduce it. It looks like something wrong with the rendering in vega-lite.

How does this report look to you?: https://42basepairs.com/browse/gs/deepvariant/visual_reports/DeepVariant/1.5.0/WGS
This one has proper minus signs when I look at it. I'm asking because the report is effectively a website, so rendering can show up differently on different computers.

A few things you could try:
1. Open the HTML report in a different web browser (Chrome, Firefox, Safari, etc.)
2. Click the (...) in the top right corner of the report and go to "Open in Vega Editor".
3. Play with any language settings on the computer or web browser in case it's the alphabet available that is missing the "-" character.

If none of those solve the issue, then I'm also happy to take a look at your report, if you can share it.

**Comment by splaisan** [comment]
Hi Maria,

Thanks for your kind help and time.

Your linked report looks OK and shows minus symbols in chrome (OSX) while mine are bad and were obtained on two different ubuntu22 servers with the same docker image.

I attach here one such report for your review, the data is not confidential and comes from a SRA genome

[WT_REP1.visual_report.html.zip](https://github.com/google/deepvariant/files/11404181/WT_REP1.visual_report.html.zip)

best regards

**Comment by MariaNattestad** [comment]
Okay it looks like it's the text encoding. Looking at the report you attached, I was able to fix it by changing the `vega@5` import (line 9) to specify `charset="UTF-8"`:

```
<script type="text/javascript" charset="UTF-8" src="https://storage.googleapis.com/deepvariant/lib/vega/vega@5"></script>
```
Does that solve it on your end too?

**Comment by MariaNattestad** [comment]
And when you make the change above, does that look okay on the Ubuntu 22 server?

**Comment by splaisan** [comment]
Hi Maria,
Thanks a lot!
It worked like a charm both on the distant copy on the server in firefox and on the transferred copy on my mac.
And I do not see any side effects on the remaining of the page.
problem solved.
Best regards
