### ISSUE TITLE
PacBio Variant Call and Phasing step

### ISSUE THREAD

**Issue by kiranpatil222** [google/deepvariant#649]
Hi,

I am new to Long reads seq and Deepvariant i tried to to WGS Variant calling steps from Alignment ( pbmm2 ) from GIAB data and Variant Call  through Deepvariant  Singularity Image ( singularity pull --name deepvariant.simg docker://google/deepvariant)

`singularity exec --bind /data $path/Programs/DeepVariant/deepvariant.simg /opt/deepvariant/bin/run_deepvariant --model_type PACBIO --ref $path/Data/resources/Homo_sapiens_assembly38.fasta --reads $path/Data/m84011_220902_175841_Aln.bam --output_vcf $path/Analysis/out_m84011_220902_175841_sif.vcf.gz --num_shards 60`

My query: Is Haplotype phasing  with whatshap  mandatory step after variant call ? As it takes more than 3hrs i do not see anyway to speed up with more cpus.

**Comment by danielecook** [comment]
@kiranpatil222 you are in luck. Our [v1.4.0 release](https://github.com/google/deepvariant/releases/tag/v1.4.0) introduced 'direct phasing,' which means you no longer need to run whatshap. 

See the [PacBio case study](https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-pacbio-model-case-study.md) for further details.

**Comment by kiranpatil222** [comment]
@danielecook Thanks a lot for for clarification.

One more quick question outa topic, As you said in v1.4.0 it no longer need Whatshap, How to check my Singularity (SIF) DeepVariant image version the one i am using ?

**Comment by SHuang-Broad** [comment]
Hi, 

I'm sure I'm doing something wrong, but couldn't figure out where that is: the variants I get are not directly phased.

I followed the PacBio case study, using the 1.5.0 docker. 
Here's the command

```bash
$ ./run_deepvariant \
    --model_type PACBIO \
    --ref /shuang_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa \
    --reads /shuang_data/HG003.GRCh38.chr20.pFDA_truthv2.bam \
    --output_vcf /tmp/only_vcf.vcf.gz \
    --regions chr20
```

What's strange in the log are the following lines

```
...
I0514 01:48:09.263085 140121429608256 make_examples_core.py:257] 62017 candidates (71070 examples) [121.51s elapsed]
I0514 01:48:23.145400 140121429608256 make_examples_core.py:257] Skip phasing: len(candidates[main_sample]) is 7088.
I0514 01:52:54.732045 140121429608256 make_examples_core.py:257] 67303 candidates (76952 examples) [285.47s elapsed]
...
I0514 02:28:55.286200 140121429608256 make_examples_core.py:257] 166834 candidates (181516 examples) [142.03s elapsed]
I0514 02:29:01.686342 140121429608256 make_examples_core.py:257] Skip phasing: len(candidates[main_sample]) is 5953.
I0514 02:31:24.326849 140121429608256 make_examples_core.py:257] 172413 candidates (187997 examples) [149.04s elapsed]
I0514 02:31:26.924692 140121429608256 make_examples_core.py:257] Skip phasing: len(candidates[main_sample]) is 7496.
I0514 02:35:53.029588 140121429608256 make_examples_core.py:257] 178012 candidates (194646 examples) [268.70s elapsed]
....
```

The linked PacBio case study also doesn't mention anything about phasing, or any related metric.

Could you please help?
Thank you!

Steve

**Comment by pichuan** [comment]
Hi @SHuang-Broad , thanks for your question.

This line in the log indicates that you are running with our internal phasing:
```
I0514 02:29:01.686342 140121429608256 make_examples_core.py:257] Skip phasing: len(candidates[main_sample]) is 5953.
```
(In this case, the phasing algorithm skips some windows based on some threshold)

Given that you're using run_deepvariant, you can see that in r1.5, our run_deepvariant.py enables `phase_reads` for the PacBio mode.
https://github.com/google/deepvariant/blob/r1.5/scripts/run_deepvariant.py#L247-L260
(Other than `phase_reads`, a few other flags are also necessary. For example: `track_ref_reads`, `sort_by_haplotypes`, `parse_sam_aux_fields`, And `partition_size` to cover enough candidates.)
If you're running make_examples separately, please make sure to add these flags. You can use the `--dry_run` flag of run_deepvariant to figure out which flags to add.

Note that our phasing is intended for use in DeepVariant accuracy only (so that our users don't need to add an extra step like before). We don't intend for our phasing results to be used like a standalone phasing tool. That is why we didn't explicitly expose the phased results.

If you're not seeing the accuracy we reported, or the accuracy you see on other samples look unexpected, please let us know!

By the way, if you really want to double check the phasing results, you can save the make_examples results using the --intermediate_results_dir flag. And then use our https://github.com/google/deepvariant/blob/r1.5/docs/show-examples.md tools to visualize the images. You should able to see a channel with the sorted HP values. Note that not all windows would be phased, but if you look through a few of them you should be able to check.

If you're curious about the phasing algorithm itself, @akolesnikov and @kishwarshafin are working on writing up a bit more of the details. That might take a while to finish, but we can let you know when we have some more details to share.

**Comment by alisondiazc** [comment]
Hello Pi-Chuan, thanks for answer above. Just to make it clear to me... I obtained a VCF file using version 1.4.0, but I cannot see the phase data (e.g., "|") in my sample. Does this mean that I need to call variants again using version 1.5.0 and the "--phase_reads" flag? Or does DeepVariant not explicitly provide this data, requiring me to run Whatshap + DeepVariant to visualize it?

**Comment by SHuang-Broad** [comment]
Thanks for the explanations, @pichuan !

Just to re-iterate to make sure I can understand, 

- it is not expected that DV 1.4.0 and 1.5.0 will output phased variants, i.e. the GT field should still look like 0/1 not 0|1. 
- Instead, phasing is done internally to DV (like the PEPPER step), so that accuracy can benefit. 
- Therefore we should still run a standalone phasing tool (e.g. whatshap, margin phase) to phase the outputs of DV 1.4.0 and 1.5.0, if phasing is needed.
- And internal phasing results are also available if one follows your suggestion above (i.e. peeking under the hood)

Is this correct?

Also, looking forward to the new doc explaining the phasing!

Thanks,
Steve

**Comment by kishwarshafin** [comment]
@SHuang-Broad ,

You are correct. The phasing automated within DeepVariant is actually the haplotagging step that was manually done with whatshap before with `whatshap haplotag`. So, it's read haplotagging that is automated not variant phasing. If you want to phase the variants, then you need to run either whatshap or margin on the output of DeepVariant to obtain the phased variants.

**Comment by kiranpatil222** [comment]
Here Itself two contradictory Answers, 

@danielecook says No need of Phasing as it is "Direct phasing" in v1.4, while @kishwarshafin says only haplotagging is automated **"Not variant phasing"**

Which is is right by the way.?

**Comment by pichuan** [comment]
Sorry for the confusion here.

We're phasing the reads internally to help with DeepVariant accuracy. ("Direct" is referring to that we're doing this now directly in DeepVariant instead of relying on external HP tags from other tools like WhatsHap)

However, DeepVariant currently still doesn't generate phased variant calls. Therefore you won't see "|" in the VCF files. Hopefully this is more clear.

**Comment by kishwarshafin** [comment]
@kiranpatil222 , 

"Phasing" can apply to both reads and variants. DeepVariant automates `haplotagging` which is synonymous for `read phasing` and it does not attempt to phase the called variants or it doesn't do `variant phasing` currently. So you wouldn't get `|` bars in the variants as they are not phased as @pichuan said.

**Comment by SHuang-Broad** [comment]
Given these confusions, I feel like some explanations of what "direct phasing" means, other than in this ticket, would reduce users' questions down the road.

**Comment by akolesnikov** [comment]
@SHuang-Broad, in the upcoming release, we will introduce a section in the DeepVariant documentation that explains "direct phasing" for long reads. 

To summarize:

* Incorporating phasing reads enhances the accuracy of DeepVariant. With the 1.4 version, we introduced direct phasing, thereby eliminating the need to execute make_examples twice and call an external tool in the process. However, internal phasing does not permit the output of phased variants due to the operation being limited to 25,000 base regions at a time, with no synchronization between these regions.

* From version 1.4 onwards, DeepVariant internally handles read phasing, eliminating the need for external phasing to attain the anticipated accuracy.

* If desired, one may opt to run third-party phasing after executing DeepVariant.

**Comment by pichuan** [comment]
Thanks all for the discussion in this thread! I'll close this issue now.
