### ISSUE TITLE
Any prospect about non-human models?

### ISSUE THREAD

**Issue by Axze-rgb** [google/deepvariant#661]
Hello, 

I was wondering ... I know you have a mosquito model that seems to work for when there is a high heterozygosity, but I was wondering if you planned to release those mdels... We, who work with non-model organisms, would be really happy to use DeepVariant. 

Sorry if this is out of place here, I didn't really know where to ask. Feel free to lock 

Cheers

Alex

**Comment by Axze-rgb** [comment]
Hello Andrew,

I am having the same problem... I am trying to call SNPs in a species with a very high density of SNPs, and short read callers do not perform well, they miss a lot of variants in cohort samples, resulting in ridiculously high mutation rates, or the opposite they reject everything as mapping errors.

I am now turning to long reads... I have the hope to obtain a solid golden reference set. That might be useful for training a DeepVariant model with short reads.

I will definitely let you know if I succeed (but that's a big IF).

Thanks
Alex

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Axze-rgb** [comment]
What's your opinion of DeepVariant performance on non model organisms? In its current state? After all people use GATK all the time and we can't say it's particularly tailored for anything else than human.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by AndrewCarroll** [comment]
Hi @Axze-rgb 

It's reasonable to try. There are non-human species for which we know DeepVariant works well,for example [rice](https://cloud.google.com/blog/products/data-analytics/analyzing-3024-rice-genomes-characterized-by-deepvariant),

You are correct that with a good long-read dataset it should be possible to train a short read DeepVariant method. If you are able to make those data and reference available, we could try it.

There are two things to keep an eye on when assessing whether DeepVariant will work well for your samples. First, keep an eye that runtime doesn't get unreasonable. DeepVariant runs per-site, which scales linearly with number of variant positions. 

The second, is to look if there are many cases where DeepVariant is calling many variants as 0/0 which have high support for the alternate allele. It's possible that a high variant density will resemble the signature of copy number variation in humans and since humans don't have much variation relative to the reference, it may become hesitant to call such variants. Really the only way to know is to try and then do some QC on the results.

It's my hope will have better support and some more advanced methods for such genomes in the intermediate future.

**Comment by Axze-rgb** [comment]
I concur this issye has been stalling my thesis for years. Nature high SNP density is a real problem. I have some preliminary promising results with long reads but the bulk of my dara are illumina.

Anyway, thanks for your reply and I will keep you posted.

Cheers

Alex

Sent from ProtonMail mobile

-------- Original Message --------
