### ISSUE TITLE
Pacbio revio data Error

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#672]
hello,
When analyzing PacBio data, I encountered some problems.
I tested the example data provided by DeepConsensus and aligned it using pbmm2(1.12.0). When I analyze with DV1.5, I got an error.
Data: gs://brain-genomics-public/research/deepconsensus/quickstart/v1.2/n1000.subreads.bam
My cmd:
   1. pbmm2 align hs37d5.fasta fa.fofn n1000.subreads_to_ccs_aligned.bam  --sort --rg '@RG\tID:test1\tSM:test1'
   2. /opt/deepvariant/bin/run_deepvariant \
  --model_type PACBIO \
  --ref hs37d5.fasta \
  --reads n1000.subreads_to_ccs_aligned.bam \
  --output_vcf n1000.depv.vcf.gz \
  --output_gvcf n1000.depv.g.vcf.gz \
  --num_shards 32 \
  --intermediate_results_dir intermediate_results_dir
Error:
![1688017046760](https://github.com/google/deepvariant/assets/70870741/e5973e9a-c44b-4a12-9179-f4657f63f4bb)

Could you help me to solve the problem?
Looking forward to your reply.

Thanks.

**Comment by crazysummerW** [comment]
@pichuan 
This is not what I expected, which step went wrong? How can I get the correct result?

**Comment by pichuan** [comment]
Hi @crazysummerW , 
in your first step, you mentioned "pbmm2 align hs37d5.fasta fa.fofn n1000.subreads_to_ccs_aligned.bam --sort --rg '@rg\tID:test1\tSM:test1'". Can you explain to me what you're trying to do in this step?

You also mentioned DeepConsensus. Are you planning to start from your own PacBio subreads BAM?
Unless you're starting with subreads, you don't need to apply DeepConsensus.

If you are starting with PacBio HiFi reads (which I think is most of the DeepVariant users), you should directly map your FASTQ files using pbmm2, which gives you a BAM file, then you apply DeepVariant on the BAM.

However, if you are indeed starting from PacBio subreads, you will need to follow https://github.com/google/deepconsensus/blob/r1.2/docs/quick_start.md to obtain the FASTQ file (which is the output that DeepConsensus gives you). Then, you map the FASTQ file, which gives you a BAM file, then you apply DeepVariant on the BAM.

From your original question, it isn't quite clear to me what you're trying to do here. Can you elaborate?

**Comment by pichuan** [comment]
Hi @crazysummerW ,
I noticed in your title you mentioned "Revio data".

If you're using Revio, DeepConsensus is already run. You don't need to run it again. So, please proceed with your usual mapping + DeepVariant pipeline, and you should be able to get your variant calls that way.

If I'm not interpreting your use case correctly, please let me know.

**Comment by crazysummerW** [comment]
Hi @pichuan ，
Thanks for your reply. You are right！
My test data is subreads.bam, which is from the deepconsensus example data(gs://brain-genomics-public/research/deepconsensus/quickstart/v1.2/n1000.subreads.bam). I'm not sure what platform this example data was generated by. Then, I obtained the FASTQ file from deepconsensus. The file fa.fofn contained the output.fastq name. Then, I mapped the FASTQ file using pbmm2. After that, I applied DeepVariant 1.5 on the BAM file. However, I encountered an ERROR.

I also tested the Revio Hifi data. It succeeded.

I want to know where is the problem in my process when I use subreads.bam analysis?
deepconsensus cmd：
![image](https://github.com/google/deepvariant/assets/70870741/049d45a5-205c-4fff-8acb-a31ca9008fba)

mapping cmd:
pbmm2 align hs37d5.fasta fa.fofn n1000.subreads_to_ccs_aligned.bam --sort --rg '@rg\tID:test1\tSM:test1'

Looking forward to your reply.

Thanks.

**Comment by pichuan** [comment]
Hi @crazysummerW ,

Given this is a question about DeepConsensus, can you repost your question (and give some context on what you're trying to do) in the DeepConsensus GitHub issue?

And, because it is a 4-day weekend for us, please expect some delay for the next person on rotation to reply.

**Comment by pichuan** [comment]
Hi @crazysummerW ,

One more thought:
You mentioned "I also tested the Revio Hifi data. It succeeded." --> If that's the case,  you don't need to re-run DeepConsensus before running DeepVariant, because DeepConsensus is already run on Revio, and in fact, the model deployed on Revio machine is the appropriate one to use.

So, I am not sure why you need to re-run DeepConsensus. Maybe I miss some context here.
That's why I encourage you to post directly on https://github.com/google/deepconsensus/issues instead of here. So that we can understand your use case of DeepConsensus.


One more thing:
When running DeepConsensus, the code snippet you posted is only an intermediate step. You'll need to finish running through the steps to get to the FASTQ file here: https://github.com/google/deepconsensus/blob/r1.2/docs/quick_start.md#run-deepconsensus 

Specifically this step:
```
deepconsensus run \
  --subreads_to_ccs=${shard_id}.subreads_to_ccs.bam  \
  --ccs_bam=${shard_id}.ccs.bam \
  --checkpoint=model/checkpoint \
  --output=${shard_id}.output.fastq
```

is the one that generate the FASTQ you'll use for mapping and then variant calling.

Thanks!

**Comment by amwenger** [comment]
@crazysummerW 

As Pi-Chuan mentioned, DeepConsensus is integrated into the Revio system; so, you will get DeepConsensus reads directly from that system.

The `n1000.subreads.bam` demo dataset being discussed here is from Sequel II.  It is a small number of reads from the human genome.  You should be able to push it through the mechanical steps of alignment and variant calling, but the results will be limited by coverage.

To figure out which mechanical step is broken here,  I would recommend to pass the FASTQ directly rather than through a `fofn` to be more explicit.  The pbmm2 alignment should have input of HiFi reads, not subreads.  So, a typical aligned file name would be `REF.hifi_reads.bam` without a mention of subreads.

> pbmm2 align hs37d5.fasta ${shard_id}.output.fastq aligned.bam --sort

**Comment by crazysummerW** [comment]
@pichuan @amwenger 
Thank you very much for your response.
Perhaps I didn't express myself clearly. I performed two tests. One is HiFi reads, which is from the PacBio public revio data set. Another one is n1000.subreads.bam, which is from DeepConsensus. 
Both datasets have been tested successfully.

Thank you for your help.
Have a great weekend!

**Comment by Jiayi-Wang-Joey** [comment]
Hi there! Thanks for the great work.
I encountered the similar problem here. I have PacBio long-read scRNA-seq data, and I am trying to use DeepVariant on the pseudobulk level. However,`isoseq groupdedup` removed the quality scores in my bam files during preprocessing, which causes error 
As you mentioned above, should I skip the deduplication step (but keep primer removal, tag, refine, barcode correction and sorting) and then align to reference genome using `pbmm2`? Or should I use another deduplication tool that keeps base quality score?

Thanks for any help in advance!

**Comment by armintoepfer** [comment]
`isoseq groupdedup` creates a consensus sequence per group without base qualities. It's not "removing quality scores". I recommend alignment of your FLNCs after `isoseq refine`

**Comment by Magdoll** [comment]
Just chiming here - I agree with @armintoepfer  suggestion to use FLNC reads.

**Comment by Jiayi-Wang-Joey** [comment]
Thank you very much! Then will deduplication after alignment still be needed? For example, one can use`umi_tools dedup` to do deduplication after alignment?

**Comment by pichuan** [comment]
Hi @Jiayi-Wang-Joey , for the PacBio tools specific questions, it might be good to use their GitHub issues, so that other users there can benefit from the answer as well.

Thanks!

**Comment by Jiayi-Wang-Joey** [comment]
Hi, sorry to bother again. I am wondering if I run DeepVariant on my non-deduplicated reads, will the results be reliable or make sense? Probably there will be artifactual mutations?
In short, I should still run DeepVariant on deduplicated reads, right?
