### ISSUE TITLE
very long running time

### ISSUE THREAD

**Issue by tzcoolman** [google/deepvariant#683]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md**:
Yes.
**Describe the issue:**
(A clear and concise description of what the issue is.)
I have several human samples of PacBio HIFI reads with on average 20X depth. I was trying to call out small variants using deepvariant. However, it's been three days and the program is still at 'make_examples' stage.
**Setup**
  - Operating system:
  - DeepVariant version:
  - Installation method (Docker, built from source, etc.):
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
Operating system:
Redhat enterprise v7.9, x86_64
**Steps to reproduce:**
  - Command:
  BIN_VERSION="1.5.0"
  singularity run -B /usr/lib/locale/:/usr/lib/locale/ --bind ${INPUT_DIR} --bind ${OUTPUT_DIR} \
  docker://google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=PACBIO \
  --ref="${INPUT_DIR}"/HG38.fa \
  --reads="${INPUT_DIR}"/0661-349-4156123_PDX_m15.bam \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --num_shards=4 \
  --intermediate_results_dir="${OUTPUT_DIR}"/tmp_dir \
  --make_examples_extra_args="vsc_min_fraction_snps=0.2,vsc_min_fraction_indels=0.2"
I allocated 4 cores and 70GBs to run that program.
I added the VAF thresholds for SNPs and Indels because I read the reported issues:
https://github.com/google/deepvariant/issues/578
  - Error trace: (if applicable)
And here are some most recent results I got from stdout:
I0720 09:27:03.965433 47167827691328 make_examples_core.py:257] 7300984 candidates (8293381 examples) [14.77s elapsed]
I0720 09:27:18.676311 47167827691328 make_examples_core.py:257] 7302320 candidates (8294814 examples) [14.71s elapsed]
I0720 09:28:15.982849 47167827691328 make_examples_core.py:257] 7304006 candidates (8296543 examples) [57.31s elapsed]
I0720 09:30:09.747373 47167827691328 make_examples_core.py:257] 7306537 candidates (8299251 examples) [113.76s elapsed]
I0720 09:30:47.913182 47167827691328 make_examples_core.py:257] 7309312 candidates (8302162 examples) [38.17s elapsed]
I0720 09:30:54.306647 47167827691328 make_examples_core.py:257] 7310398 candidates (8303278 examples) [6.39s elapsed]
I0720 09:31:09.601874 47167827691328 make_examples_core.py:257] 7312009 candidates (8304925 examples) [15.30s elapsed]
I0720 09:31:26.455226 47167827691328 make_examples_core.py:257] 7314037 candidates (8306995 examples) [16.85s elapsed]
I0720 09:31:53.227815 47167827691328 make_examples_core.py:257] 7316209 candidates (8309221 examples) [26.77s elapsed]
I0720 09:32:17.500923 47167827691328 make_examples_core.py:257] 7318273 candidates (8311319 examples) [24.27s elapsed]
I0720 09:32:34.811367 47167827691328 make_examples_core.py:257] 7321518 candidates (8314739 examples) [17.31s elapsed]
I0720 09:32:44.729567 47167827691328 make_examples_core.py:257] 7322681 candidates (8315968 examples) [9.92s elapsed]
I0720 09:33:06.723722 47167827691328 make_examples_core.py:257] 7324476 candidates (8317881 examples) [21.99s elapsed]
I0720 09:33:19.195762 47167827691328 make_examples_core.py:257] 7326384 candidates (8319827 examples) [12.47s elapsed]
I0720 09:33:38.669367 47167827691328 make_examples_core.py:257] 7328314 candidates (8321795 examples) [19.47s elapsed]
I0720 09:33:58.173868 47167827691328 make_examples_core.py:257] 7330371 candidates (8323872 examples) [19.50s elapsed]
I0720 09:34:11.184109 47167827691328 make_examples_core.py:257] 7332195 candidates (8325720 examples) [13.01s elapsed]
I0720 09:34:37.427601 47167827691328 make_examples_core.py:257] 7334598 candidates (8328193 examples) [26.24s elapsed]
I0720 09:34:53.436255 47167827691328 make_examples_core.py:257] 7336041 candidates (8329660 examples) [16.01s elapsed]
I0720 09:35:18.419953 47167827691328 make_examples_core.py:257] 7338676 candidates (8332321 examples) [24.98s elapsed]
I0720 09:35:32.331245 47167827691328 make_examples_core.py:257] 7340143 candidates (8333833 examples) [13.91s elapsed]
I0720 09:35:48.913797 47167827691328 make_examples_core.py:257] 7342460 candidates (8336192 examples) [16.58s elapsed]
I0720 09:36:05.716144 47167827691328 make_examples_core.py:257] 7344261 candidates (8338017 examples) [16.80s elapsed]
I0720 09:36:24.168858 47167827691328 make_examples_core.py:257] 7347004 candidates (8340828 examples) [18.45s elapsed]
I0720 09:36:42.921647 47167827691328 make_examples_core.py:257] 7349633 candidates (8343603 examples) [18.75s elapsed]
I0720 09:36:47.287455 47167827691328 make_examples_core.py:257] 7350149 candidates (8344123 examples) [4.37s elapsed]
I0720 09:37:06.694804 47167827691328 make_examples_core.py:257] 7352217 candidates (8346237 examples) [19.41s elapsed]
I0720 09:37:27.305462 47167827691328 make_examples_core.py:257] 7354095 candidates (8348169 examples) [20.61s elapsed]
I0720 09:37:48.644136 47167827691328 make_examples_core.py:257] 7356001 candidates (8350103 examples) [21.34s elapsed]

My question is: 
Is the long running time due to the complexity of my samples? Do I need to allocate more threads to speed up this process? As I recall make_examples is a single-thread program. 

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?
Yes
**Any additional context:**

**Comment by pgrosu** [comment]
Hi @tzcoolman,

A few things:

$`1)`$ Yes, it can take a long time, as shown here:

https://github.com/google/deepvariant/blob/r1.5/docs/metrics.md#pacbio-hifi

$`2)`$ Yes, `make_examples` is single-threaded and has multiple stages.  You can adjust the parallelism distribution indirectly through the number of shards, which can either match the number of chromosomes (or if more then the sub-regions):

https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-details.md#make_examples

https://github.com/google/deepvariant/blob/r1.5/docs/runtime-by-region.md

$`3)`$ Be careful when adjusting the `vsc_min_*` values $`-`$ yes, higher values will make it faster $`-`$ but the reason those were adjusted in post #578 is because the reference was also lower quality, and you might miss some candidates doing so.

$`4)`$ One way to make things faster would be to balance the CPU core and thread workloads.  CPUs with operating systems have limits at how much they can context switch, before they spend more time resource managing these threads, which is called [thrashing](https://blog.netdata.cloud/understanding-context-switching-and-its-impact-on-system-performance/).  A trick you could do is to run DeepVariant with the `--dry_run` parameter, in order to retrieve the individual commands being run.  Then you can run the `make_examples` step, adjusting the parameters for `parallel` for either CPU cores or threads, as now the number of jobslots (-j) is its preferred method.  `parallel` loves threads and the jobslot (`-j`) argument tries to balance CPU/threads, but the key word here is $`tries`$.  In fact, you can force it one way or anther, but you will have to test that empirically in order to see what gets you the best results for your machine.  The list of the parameters for parallel are shown on the following page:

https://man.linuxreviews.org/man1/parallel.1.html

Hope it helps,
Paul

**Comment by tzcoolman** [comment]
Thank you for the explanation. :-)

**Comment by pgrosu** [comment]
You are very welcome :-)
