### ISSUE TITLE
Why does DeepVariant PASS variants that have such a low read depth ~2 ? 

### ISSUE THREAD

**Issue by amy-houseman** [google/deepvariant#684]
Hello, 

I just wanted to ask if deepvariants PASS/RECALL excludes variants of low depth? I have some variants that passed but have very low depth in that area.

Thanks!
Amy

**Comment by pgrosu** [comment]
Hi Amy,

Basically, this all happens when the candidates are selected during the `make_examples` stage:

$`1)`$ DP (read depth) is set from the total allele counts [in this line](https://github.com/google/deepvariant/blob/r1.5/deepvariant/variant_calling.cc#L307):

```Python
 nucleus::SetInfoField(kDPFormatField, TotalAlleleCounts(allele_count), call);
```

$`2)`$ In the `make_examples` stage, a tensor image (set of matrices) representing information about your reads gets created.  That tensor is usually preinitialized with zeros (0), and then the values get updated with the read information for the rows.  The first 5 rows are the reference representation anyway, before it gets populated with your read representation starting with row 6.  Then this tensor gets processed through the model $`-`$ during the `call_variants` stage $`-`$ generating the genotype probabilities for: homozygous ref, het, and homozygous alt.

$`3)`$ Then in `postprocess_variants` $`-`$ based on the maximum genotype probability from step $`2`$ $`-`$ the [`compute_filter_fields()`](https://github.com/google/deepvariant/blob/r1.5/deepvariant/postprocess_variants.py#L170-L190) function assigns the `PASS` or `RefCall` for the `FILTER` column of the VCF file.

$`4)`$ If you want to filter out these low depth candidates, you can adjust this via the `--make_examples_extra_args=`, by setting some or all of the following parameters to your preference (notice the the default count is already 2, which you are obvserving):

* vsc_min_count_snps (the default is 2)
* vsc_min_count_indels (the default is 2)
* vsc_min_fraction_snps (the default is 0.12)
* vsc_min_fraction_indels (the default is 0.06)
* vsc_min_fraction_multiplier (the default is 1.0)

Here is an example:

```
--make_examples_extra_args='vsc_min_count_snps=3,vsc_min_count_indels=3,vsc_min_fraction_snps=0.12,vsc_min_fraction_indels=0.06'
```

You can read more details about these parameters at the following links:

https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md#why-does-deepvariant-not-call-a-specific-variant-in-my-data

https://github.com/google/deepvariant/blob/r1.5/deepvariant/make_examples_options.py#L178-L202

Hope it helps,
Paul

**Comment by amy-houseman** [comment]
Hi Paul,

Thank you so much for your detailed reply, that really helped me understand it! 

BW,
Amy

**Comment by pgrosu** [comment]
Thank you Amy, glad it helped.

~p

**Comment by kishwarshafin** [comment]
Thank you very much @pgrosu for such detailed answer! You are absolutely right. So, @amy-houseman, in summary, if a candidate variant passes all of the VSC's (very sensitive caller) thresholds and then the neural network prediction is confident on the genotype, `post_processing` will assign a PASS to the variant.

One more thing to note, we train DeepVariant at several downsampled coverages so the model can capture the coverage variability of regions and different sequencing runs. This also makes DeepVariant robust to different coverages. Hopefully that answers your question. 

@pgrosu, again thank you for such detailed and excellent answer. This Q/A is an excellent candidate for our FAQ (https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md). We maintain this as a hub for all common answers. Let us know if it would be OK if we link to your response here in our FAQ.

**Comment by pichuan** [comment]
I'll close this bug now. Thanks all!
