### ISSUE TITLE
Works in dry run, not in functional mode

### ISSUE THREAD

**Issue by Axze-rgb** [google/deepvariant#685]
Hello, 

I am very sorry because this seems like a kind of s*** I could figure out but I have spent the afternoon to no avail. So, the following command WORKS in dry run mode, no error, but fails when in real operative mode. 

```
#!/usr/bin/zsh

OUTPUT_DIR="${PWD}"
INPUT_DIR="${PWD}"

BIN_VERSION="1.5.0"

OUTPUT_VCF=vaga_lab_hifi_standing_variation.vcf.gz
OUTPUT_GVCF=vaga_lab_hifi_standing_variation.vcf.gz
BAM=HiFi_vaga.sorted.bam


time (docker run -v "${INPUT_DIR}":"/input" -v "${OUTPUT_DIR}:/output" google/deepvariant:"${BIN_VERSION}" /opt/deepvariant/bin/run_deepvariant --model_type PACBIO --ref=/input/Adineta_vaga.fsa --make_examples_extra_args=vsc_min_count_snps=2,vsc_min_fraction_snps=0.12 --reads=/input/BAM --output_vcf=/output/OUTPUT_VCF --output_gvcf=/output/OUTPUT_GVCF --num_shards=$(nproc) --logging_dir=/output/logs) 2>&1 | tee -a generallog.log
```
and the output tells me 

```
ValueError: NOT_FOUND: Could not open /input/BAM
[E::hts_open_format] Failed to open file "/input/BAM" : No such file or directory
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/Adineta_vaga.fsa --reads /input/BAM --examples /tmp/tmpbkwxdhbf/make_examples.tfrecord@48.gz --add_hp_channel --alt_aligned_pileup diff_channels --gvcf /tmp/tmpbkwxdhbf/gvcf.tfrecord@48.gz --max_reads_per_partition 600 --min_mapping_quality 1 --parse_sam_aux_fields --partition_size 25000 --phase_reads --pileup_image_width 199 --norealign_reads --sort_by_haplotypes --track_ref_reads --vsc_min_count_snps 2 --vsc_min_fraction_indels 0.12 --vsc_min_fraction_snps 0.12 --task 15

```
the bam file is there, 100% sure, at least to my eyes. But it seems docker fails to see it. Any idea? I have the full log available if needed.

Again, I am sorry because it looks like some easy stuff, but my colleague and I can't find it. 

Thanks a lot

**Comment by kishwarshafin** [comment]
Hi @Axze-rgb ,

instead of setting INPUT_DIR="${PWD}" please provide the absolute path. You can also do echo $INPUT_DIR to make sure the variable is set correctly. Hope this helps.

**Comment by kishwarshafin** [comment]
Also it seems like you are saying your bam files name is “BAM”? Please make sure your file’s name matches the parameters you are setting. Generally the BAM file would be “somename.bam”.

**Comment by Axze-rgb** [comment]
> Also it seems like you are saying your bam files name is “BAM”? Please make sure your file’s name matches the parameters you are setting. Generally the BAM file would be “somename.bam”.

Sorry, I don't understand, I declare a variable BAM=mysorted.bam" isn't it how it should work? I will try with providing the absolute path then. 

Still puzzled why the dry run works.

**Comment by Axze-rgb** [comment]
Ok that seems to be working with absolute path (at least it's making the examples right now). Also, the index of the bam was corrupted! it seems that you declare the BAM but then deepvariant goes to the index. Which makes sense of course, but maybe it would be a good idea to say somewhere in the doc to pay attention to the index? Or return an error like "index not found" rather than "bam not found"? and why dry run didn't catch this? 

Anyway, thank you

**Comment by pgrosu** [comment]
Hi @Axze-rgb,

You did pretty awesome, in terms of how far you got!  Kishwar's suggestions are perfect, and always never hesitate to just post here if you feel you are spending too much time.  It also took me time to understand the DeepVariant ecosystem, but once you see how it all works together it becomes a joy to use.  Basically just freely ask, and someone here can get you there quicker :)

You did great, and only a few minor things:

$`1)`$ So you are correct that will need the index file, as the DeepVariant uses [Nucleus](https://github.com/google/nucleus), which in turn uses [HTSlib](https://github.com/samtools/htslib/blob/master/hts.c#L4508-L4559), and will complain with an error like this (when trying to locate it):

```
[E::idx_find_and_load] Could not retrieve index file for '/input/mysorted.bam'
```

Maybe this helps, so regarding the types of files DeepVariant needs is in the following document:

https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-details.md

$`2)`$ The reason the first time it failed is because the BAM variable wasn't referenced with ${BAM}, and was written as `--reads=/input/BAM`, which is totally understandable to overlook.  I've done that myself too many times to count :)

$`3)`$ Regarding the dry run mode, that [just prints the commands](https://github.com/google/deepvariant/blob/r1.5/scripts/run_deepvariant.py#L492-L497) without actually running them. 

Hope it helps,
Paul

**Comment by kishwarshafin** [comment]
@Axze-rgb,

In bash when you declare a variable as:
```
BAM=HiFi_vaga.sorted.bam
```
Then you need to use it as `${BAM}`, for example:
```bash
echo ${BAM}
# vs.
echo BAM
```
Would show you the difference. This is a good source to know about bash variables: https://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-5.html

In your first run, when it could not locate the BAM file, it gave you the error that it can't locate the BAM file, without locating the bam.

Then when it was able to locate the bam, it told you that the index is corrupted. These two errors are not related, it was not giving you can't locate BAM because your index was corrupted.

Hope this helps.

**Comment by Axze-rgb** [comment]
Waw thanks everyone! really. I will save this.
