### ISSUE TITLE
How to get pileup images

### ISSUE THREAD

**Issue by sophienguyen01** [google/deepvariant#690]
Hi,

I'm running DeepVariant via NVIDA docker image on Horizon sample (Detail of the sample dataset is here: https://horizondiscovery.com/en/reference-standards/products/truq-1-5-tier-reference-standard) . The result is not good as only 5 variants out of 13 expected variants are found, and among 5 found variants, only 1 variant has PASS filter and the other 4 variants have REFCALL filter. 

I read the blog post of pileup image of Deepvaraint. Is there a way for me to see the pileup image of variants in my results. I want to know why the other variants are not detected event though I relaxed some of the parameters: vsc_min_fraction_snps = 0.03 instead of 0.12 as default, --min_base_quality=5 instead of 10 as default. Also, I want to see why the variants has REFCALL filter instead of expected PASS filter. 

Thanks

**Comment by pgrosu** [comment]
Hi Sophie,

DeepVariant calls variants based on a trained model for different technologies.  I'm not sure it has a model for Horizon Tru-Q 1, and only has models for the following technologies (`WGS`, `WES`, `PACBIO`, `ONT_R104`, `HYBRID_PACBIO_ILLUMINA`):

*   NGS (Illumina) data for either a
    [whole genome](docs/deepvariant-case-study.md) or
    [whole exome](docs/deepvariant-exome-case-study.md).
*   [RNA-seq Case Study](docs/deepvariant-rnaseq-case-study.md) for Illumina
    RNA-seq.
*   PacBio HiFi data, see the
    [PacBio case study](docs/deepvariant-pacbio-model-case-study.md).
*   Oxford Nanopore R10.4.1 Simplex or Duplex data, see the
    [ONT R10.4.1 Simplex case study](docs/deepvariant-ont-r104-simplex-case-study.md)
    and [ONT R10.4.1 Duplex case study](docs/deepvariant-ont-r104-duplex-case-study.md).
*   Hybrid PacBio HiFi + Illumina WGS, see the
    [hybrid case study](docs/deepvariant-hybrid-case-study.md).
*   Oxford Nanopore R9.4.1 data by using
    [PEPPER-DeepVariant](https://github.com/kishwarshafin/pepper).

Regarding seeing the pileup images, the command is the following -- which is based [on the following document](https://github.com/google/deepvariant/blob/r1.5/docs/show-examples.md):

```
INPUT_DIR="${PWD}/YOUR_INPUT_PATH"
OUTPUT_DIR="${PWD}/YOUR_OUTPUT_PATH"

BIN_VERSION="1.5.0"

sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" /opt/deepvariant/bin/show_examples \
  --examples=/output/intermediate_results_dir/make_examples.tfrecord-00000-of-00001.gz \
  --example_info_json=/output/intermediate_results_dir/make_examples.tfrecord-00000-of-00001.gz.example_info.json \
  --output=/output/pileup --num_records=20

# And then your images are here:
ls "${OUTPUT_DIR}"/pileup*.png
```

There are many reasons why candidate variants are not detected:

1. The quality of reads in the BAM file.
2. The reference file used to generate the BAM is different than the one used with DeepVariant.
3.  There might not be many SNPs left supported by informative reads.
4. Besides requiring that you have a model for your technology, how many variants do you see in IGV that are based on high-quality reads?

The reason for RefCall is because the genotype for those calls is 0/0, as per the postprocessing that happens as the last step in DeepVariant.

Hope it helps,
Paul

**Comment by pichuan** [comment]
Hi @sophienguyen01 

I am not familiar with https://horizondiscovery.com/en/reference-standards/products/truq-1-5-tier-reference-standard so I clicked on it and read a bit on the page. From https://horizondiscovery.com/-/media/Files/Horizon/resources/Product-data/Notification_Tru-Q_update_effective_from_31st_March_2021.pdf which listed the Allele Frequency, it seems to me that these variants you're try to detect are NOT germline variants?

If so, that would explain why DeepVariant wasn't able to detect many of them, especially given the default thresholds.

Note that DeepVariant (and our released models) are trained for germline variant calling use cases, we don't currently support non-germline variant calling. You're welcome to tweak the thresholds and try out different ways of using the codebase, but please be aware that our models are not designed for that.

Hopefully this is helpful. Feel free to reopen if you have further questions!

**Comment by sophienguyen01** [comment]
hi @pichuan,

That makes a lot of sense. 

I already lowered the threshold but it seem like this is not a way to go. My plan is to retrain the model on our dataset and hopefully it performs better.

**Comment by pgrosu** [comment]
This seems to be a QC assay for detecting specific allele frequencies of cancer variants.  As Pi-Chuan mentioned, these would be somatic variants and usually one cannot rely on the ploidy to correlate with allele frequency given there might be a mixture of cancer subpopulations.  I wonder what the genotype probabilities would even mean.  I'm not sure what a good VCF truth set of candidates might be for this specific subset of cancer variants to be used for training a model.  It probably could be simulated as tumor purity is not consistent in its microenvironment -- unless of course you have well-validated samples.  In any case I'd be curious to see where this journey might lead.
