### ISSUE TITLE
Decoy Reads are added to the wrong contig for hs37d5_decoy.fasta

### ISSUE THREAD

**Issue by Npaffen** [google/deepvariant#695]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md**:

**Describe the issue:**
When calling a bam file aligned to hs37d5_decoy.fasta so the hs37d5 version with decoys. The produced vcfs contains no decoys despite there are such reads in the file but instead those calls were aligned to chrY. This is problematic in several ways. Thereby one can't distinguish between chromosome Y and decoy and it is impossible to determining the sex of the sample using just the vcf.     

**Setup**
  - Operating system: Linux 5.15.0-78-generic #85-Ubuntu SMP
  - DeepVariant version: 1.5.0
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
1. Align any WGS sequencing reads to hs37d5 with decoys. Maybe this can be repeated with any GRCh38 reference fasta containing decoys as well but I did not test that. 
2. Run deepvariant with default parameters to call the file.
3. Open the vcf and see if the file contains decoy regions or not and observe if such calls were catched by chromosome Y
4. 
**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by pgrosu** [comment]
Hi Nils,

This is possibly because most of the decoy contigs are excluded by default through the following file (because of possible large incorrect mappings):

https://github.com/google/deepvariant/blob/r1.5/deepvariant/exclude_contigs.py

More of this is discussed in [issue 37](https://github.com/google/deepvariant/issues/37).

In this situation, besides trying with GRCh38 -- which could be a good check -- some of your reads probably have better alignment to the decoy contigs with suboptimal alignment to chromosome Y (or vice-versa).  One thing you could try is to indirectly determine the sex of the sample via a threshold that compares differences between allele depth (AD) and depth of coverage (DP) across variants in the sample.  If that is not enough (in case they are equal), then a comparison between GQ and QUAL might provide better granularity.  The idea is that suboptimal vs optimal read alignments for chrY might work as an inference of sex.  For this to work, you would need to create a test and validation set of samples where the sex is known to extract what the threshold would be.  I'm assuming these are not in the pseudo-autosomal (PAR) regions, as both chrX and chrY are identical in the PAR regions of the genome assembly.   As a last resort you can rename the decoys in your BAM and reference with something different than the ones in the excluded file, so that they would be included in the VCF.

Hope it helps,
~p

**Comment by AndrewCarroll** [comment]
Hi @Npaffen 

DeepVariant won't by default call on the decoy contigs. That is behaving as expected. If you really need to call with the decoy contigs, you would have to change their name so that they don't match the exclude list.

I am not sure what you mean by the calls are caught on chrY. The reads that map to a decoy should not be used. How is this manifesting for you, is there a variant call on chrY which is supported ONLY by reads that come from a decoy. Is there an IGV screenshot or a small BAM snippet that might illustrate the effect?

Thank you,
Andrew

**Comment by akolesnikov** [comment]
Closing the issue due to inactivity. Feel free to reopen if needed.
