### ISSUE TITLE
Question about running DeepVariant on AWS

### ISSUE THREAD

**Issue by sophienguyen01** [google/deepvariant#696]
Hi,

I'm testing running DeepVariant on some of our genomic datasets. . I found out through reading the quick start guide that I can download the docker image of Deepvariant and run this docker image on AWS EC2 instance. In the guideline, it uses t2.medium EC2 instance, I tested and was able to run using the test files. This works with t2.medium because the test cases don't go through the first step, which require GPU to make examples.

I want to know that for the real cases with bigger memory requirement, what is the **recommended EC2 instance type** I should use in order to run DeepVariant? 

Also, if I want to start with fastq sequencing file, is there an existing tool in the docker image to convert from .fastq to .bam?

**Comment by pgrosu** [comment]
Hi Sophie,

Regarding requirements for resources, it all depends on how large your data is that you need to process.  Also only the middle step `call_variants` can utilize 1 GPU if you prefer, but you can run the CPU version of DeepVariant.  Below are the two Docker versions:

[google/deepvariant:1.5.0](https://hub.docker.com/layers/google/deepvariant/1.5.0/images/sha256-6a27bc877db9191c8fad0fe5f98dce6192fd4eb6392551e1a3add8d01e08af2e?context=explore)

[google/deepvariant:1.5.0-gpu](https://hub.docker.com/layers/google/deepvariant/1.5.0-gpu/images/sha256-312af65c01d27e4fc8bb34a4c933ca708bd24d2e7d8ac3076c9c7c078afa20e9?context=explore)  

Regarding machines, people have had luck with [r4.8xlarge EC2 (32 cores and 244 GB of RAM)](https://github.com/google/deepvariant/issues/167#issuecomment-479738587), especially since the different steps of DeepVariant [utilize different amounts of resources](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-details.md).

So FASTQ files are used to align to a genome reference sequence such as [GRCh38](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000001405.26/) to generate BAM files.  The recommended on is `GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz`, which you can download from the following location:

https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/

Regarding aligning your FASTQ file, that depends on your type of sequencer.  If you are using PacBio HiFi it is recommended you use [pbmm2](https://github.com/PacificBiosciences/pbmm2), otherwise you can use [bwa](https://github.com/lh3/bwa).

Regading Docker containers for both, here are a couple of links:

[pbmm2](https://quay.io/repository/biocontainers/pbmm2?tab=tags)

[bwa](https://hub.docker.com/r/biocontainers/bwa/tags)

Otherwise you can always use BioConda:

[pbmm2](https://anaconda.org/bioconda/pbmm2)

[bwa](https://anaconda.org/bioconda/bwa)

Hope it helps,
Paul

**Comment by pgrosu** [comment]
Think of a CPU (core) as a basket of functions your program can utilize to take an input data to an output.  A GPU has many more baskets, but containing fewer, more specialized functions.  A high-end CPU can have 64 cores (baskets), while a nice high-end GPU can have between 2,560-16,384.  Thus a GPU can operate on a specialized set of functions much faster in parallel, but with one caveat.  The thing is that your program would need to be coded and compiled for a GPU.  DeepVariant only can utilize 1 GPU for the middle stage (`call_variants`) of the three stages, as the other two (`make_examples` and `postprocess_variants`) are single-threaded (meaning they are CPU-based).  Regarding the compute instance of EC2, that is a high-end one, but you need to experiment to see what works for you and is within your budget.  DeepVariant can also utilize a lot of memory depending on what stage it is running, and how much of the genome your are covering.

**Comment by sophienguyen01** [comment]
Thanks Paul for your answer,

That's clear now. That means I need to choose EC2 instance type with 1 GPU because instance with more than 1 GPU does not have any better impact on DeepVariant's performance.

**Comment by pgrosu** [comment]
Glad it helped Sophie!  Currently yes, though DeepVariant can easily be ported to multiple GPUs with many other optimizations, that would probably be at a later time.  Even if you think about the called variants, those are locus-specific and multiple regions can run across multiple GPUs.  For counting alleles in the `make_examples` stage, that would be the same thing that can be taken advantage of [as illustrated by the benchmark of its sub-stages](https://github.com/google/deepvariant/blob/r1.5/docs/runtime-by-region.md) -- and there are GPU-based Smith-Waterman aligners that are 8x-20x faster than CPU.  Distributing for speedup the collecting/transforming/sorting in the last stage of post-processing the variants is only natural, and that can subsequently also provide logarithmic combines -- including other optimizations, which would be aided by utilizing changes in the previous stage.  So the future is very bright, but again that would be something for a later time :)

**Comment by AndrewCarroll** [comment]
Hi @sophienguyen01,

Just a few additional notes. It's been awhile since I run things on AWS. 

My instinct is that the most cost-effective instance will turn out to be m7i.4xlarge. m7i.8xlarge will likely be slightly more expensive, but should scale close to linear in speed. 

If you have PacBio data and experience a failure, you might want to try R7iz.4xlarge or R7iz.8xlarge.

The GPU instances will be faster, but I suspect not necessarily cost-optimal. So it depends on what you are looking for.

**Comment by akolesnikov** [comment]
Closing the issue due to inactivity. Feel free to reopen if needed.
