### ISSUE TITLE
WES model for Element AVITI™ System

### ISSUE THREAD

**Issue by Fred-07** [google/deepvariant#703]
Hello,

Deepvariant is reported to work well with WGS data from the Element AVITI™ System.
#623 
https://www.biorxiv.org/content/10.1101/2023.08.11.553043v1.full.pdf

How does Deepvariant perform with AVITI WES data?
Is it possible to use the current WES model or is it still required to update the WES model?

Thanks!

**Comment by pgrosu** [comment]
Hi @Fred-07,

Since the [Element AVITI System](https://www.elementbiosciences.com/blog/whole-exome-sequencing-101-cost-effective-dna-sequencing-to-understand-genetic-disease) seems to be dependent on external exome enrichment solutions, the answer would be it depends.  Element seems to [prefer Roche for library preparation](https://www.elementbiosciences.com/news/elements-new-aviti-system-shows-seamless-compatibility-and-high-performance-with-kapa-library-preparation-kits-in-multiple-ngs-applications) - also used in the paper - and which has its [own enrichment solution](https://sequencing.roche.com/us/en/products/group/kapa-hyperexome.html).

Now if the exome selection is optimal, and coverage passes the Fold-80 base penalty (i.e. how much more required sequencing is necessary for 80% of the target bases to achieve desired mean coverage among samples), then the WES model should work given some in-house validation - as that the reads have a higher quality (as shown below), and have worked for WGS:

![image](https://github.com/google/deepvariant/assets/6555937/daa31daa-7abe-46fa-8037-f6ed49112c6f)

Hope it helps,
Paul

**Comment by pichuan** [comment]
Hi @Fred-07 ,
Yes, you can use our existing WES model. @AndrewCarroll can add more details later.

**Comment by AndrewCarroll** [comment]
Hi @Fred-07 

When we investigated Element sequencing for exomes with the out-of-the-box Illumina models, we generally observed accuracy that was as good or better as that observed with Illumina without any retraining.

With v1.5 the whole genome models do include joint training with Element data, and including element in WGS training does make Element accuracy somewhat further improved. I expect we'll try to get Element exomes and add them into the exome model training in the future, but for now I think you will see good performance with the existing exome model.

If you do have any feedback on performance with Element exomes, please let us know.

**Comment by Fred-07** [comment]
Thanks for the feedback and the good news about the model. I plan to get some WES data from Element for testing.
