### ISSUE TITLE
Question on trio analysis using DeepVariant and Deeptrio

### ISSUE THREAD

**Issue by GaianX39** [google/deepvariant#704]
I ran my DeepVariant and Deeptrio pipeline following the "quick start" guidance, and I noticed that in my real trio case analysis, the variants called by Deeptrio outnumbers those called by DeepVariant (especially the RefCalls), for both the parents and child. Why did this happen? And I also noticed that in issue #699 your team recommand to perform trio analysis either through DeepVariant+GLnexus or Deeptrio with truth sets to be compared. I wonder how to use "truth set" (and what does the truth set means? like dataset from GIAB?) to check my Deeptrio results? And which method will you consider as the best in both accuracy and time cost in trio analysis? Really appreciate that if your team could answer these questions!

**Setup**
  - Operating system: linux
  - DeepVariant version: 1.5.0 (in Deeptrio as well)
  - Installation method: Singularity version
  - Type of data: WES

**Comment by pgrosu** [comment]
Hi @GaianX39,

Did you use WhatsHap to improve accuracy?  The recommended way is to run `DeepVariant -> WhatsHap -> DeepTrio`, as [noted here for adding an additional signal of information for variant qualification](https://github.com/google/deepvariant/issues/689#issuecomment-1660748817).  DeepTrio is complex, as it combines the child and parent information together, since models were trained with the assumption that the child resides in the middle between the two parents (as in the pileup image shown below):

![image](https://github.com/google/deepvariant/assets/6555937/080684de-68b9-4f8b-8c45-1625484d96af)

When that happens, candidate alleles that were generated by `make_examples` could have lower quality probabilities (going through the model), as by design it is selected across all samples (which might not yield high probability for a genotype).

Truth set just means what expected variants from a gold standard you might have for your study, or in case of DeepTrio's that were [used to train the model](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-training-case-study.md#training-set), as listed here:

https://github.com/google/deepvariant/blob/r1.5/docs/deeptrio-details-training-data.md

Another way you can compare against is to use `DeepVariant -> WhatsHap -> DeepVariant -> GLnexus` [as shown here](https://google.github.io/deepvariant/posts/2021-02-08-the-haplotype-channel/).  The truth sets are there based on expected results for a controlled experiment.  If you know the variants do not follow normal Mendelian inheritance patterns, such as de novo ones, then you would need more replicate samples to validate against - which might also require validation via other assays.

Let me know where I should add more clarification, as there are many ways to expand on this.

Thanks,
Paul

**Comment by GaianX39** [comment]
Hi Paul
Thanks for all the informations. As learnt from above, I should use the "DeepVariant -> WhatsHap -> DeepTrio" pipeline for better accuracy of the Deeptrio, as it do not support the functionality of reading haplotagging. But the DeepVariant can do it since 1.4.0, which means in case of trio analysis, "DeepVariant + GLnexus" will already be most accurate way currently, am I get it right?

**Comment by pgrosu** [comment]
Hi Gaian,

You're absolutely right!  Direct phasing is happening internally from version 1.4 of DeepVariant, so it's only necessary for DeepTrio (with the additional `--use_hp_information` flag following `whatshap` processing), while `DeepVariant -> GLnexus` should work as is.

Good catch!
Paul

**Comment by GaianX39** [comment]
Thanks a lot! Really appreciate for that!

**Comment by pgrosu** [comment]
You are very welcome, and please don't hesitate to reach out again if you have more questions. 

Paul

**Comment by AndrewCarroll** [comment]
Hi @GaianX39 

I wanted to add just a few things. 

First, in our next release we're planning to improve the de novo detection aspects of DeepTrio, so if that's of interest to you, please stay tuned for this. 

Using GIAB to validate performance is only something that you can do when sequencing the known samples (e.g. HG002-HG003-HG004). If you have those, then please follow the "Running Hap.py" steps at the end of most quick starts (e.g. [Hap.py section of WGS case study](https://github.com/google/deepvariant/blob/r1.5/docs/deeptrio-wgs-case-study.md#perform-analysis-with-happy-against-421-truth-set). To do this with a joint called VCF, we use BCFtools to subset the VCF to individual samples (e.g. `bcftools -s ${SAMPLE_ID}`)

For runtime, we have benchmarks in the Figure 6 of the [DeepTrio paper](https://www.biorxiv.org/content/10.1101/2021.04.05.438434v1). Here, we see DeepTrio takes about 1.5x the time that running DeepVariant on all 3 samples does. The cost should be a similar multiple as this is run on the same hardware. What this translates to in cost depends on how you run it (local, which cloud provider and with which deals, etc...)
