### ISSUE TITLE
Newbie advice

### ISSUE THREAD

**Issue by zoeward-nz** [google/deepvariant#712]
Hi,

Sorry this is more of a question than an issue but I just want to understand that I am using Deepvariant correctly.
I read in #704 you said "Direct phasing is happening internally from version 1.4 of DeepVariant, so it's only necessary for DeepTrio (with the additional --use_hp_information flag following whatshap processing), while DeepVariant -> GLnexus should work as is."

I am trying to run trios using Deepvariant/Deeptrio for the first time. With the above statement are you recommending running Trios with DeepVariant -> GLnexus?

Could you also give some guidance as to how we "or the non-PAR regions of the sex chromosomes (X and Y), we recommend running these providing only the parent who contributed the child's chromosome (e.g. for chromosomeX, only the mother and son samples and for chromosomeY only the father and son samples)."

Does this mean if we have a trio with son we have to remove Dad's X?

**Comment by AndrewCarroll** [comment]
Hi @zoeward-nz 

We're close to a next release of DeepVariant and DeepTrio that will make some improvements to each, some of which will be relevant here. I assume you are using PacBio data here. 

DeepTrio with PacBio will still require you to haplotag the BAM files with whatshap in the two-stage process as before. DeepTrio will give better overall accuracy than DeepVariant for the trios, especially at lower coverages. The coming update will also improve performance for de novo variants. It should be the most accurate way to analyze the sample, but because you will need to do the call-phase-call approach, and because you will need to manage the non-PAR regions, it will be slower and less convenient.

To run on non-PAR with DeepTrio, the recommendation is to run DeepTrio with a --regions that covers all autosomes and the PAR region with both samples. For the non-PAR regions, it would be to use the --regions flag to run the non-PAR ChrX with only the child and mother sample (omit the father's BAM). You won't need to modify the BAM files themselves by using the --regions flag, but you will need to run twice.

You may find this too cumbersome, running DeepVariant on the samples, especially with 30x coverage, should give highly accurate results as well. In the coming release, there will be flags which enable you to specify non-PAR regions for male samples. 

In terms of making a decision of which to run, you might want to start with DeepVariant and look at the performance characteristics that you care most about (e.g. number of de novos calls). If you are finding too many de novo calls difficult to wade through, you might want to go ahead and try the more involved trio process. 

Thank you and please let me know if you have any questions,
Andrew
