### ISSUE TITLE
Retraining DeepVariant using a long read truth set, can it be done?

### ISSUE THREAD

**Issue by Axze-rgb** [google/deepvariant#716]
Hello, 
I think the answer is "yes I could". To be quick ... I have 25 datasets of high-coverage illumina data. But mapping them on the rotifer genomes is a nightmare, it seems there are many mismappings. But ... we finally start to have enough material to get long ONT precise reads (the very last one that is accurate at 99.99%, just like a giant PCR); those are much less likely to mismap, and Clair3 seems extremely powerful and precise to call.

Therefore, we could consider the call from long reads as a "truth set". 

My point is if I give deep variant the ONT "truth set" and then the mapping of short illumina reads. Could it be retrained to understand the mapping and calling issues with this kind of genome?  I don't have a "rule" such as Mendelian violation because my organism is clonal. Therefore, the only possibility of having a "truth set" is to trust long reads mapping (Sanger sequencing doesn't work well either; we don't know why). 

Is it something doable? I could use other things, such as Python random forests, as suggested by a colleague, but since you have spent a lot of time trying to help me, before, I found it gentlemanly to ask if we can use Deepvariant.
I think the answer is "Yes, I could". To be quick ... I have 25 datasets of high-coverage Illumina data. And I'm not sure I will get those datasets resequenced in long reads with enough coverage and N50 (for another reason we don't understand well, DNA extraction is harrowing in rotifers; it often fails or yields highly damaged DNA). Therefore, if I could retrain a model to use the Illumina datasets, that would be great. 

My worries are: what does it take in terms of hardware to retrain Deepvariant? I don't have access to a huge GPU. 

I found this tutorial: https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-training-case-study.md 

but I am not sure if it is adapted to my case, streamlined, or can be done here, if I understand well this example relies on using Google machines, right?

EDIT: to be perfectly clear it seems to me I need some discussion to understand what you take as a truth set and how you define a bed file with the confidence region. I also would like to know if everything can be done locally

**Comment by AndrewCarroll** [comment]
Hi @Axze-rgb 

Conceptually, it is possible, and most of the challenge (which will be substantial) will be in constructing a truth set that is reliable enough, and in things like whether mapping will be reliable enough or the amount of variation is samples. Also, as I really you might be looking for subclonal variants instead of full germline variants. If this last piece is the case, then re-training with DeepVariant is likely not a good fit.

In terms of hardware itself, when warmstarting training from a checkpoint, it's generally possible to train a new model with a single GPU. The GPU itself used in the case study is relatively old (a P100), several generations older than the current A100 or H100 GPUs. However, that GPU was designed for industry applications, I am not sure how it would stack up against a current consumer GPU.

However, one thing to check - how many of your Illumina reads are MAPQ0 versus MAPQ 1-5 versus MAPQ5+. With default parameters, DeepVariant doesn't see Illumina reads with MAPQ <5. With long reads we were able to lower that threshold to MAPQ1, but if you're not getting many reads with more than MAPQ5 and especially if you're not getting reads more than MAPQ0, then the reads can't be mapped reliably enough for DeepVariant to attempt calling, whether the model is retrained or not.

**Comment by Axze-rgb** [comment]
Thanks for your reply. Hopefully reads seem to map with a MAPQ of 60 so Deepvariant should see them. We believe the issue is high SNP density making some standing variant hard to call. It's also very possible there is no signal, i.e. the bdelloids have evolved a very low mutation rate and we are chasing ghosts. Since they reproduce asexually (at least in the lab) by automixis, it is a possibility. 

Anyway, the ONT sequencing is ongoing.

**Comment by AndrewCarroll** [comment]
Hi @Axze-rgb 

OK, if that is the case, it's possible that re-training will help. If you have a GPU, hopefully you will be able to re-train. Please let me know if you have questions when you attempt that.
