### ISSUE TITLE
Filtering variants out if they show strand bias 

### ISSUE THREAD

**Issue by amy-houseman** [google/deepvariant#719]
Not an issue! Just a question.

Hello,

I was wondering if you knew of any ways to filter out variants based on strand bias? Is there a method to this - I can look visually at the BAM files but I have a lot of samples so wondered if anyone had done anything like this before - or whether there were any stats in the VCF outputs that would allow me to assess this?

No worries if not! I thought I would just ask :)
Amy

**Comment by AndrewCarroll** [comment]
Hi @amy-houseman 

The strand of the read is one of the input channels in DeepVariant, so it is able to see that information and to learn the effects of strand bias on variant calling during training. For more information on what data is seen by DeepVariant, you can see the blog [Looking through DeepVariant's eyes](https://google.github.io/deepvariant/posts/2020-02-20-looking-through-deepvariants-eyes/).

We don't write the strand information itself in the variant calls. For filtering, we instead recommend using the GQ field, which we find to be well calibrated with the probability of genotype error. Because DeepVariant sees the strand information, it will incorporate this into its confidence about the variant.

If you have some specific aspect of your problem which you think the strand of reads will behave different from the genomes and exomes DeepVariant is trained on, and you want to do independent filtering, you would have to find some other method to annotate the strand information as DeepVariant does not write this directly to the VCF.

**Comment by amy-houseman** [comment]
Amazing, thank you! Amy
