### ISSUE TITLE
Why does the reference/alternate not add up to the read depth column?

### ISSUE THREAD

**Issue by amy-houseman** [google/deepvariant#732]
Sorry I've submitted this wrong!

But basically I was wondering why sometimes the reference/alternate read depth column values do not always add up to the read depth column such as here: 

![image](https://github.com/google/deepvariant/assets/110385188/818edea3-82d3-4877-9ab6-963226f12706)

**Comment by akolesnikov** [comment]
Could you paste the entire line from VCF?
Also, if possible attach a snapshot of IGV showing this position.

**Comment by amy-houseman** [comment]
Hi, 

The full line is: 

![image](https://github.com/google/deepvariant/assets/110385188/e9cfda93-d778-4d10-9ffa-d68f98ed1d95)

In terms of the bams, this is the bam before deepvariant realignment:
![before_deepvariant](https://github.com/google/deepvariant/assets/110385188/a40e77cb-4bf6-46b9-94bd-027403b41eef)

and this is after deepvariants ' realignment:
![after_realignment](https://github.com/google/deepvariant/assets/110385188/0c5bed25-847b-4a4e-9e2f-5632571e73bf)

Thanks!!
Amy

**Comment by akolesnikov** [comment]
It looks like there is an insertion at the same position in the 5th read from the top, and most likely a soft clip in the 3d read from the top. Total Depth is Ref depth + all allele depths. In this case there 7 reads supporting ref, and 2 reads supporting the SNP. There are two more reads that support different alleles. Those different alleles are not reported because they didn't pass the filter. The allele is considered if the base quality is higher than a threshold and number of supporting reads is greater than 2.

**Comment by amy-houseman** [comment]
ah amazing, thank you so much! That makes a lot of sense now! Amy

**Comment by akolesnikov** [comment]
You are welcome! I will close the issue. Feel free to reopen if needed.
