### ISSUE TITLE
splitting bam for deepvariant input

### ISSUE THREAD

**Issue by themkdemiiir** [google/deepvariant#744]
Hello,

I am working on a next-flow pipeline and have a question about using the deep variant tool. Would it still work correctly if I split the bam file into chromosomes, or if it's not designed to be used with a splitter? Additionally, I would like to know if there would be any speed issues between the two options. Using the splitter chromosomes would be faster, but I am unsure.

**Comment by akolesnikov** [comment]
Hi @themkdemiiir,

Although, it is absolutely possible to split the bam into chromosomes and run them separably there are better way to make a pipeline. There are 3 binaries that DeepVariant executes: make_examples, call_variants, and postprocess_variants. You may run those binaries from the docker.

* make_examples is highly parallelized already. You may shard it to as many shards as needed by simply specifying the output of make_examples as sharded by adding @<num of shards> to the file name and add `--task` flag that specifies the task number for each shard. 
* call_variants  will be run with the same number of shards.
* postprocess_variants has to be run in a single process.

Here is an example of running shard 11 of make_examples and call_variants broken into 200 shards:

```
bin/make_examples \
--examples /tmn/your_examples.tfrecord@200.gz \
--mode calling \
--reads /tmp/your_input_bam.bam \
--realign_reads \
--ref=/tmp/your_reference.fna \
--task=11

# Input for each instance of call_variants is the output of one instance of make_examples:
bin/call_variants.par \
--[batch_size=32 \
--checkpoint <Path to the model checkpoint or saved model>.ckpt \
--examples /tmp/your_examples.tfrecord-00011-of-00200.gz \
--outfile /tmp/your_call_variants_output.cvo.tfrecord-00011-of-00200.gz

#  Input for for postprocess would be the output of all instances of call_variants:
/tmp/your_call_variants_output.cvo.tfrecord@200.gz
```

**Comment by pichuan** [comment]
Hi @themkdemiiir ,
@akolesnikov already mentioned this in his previous answer -- it's totally possible to split by chromosomes first. Especially if that works better for your workflow.
(I know for many users, their workflow already split by chromosomes, so it makes sense to go from these BAMs that are per chromosome.)

@akolesnikov 's answer above further explains that DeepVariant does its own sharding for any BAM inputs. You can run DeepVariant on a BAM that includes all chromosomes, but you can also do that on a BAM that include one chromosome (and then combine the VCFs later if you like).

Please feel free to follow up if it's not clear. I'll close this issue for now.

**Comment by themkdemiiir** [comment]
Would there be any difference if I gave it all chromosomes or only one in vcf outputs? Also, how does it shard the BAM file according to chromosomes or regions?

**Comment by pichuan** [comment]
@themkdemiiir if the input BAM has only one chromosome, then the output VCF will only be able to call variants in the input BAM (therefore will only have calls from one chromosome).

But that allows you to parallelize. For example, you can run 22 separate DeepVariant runs from 22 input BAMs, each of them are chr1-chr22. Then at the end, you'll have 22 VCFs, each of them have calls from chr1-chr22, and you can combine them at the end if you want to have one VCF.

What I describe above will be the way you split by chromosome when using DeepVariant. (Basically you'll need to split the input BAMs by yourself, using tools like `samtools`)



Once you provide DeepVariant one input BAM, DeepVariant has some internal way of further parallelizing/sharding its computation. This is controlled by the `--num_shards` flag of `run_deepvariant`. We recommend not using more than the number of processors when using `--num_shards`. The way that @akolesnikov described about the `--task` flag is a more advanced way. I actually don't necessarily recommend you trying to use the `--task` flag directly because it can be confusing. 
The `--num_shards` flag of `run_deepvariant` is something that you can change.

Hopefully this is helpful.

**Comment by themkdemiiir** [comment]
> Hi @themkdemiiir,
> 
> Although, it is absolutely possible to split the bam into chromosomes and run them separably there are better way to make a pipeline. There are 3 binaries that DeepVariant executes: make_examples, call_variants, and postprocess_variants. You may run those binaries from the docker.
> 
> * make_examples is highly parallelized already. You may shard it to as many shards as needed by simply specifying the output of make_examples as sharded by adding @ to the file name and add `--task` flag that specifies the task number for each shard.
> * call_variants  will be run with the same number of shards.
> * postprocess_variants has to be run in a single process.
> 
> Here is an example of running shard 11 of make_examples and call_variants broken into 200 shards:
> 
> ```
> bin/make_examples \
> --examples /tmn/your_examples.tfrecord@200.gz \
> --mode calling \
> --reads /tmp/your_input_bam.bam \
> --realign_reads \
> --ref=/tmp/your_reference.fna \
> --task=11
> 
> # Input for each instance of call_variants is the output of one instance of make_examples:
> bin/call_variants.par \
> --batch_size=32 \
> --checkpoint <Path to the model checkpoint or saved model>.ckpt \
> --examples /tmp/your_examples.tfrecord-00011-of-00200.gz \
> --outfile /tmp/your_call_variants_output.cvo.tfrecord-00011-of-00200.gz
> 
> #  Input for for postprocess would be the output of all instances of call_variants:
> /tmp/your_call_variants_output.cvo.tfrecord@200.gz
> ```

So how could I merge the output of the call_variants step?
