### ISSUE TITLE
Checkpointing / resuming analysis

### ISSUE THREAD

**Issue by dbrami** [google/deepvariant#749]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6/docs/FAQ.md**:

**Describe the issue:**
I am struggling to get DeepTrio to run to completion on a small dataset. It completes at the end of call_variants.py but my system just collapses when at postprocess_variants.
Through using --dry_run=true, I'm able to keep going only after being sufficiently confident the last step has completed without error.
So in short, is it possible to re-run the wrapper command and have the analysis pipeline pick up where it left off? 

**Setup**
  - Operating system: Rocky Linux 8
  - DeepVariant version: 1.6
  - Installation method (Docker, built from source, etc.): through Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) illumina, 151bp, same reference as case studies
  - RAM 64 GB
  - CPUs 32 (c6i.8xlarge)

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?** Yes they do. they complete because they are small. 
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**
Unfortunately, i cant run it on g4dn.8xlarge available to me since that EC2 running Amazon Linux 2, and GPU DeepVariant seems to need Ubuntu.
In short, a "step_x_completed" sentinel file at end of each step would be great IMO.  

Thanks,
-Daniel

**Comment by pichuan** [comment]
Hi @dbrami ,

Thanks for the question. To make sure you can restart from each of the steps, you're on the right track : using `--dry_run=true` to find out what to run is useful.

The other part that's missing is: when you want to rerun the next steps (say `call_variants`, after `make_examples` are done), you'll want to be able to access the outputs of the previous step. If you're using the one step `run_deepvariant` or `run_deeptrio` wrapper, the way you can do it is to make sure you specify `--intermediate_results_dir` and point it to your own output directory that you can access later. (The default is temp directory in /tmp, which would be inside Docker and might not be accessible if the run dies)

And actually, if you use `--dry_run=true` just for the sake of finding out the commands, and then run each of the steps manually (still through docker), that actually gives you the best control, because you can see where all the intermediate files go.

As your point about using a sentinel file after each of the steps finishing - I totally understand the point, and agree that such solution can make resuming the run easier. I can file an internal issue to track this suggestion. However, the feature for resuming runs might not be able to prioritized soon based on our workload.

And overall, if you're putting things in a production pipeline, it might be better for you to have more control (by running the steps separately and have full control). I understand this is not ideal. But this is currently a trade-off for my team.
If you would be interested in helping us improving run_deepvariant.py and run_deeptrio.py, I'm also open to reviewing pull requests!

Thank you for reporting. I'll file a bug to track internally and can update here if we make more progress.
If you have any questions about the workaround I suggested, please feel free to follow up!

**Comment by dbrami** [comment]
Thanks for response @pichuan,
I think i will definitely strive to implement this, but wont be before February 2024.
I'm still having issues getting my analysis to run end to end on its own and also with manual intevention, depending on size of dataset from same sample...

I will ask remaining questions in separate tickets.
Thanks.

**Comment by pichuan** [comment]
Thank you @dbrami .

**Comment by SHuang-Broad** [comment]
I second this feature request.

We typically run DV in WDL (backed by Cromwell, on GCP) workflows. We try our best to take advantage of the spot machines but as you know, spot VMs can be preempted non-predictably and the more resource reserved for that machine, the chance is higher for it to be preempted within a certain period (i.e. smaller VMs survive longer before taken away). OTH smaller VMs take longer to finish the job on the same chunk of data, hence the overall preemption rate is likely the same as the bigger ones.

So if there's a way to do check-pointing, even during the execution of a step, and resuming from that after recovery from the preemption, it'd be a huge saving for us.

Thanks!
Steve
