### ISSUE TITLE
RNA-seq pre-processing

### ISSUE THREAD

**Issue by j0ntt** [google/deepvariant#791]
Hi,

A few questions about RNA-seq pre-processing before DeepVariant?

- Do you recommend read trimming before alignment using tools such as fastp?
- I can see that this is the repository for the human reference genome, which DeepVariant recommends. https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/ . But when I perform read alignment using STAR, can I use GCA_000001405.15_GRCh38_full_analysis_set.fna instead of GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz? GCA_000001405.15_GRCh38_full_analysis_set.fna has the GTF file, which is needed for creating the STAR index.
- Or can I perform the alignment using any GRCh38 reference genome? Does it have to be the same one, GCA_000001405.15_GRCh38_no_alt_analysis_set, used in the RNA-seq tutorial of DeepVariant.

**Comment by danielecook** [comment]
> Do you recommend read trimming before alignment using tools such as fastp?

No - we don't perform read trimming and in fact, this can hurt model performance (because we trained on untrimmed data). We observed this when running our models on processed with Opossum (which performs trimming):

<img width="1167" alt="image" src="https://github.com/google/deepvariant/assets/1536935/4e0cd335-0818-4cec-ae0c-ef294e98da39">

> I can see that this is the repository for the human reference genome, which DeepVariant recommends.

You can use a reference without alt contigs, but my guess is that it could contribute to a small increase in the number of errors. The reason is that without ALT contigs, STAR will map reads unambiguously (see https://github.com/alexdobin/STAR/issues/39), and DeepVariant will be more likely to call these variants because the reads won't be mapping ambiguously.

**Comment by malonzm1** [comment]
Can you recommend a GTF annotation?

**Comment by j0ntt** [comment]
@malonzm1 

I think that this should do fine. Can be found from the link I shared

GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf.gz

**Comment by j0ntt** [comment]
Hi @danielecook 

thanks for the quick response.

And is it ok to use STAR for alignment, or do you have some other tool you would recommend? The GTF file @malonzm1 referred to is needed for STAR..

**Comment by pichuan** [comment]
Hi @j0ntt , this has been inactive for a month, so I'll close it.
If there are remaining questions, please feel free to reopen with more details.
