### ISSUE TITLE
How to set threshold to filter vcf files

### ISSUE THREAD

**Issue by Tonitsk8264** [google/deepvariant#800]
Hello，

I have two problem about this:

1. In a VCF file generated by DeepVariant, what does "RefCall" in the FILTER column represent, and should it be removed when filtering VCF files?

2. For PASS-flagged variants in the PASS column, their QUAL values seem relatively small. Are there appropriate filtering thresholds for VCF, and are there recommended filtering criteria for corresponding values in the INFO column to ensure more accurate variant calling?

Thanks!
![企业微信截图_17119681423827](https://github.com/google/deepvariant/assets/143433202/e2ee15e6-3448-49e6-a12d-2dba90744207)

**Comment by lucasbrambrink** [comment]
Hi, thanks for the question.

1. RefCalls are candidates that were determined to match the reference and are therefore not variants. They are still included in the VCF file to show they were considered, since it can be just as important to know with high confidence that a particular variant does _not_ exist as it is to know that it does exist.

2. The `postprocess_variants` step applies quality filters, which can be set via flags.
     - [--qual_filter](https://github.com/google/deepvariant/blob/r1.6.1/deepvariant/postprocess_variants.py#L98-L102) will remove any variant with `QUAL < qual_filter`.
     - [--cnn_homref_call_min_gq](https://github.com/google/deepvariant/blob/r1.6.1/deepvariant/postprocess_variants.py#L103-L110) will set `RefCalls` to `./.` instead of `0/0` with `GQ < cnn_homref_call_min_gq`
     - [--multi_allelic_qual_filter](https://github.com/google/deepvariant/blob/r1.6.1/deepvariant/postprocess_variants.py#L111-L115) will remove multi-allelic variants with `QUAL <  multi_allelic_qual_filter`.

The default value for `--qual_filter` is 1.0. If this is too low, you can set this to a higher value using the [--postprocess_variants_extra_arg](https://github.com/google/deepvariant/blob/r1.6.1/scripts/run_deepvariant.py#L221-L229) flag in `run_deepvariant`, e.g. `--postprocess_variants_extra_args="qual_filter=5.0"`

I hope that helps!

**Comment by Tonitsk8264** [comment]
Thank you for your prompt reply !
