### ISSUE TITLE
Can't read tfrecord.gz file outputted from call_variants command

### ISSUE THREAD

**Issue by ssm0808** [google/deepvariant#82]
I want to understand the tfrecord.gz file outputted from call_variants ( called call_variants_output.tfrecord.gz )representation. I modified the visualizing_examples.ipynb not to read the tfrecord.gz file of call_variants. But the output of the modified script is like the following:
`features {
}
`
I don't believe that there are nothing in the call_varaints_output.tfrecord.gz file. Because the same all_varaints_output.tfrecord.gz file can generate the vcf file through the postprocess_variants tools. Could you tell me how to read the call_variants_output.tfrecord.gz file? Thanke you.

**Comment by pichuan** [comment]
Hi,
the output from the `call_variants` step is [CallVariantsOutput](https://github.com/google/deepvariant/blob/r0.6/deepvariant/protos/deepvariant.proto#L278)

The [visualizing_examples.ipynb](https://github.com/google/deepvariant/blob/r0.6/docs/visualizing_examples.ipynb) example you're referring to is attempting to parse the examples as `example_pb2.Example`. That's why it didn't work.

If you want to programmatically read output from the `call_variants` step, the best place to look at is the code in `postprocess_variants`. For example:
https://github.com/google/deepvariant/blob/r0.6/deepvariant/postprocess_variants.py#L829-L831

Let me know if you have more questions.

**Comment by pichuan** [comment]
Closing an old issue. If there are more questions, feel free to reopen.
