### ISSUE TITLE
training with multi-gpu

### ISSUE THREAD

**Issue by gambalab** [google/deepvariant#832]
Hi,
I was wondering if training with multiple GPUs is supported and, if so, if there is any specific flag to use or if it will be automatically activated when there is more than one GPU in your working environment.

Thank you in advance,
Regards

**Comment by akolesnikov** [comment]
Hi @gambalab,

Unfortunately, DeepVariant does not support multi-GPU training (or inference) at this time.

**Comment by 0809zheng** [comment]
Hi,
Since DeepVariant does not support multi-GPU training, I am pretty curious about "We have tested training with 1 and 2 GPUs and observed the following runtimes:" mentioned in the [training case](https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-training-case-study.md#start-train).
Specifically, how training with 2 GPUs achieved?

Thank you!
