### ISSUE TITLE
I read DeepVariant essay and want to download some data.

### ISSUE THREAD

**Issue by pioneer-pi** [google/deepvariant#852]
Hello, I read you essay "A universal sNP and small-indel variant caller using deep neural networks" in nature biotechnology. It's so good. I want to download the Platinum Genomes Project NA12878 data. I check it in the  supplementary information.  In supplementary note 11, there is a link[https://cloud.google.com/genomics/data/platinum-genomes.]( NA12878 Platinum Genomes BAM file). However, it's missing. So I want to ask if there is a new web that I can download it.
Thank you!!

**Comment by akolesnikov** [comment]
Hi @pioneer-pi,

You may find Platinum Genomes at [here](https://cloud.google.com/life-sciences/docs/resources/public-datasets/illumina-platinum-genomes).

**Comment by pioneer-pi** [comment]
@akolesnikov Sorry, I don't find the special version of reference, fastq, vcf in your essay in Platinume Genome Project NA12878. In the given link, I find different version of data. Can you support me the special version of data. Thank you very much!!!

**Comment by kishwarshafin** [comment]
@pioneer-pi , the deepvariant manuscript from six years ago. Since then, the benchmarking methods, tools and data all has been updated. The latest version of bechmarking is GIAB v4.2.1 for HG002 that you can find [here](https://ftp.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/). I would suggest reading the following manuscripts if you are interested to learn about these benchmarks:

1) https://cell.com/cell-genomics/fulltext/S2666-979X(22)00058-1
2) https://www.cell.com/cell-genomics/fulltext/S2666-979X-2200057-X
3) https://www.biorxiv.org/content/10.1101/2020.12.11.422022v1.abstract

The latest data can be found in: 

https://storage.googleapis.com/brain-genomics-public/research/sequencing/fastq/

https://storage.googleapis.com/brain-genomics-public/research/sequencing/grch37/

https://storage.googleapis.com/brain-genomics-public/research/sequencing/grch38/

**Comment by kishwarshafin** [comment]
@pioneer-pi , I will close this issue. Please feel free to reopen if you have further questions.
