### ISSUE TITLE
I have a question about training DeepVariant.

### ISSUE THREAD

**Issue by pioneer-pi** [google/deepvariant#858]
If I wanna train a customer DeepVariant on my own WGS data. I have two ideas:
1. Create training dataset(such as chr1-chr19) and train the model on each chr1 one by one independently(It means train a model on chr1 firstly, and then continue to train on chr2)
2. Create training dataset on all chr(chr1-chr19), shuffle the dataset and training.
Which way is deepvariant?

In addition, I wanna to train a clean DeepVariant(Only train on my own data, is it work?)

Thanks and except for you reply!

**Comment by AndrewCarroll** [comment]
Hi @pioneer-pi 

DeepVariant trains on all of chr1-chr19 and shuffles all together, as opposed to progressively going across chr1, chr2, etc... Because of some aspects of how training works, it's better to have the training batches be as uniformly sampled as possible.

That corresponds to number 2 in your list.

By "clean" DeepVariant, I assume that you mean to initialize from an InceptionV3 model that has been trained on ImageNet (that is only general images). This is possible, but you will need a large number of training examples, likely at least a few full whole genomes of examples, maybe something like 30 million created training examples, to get good performance. For most training experiments or setups, you will get better results training from an existing DeepVariant model checkpoint.

**Comment by pichuan** [comment]
Hi @pioneer-pi ,
Hopefully your question is answered. I'll close this issue now.
