### ISSUE TITLE
CPU and GPU using 

### ISSUE THREAD

**Issue by weiranmmm** [google/deepvariant#873]
Hello,

I've been using DeepTrio for de novo variant analysis, and it's been performing excellently. However, I noticed from the logs that DeepTrio uses the CPU to prepare data, which is quite time-consuming. In my case, it took 12 hours for one trio analysis, with an additional 4 hours on the GPU.

Given that renting GPU servers( usually with less CPU) is more expensive than CPU servers and access to privately owned GPU servers is limited, it seems inefficient to run lengthy CPU processes on a GPU server. It feels like a bit of a waste, and sometimes I half-jokingly feel there might be someone out there with murderous intent because of it!

Would it be possible in future updates to partition the DeepTrio analysis into separate steps? This way, CPU-intensive tasks could be completed on a CPU server, and then the job could be transferred to a GPU server for the remaining tasks. Alternatively, could the data preparation (CPU) and analysis (GPU) be run at the same time? This would help optimize resource usage and reduce costs.

Thank you for considering these suggestions.

**Comment by kishwarshafin** [comment]
@weiranmmm haha, I half jokingly thought "I hope DeepTrio doesn't get them into deep trouble". Good to know DeepTrio de novo analysis is working well for you.

Anyways, you can run each step of DeepTrio separately. For that, please set:

```
--intermediate_results_dir=${OUTPUT_DIR}/intermediate_files
```
And then, if you run your command using:
```bash
--dry_run=true
```

Then you should be able to see the three commands (`make_examples`, `call_variants`, `postprocess_variants`) separately. You can copy the commands and run them one after another instead of running "run_deeptrio" and can only ask for GPU for the `call_variants` part. Let me know if you need further instructions.

**Comment by weiranmmm** [comment]
@kishwarshafin 
These commands have been really helpful to me, and I can't wait to try them out. 
Thank you so much for your suggestions!
