### ISSUE TITLE
termination of the process

### ISSUE THREAD

**Issue by vendig** [google/deepvariant#88]
Hi. DeepVariant requires more than 60 minutes running time. I am encountering a problem of a termination of googleCloud shell after 60 minutes. I am trying to find a way to extent the running time of an idle. So far I could not find any relevant solution. Please let me know hot to prevent the googleCloud termination in order to successfully execute DeepVariant? Thank you a lot.  

I tried to use screen mode. When the screen mode was used, I got an error running following command (branch 0.7):
( time seq 0 $((N_SHARDS-1)) | \
  parallel --halt 2 --joblog "${LOG_DIR}/log" --res "${LOG_DIR}" \
    sudo docker run \
      -v /home/${USER}:/home/${USER} \
      gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
      /opt/deepvariant/bin/make_examples \
      --mode calling \
      --ref "${REF}" \
      --reads "${BAM}" \
      --examples "${EXAMPLES}" \
      --gvcf "${GVCF_TFRECORDS}" \
      --task {} \
) >"${LOG_DIR}/make_examples.log" 2>&1

I got an error: -bash: /make_examples.log: Permission denied

Then I went out of the screen mode and try to run same command again and the error was still there.
Thank you a lot for the help.

**Comment by pichuan** [comment]
First of all, from the error you're seeing, I think you forgot to set up the variables in that shell. Basically, if you do `echo $LOG_DIR` in that shell, you'll find it's empty.

And, instead of directly using a Google Cloud shell in the browser, you can consider ssh into your machine from a terminal, like in this section:
https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-case-study.md#request-a-machine
You can do something like `gcloud compute ssh "${USER}-deepvariant-casestudy" --zone "us-west1-b"`

Using screen should certainly work. You'll just need to paste in the variable settings in this section again, because otherwise they'll all be empty strings.
https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-case-study.md#preliminaries
