### ISSUE TITLE
VAF != AD[1]/(AD[0]+AD[1])

### ISSUE THREAD

**Issue by minw2828** [google/deepvariant#880]
Hello, 

Thank you for developing the tool. 

I expected the VAF field to be roughly equal to the fraction of alternative alleles in reads, but that wasn't the case. Would you know why? 

In the example below, the first variant has a VAF of 25%, but the read depth of REF allele is 6 and the alternative allele is also 6. I had expected the VAF to be about 50%.
The second variant has a VAF of 52.1739%, but the read depth of REF alelle is 6 and the alternative allele is 12. I had expected the VAF to be about 66.67%. 

```
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth for each allele">
##FORMAT=<ID=VAF,Number=A,Type=Float,Description="Variant allele fractions.">
chr13	32323151	.	A	AT	45.1	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:21:24:6,6:0.25:45,24,44
chr13	32349216	.	CA	C	8.3	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:8:23:6,12:0.521739:7,0,22
```

Could you help me interpret the discrepancy in the `VAF` field and the `AD` field, please? 

Many thanks,
Min

**Comment by kishwarshafin** [comment]
Hi @minw2828 , VAF as it stands is variant allele frequency. 

This is how it's calculated for the two variants:

```bash
chr13	32323151	.	A	AT	45.1	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:21:24:6,6:0.25:45,24,44
GT:GQ:DP:AD:VAF:PL 0/1:21:24:6,6:0.25:45,24,44
# which means
GT=0/1 (genotype)
DP=24 (depth)
AD=[6,6] (Allelic depths of two allele 0 and 1)
```
So the VAF becomes:
VAF=AD[1]/DP = 6/6 = 0.25 
AD[1] is because we are taking the alternate allele.

For the second one:
```bash
chr13	32349216	.	CA	C	8.3	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:8:23:6,12:0.521739:7,0,22
GT:GQ:DP:AD:VAF:PL 0/1:8:23:6,12:0.521739:7,0,22
# which means
GT=0/1 (genotype)
DP=23 (depth)
AD=[6,12] (Allelic depths of two allele 0 and 1)
```
So the VAF becomes:
VAF=AD[1]/DP = 12/23 = 0.521739130434783
Which is the reported to the sixth precision point.

Let me know if you have further questions. VAF is specific to the allele called in a record, not all of the alleles, VAF calculated that way would always be 1.0 as the sum of all alternate alleles including reference allele would sum to the depth we observe in that site.

Hope this helps.
